import type { Prisma, PrismaClient } from "../../generated/client/index.js";

const s=(v:any)=>v==null?undefined:String(v), n=(v:any)=>Number.isFinite(Number(v))?Number(v):undefined;
const cents=(v:any)=>Math.round((Number(v)||0)*100);
function isoDate(date:any,time="00:00"){if(!date)return undefined;const raw=String(date);if(/T/.test(raw))return new Date(raw);return new Date(`${raw}T${time||"00:00"}:00`)}
function arr<T=any>(v:any):T[]{return Array.isArray(v)?v:[]}
function record(v:any):Record<string,any>{return v&&typeof v==="object"&&!Array.isArray(v)?v:{}}
function json(v:any): Prisma.InputJsonValue { return sanitizeJson(v) as Prisma.InputJsonValue }
function sanitizeJson(v:any): any { if(v===undefined)return null; if(v===null||typeof v!=="object")return v; if(Array.isArray(v))return v.map(sanitizeJson); return Object.fromEntries(Object.entries(v).filter(([,value])=>value!==undefined).map(([key,value])=>[key,sanitizeJson(value)])); }
function legacyAppointmentStatus(status:any){const v=String(status??"").toLowerCase();if(/realiz|complet/.test(v))return"COMPLETED" as const;if(/npa|ausente|no.show|no presentado/.test(v))return"NO_SHOW" as const;if(/gabinete|chair/.test(v))return"IN_CHAIR" as const;if(/espera|lleg/.test(v))return"ARRIVED" as const;if(/confirm/.test(v))return"CONFIRMED" as const;if(/cancel/.test(v))return"CANCELLED" as const;return"PLANNED" as const}
function clinicalStatus(status:any){const v=String(status??"").toLowerCase();if(/complet|realiz|hecho|finaliz/.test(v))return"COMPLETED" as const;if(/cancel/.test(v))return"CANCELLED" as const;if(/aplaz|defer/.test(v))return"DEFERRED" as const;if(/activ|curso|progress/.test(v))return"ACTIVE" as const;return"PLANNED" as const}
function budgetStatus(status:any){const v=String(status??"").toLowerCase();if(/parcial/.test(v))return"PARTIALLY_ACCEPTED" as const;if(/acept/.test(v))return"ACCEPTED" as const;if(/rechaz/.test(v))return"REJECTED" as const;if(/caduc|expir/.test(v))return"EXPIRED" as const;if(/present|entreg/.test(v))return"PRESENTED" as const;return"DRAFT" as const}
function paymentMethod(method:any){const v=String(method??"").toLowerCase();if(/efect|cash/.test(v))return"CASH" as const;if(/tarjet|card|tpv/.test(v))return"CARD" as const;if(/transf/.test(v))return"TRANSFER" as const;if(/finan/.test(v))return"FINANCING" as const;return"OTHER" as const}
function safeId(prefix:string,value:any){return`${prefix}-${String(value).replace(/[^a-zA-Z0-9_-]/g,"_")}`}
function legacySpecialtyForTreatmentCode(code:any){const value=String(code??"").toLowerCase();if(/implant|sinus|bone|regener|graft/.test(value))return"Implantología";if(/ortho|bracket|aligner|invis|retainer/.test(value))return"Ortodoncia";if(/endo|root_canal|pulp/.test(value))return"Endodoncia";if(/perio|scal|root_plan|hygien|cleaning/.test(value))return"Periodoncia e higiene";if(/extract|surgery|surgical|exodon/.test(value))return"Cirugía";if(/crown|bridge|prost|removable|denture|onlay|veneer|maryland/.test(value))return"Prótesis y rehabilitación";if(/restor|filling|caries|composite|reconstruction/.test(value))return"Conservadora";if(/whiten|aesthetic|esthetic/.test(value))return"Estética";if(/pedo|pulpotomy|pulpectomy|space_maintainer/.test(value))return"Odontopediatría";return"Otros"}

export async function importLegacyState(prisma:PrismaClient,state:any,options:{clinicId?:string;clinicName?:string}={}){
  const clinicId=options.clinicId??"legacy-clinic";
  await prisma.clinic.upsert({where:{id:clinicId},create:{id:clinicId,name:options.clinicName??state?.settings?.clinicName??"Denty"},update:{name:options.clinicName??state?.settings?.clinicName??"Denty"}});
  const siteMap=new Map<any,string>(),staffMap=new Map<any,string>(),patientMap=new Map<any,string>(),clinicalItemMap=new Map<any,string>(),planByPatient=new Map<any,string>();

  for(const x of arr(state?.sites)){
    const id=safeId("legacy-site",x.id);await prisma.site.upsert({where:{id},create:{id,clinicId,name:s(x.name)??`Sede ${x.id}`,address:s(x.address),active:x.active!==false},update:{name:s(x.name)??`Sede ${x.id}`,address:s(x.address),active:x.active!==false}});siteMap.set(x.id,id);
  }
  if(!siteMap.size){const id="legacy-site-main";await prisma.site.upsert({where:{id},create:{id,clinicId,name:"Sede principal",active:true},update:{active:true}});siteMap.set("main",id)}

  const staffRows=arr(state?.employees).length?arr(state?.employees):arr(state?.doctors??state?.staff);
  for(const x of staffRows){
    const id=safeId("legacy-staff",x.id);await prisma.staffProfile.upsert({where:{id},create:{id,clinicId,displayName:s(x.name)??s(x.displayName)??`Profesional ${x.id}`,role:/aux|assist/i.test(String(x.role??""))?"ASSISTANT":"DENTIST",active:x.active!==false},update:{displayName:s(x.name)??s(x.displayName)??`Profesional ${x.id}`,active:x.active!==false}});staffMap.set(x.id,id);
    const legacySite=x.site_id??x.siteId,siteId=siteMap.get(legacySite)??siteMap.values().next().value;if(siteId)await prisma.staffSite.upsert({where:{staffId_siteId:{staffId:id,siteId}},create:{clinicId,staffId:id,siteId},update:{clinicId}});
  }

  for(const x of arr(state?.patients)){
    const legacyId=n(x.id),existing=legacyId!=null?await prisma.patient.findFirst({where:{clinicId,legacyId}}):null;
    const data={clinicId,legacyId,recordNumber:s(x.recordNumber??x.historyNumber??x.history_no),firstName:s(x.firstName??x.name?.split?.(" ")?.[0])??"Paciente",lastName:s(x.lastName??x.surname??x.name?.split?.(" ")?.slice?.(1)?.join?.(" "))??"",dni:s(x.dni??x.nif),phone:s(x.phone??x.mobile),email:s(x.email),birthDate:x.birthDate||x.birth_date?new Date(x.birthDate??x.birth_date):undefined,notes:s(x.notes)};
    const patient=existing?await prisma.patient.update({where:{id:existing.id},data}):await prisma.patient.create({data});patientMap.set(x.id,patient.id);
  }

  for(const x of arr(state?.appointments)){
    const patientId=patientMap.get(x.patientId??x.patient_id),staffId=staffMap.get(x.doctorId??x.staffId??x.employee_id),siteId=siteMap.get(x.siteId??x.site_id)??siteMap.values().next().value;if(!patientId||!staffId||!siteId)continue;
    const id=safeId("legacy-appointment",x.id),startsAt=isoDate(x.date,x.time??x.start_time)??new Date(),duration=n(x.duration??x.duration_minutes)??30,endsAt=x.end_time?isoDate(x.date,x.end_time)!:new Date(startsAt.getTime()+duration*60000),status=legacyAppointmentStatus(x.status);
    const appointment=await prisma.appointment.upsert({where:{id},create:{id,clinicId,patientId,staffId,siteId,startsAt,endsAt,status,title:s(x.title)??s(x.reason)??"Cita",reason:s(x.reason),arrivedAt:x.arrived_at?new Date(x.arrived_at):undefined,chairAt:x.chair_at?new Date(x.chair_at):undefined,absentAt:x.absent_at?new Date(x.absent_at):undefined,completedAt:x.completed_at?new Date(x.completed_at):undefined},update:{startsAt,endsAt,status,title:s(x.title)??s(x.reason)??"Cita",reason:s(x.reason),arrivedAt:x.arrived_at?new Date(x.arrived_at):undefined,chairAt:x.chair_at?new Date(x.chair_at):undefined,absentAt:x.absent_at?new Date(x.absent_at):undefined,completedAt:x.completed_at?new Date(x.completed_at):undefined}});
    if(status==="NO_SHOW"){const eventId=safeId("legacy-analytics-npa",x.id),durationMinutes=Math.max(0,Math.round((endsAt.getTime()-startsAt.getTime())/60000));await prisma.analyticsEvent.upsert({where:{id:eventId},create:{id:eventId,clinicId,occurredAt:x.absent_at?new Date(x.absent_at):startsAt,type:"appointment.no_show",category:"appointment",patientId,staffId,siteId,appointmentId:appointment.id,lossCents:0,metadataJson:{backfilled:true,unvaluedHistorical:true,durationMinutes,reason:"No existe margen histórico fiable para valorar económicamente este NPA importado."}},update:{occurredAt:x.absent_at?new Date(x.absent_at):startsAt,patientId,staffId,siteId,appointmentId:appointment.id,lossCents:0,metadataJson:{backfilled:true,unvaluedHistorical:true,durationMinutes,reason:"No existe margen histórico fiable para valorar económicamente este NPA importado."}}})}
  }

  // Legacy odontogram V2/V3 + periodontal data + snapshots.
  const odontograms=record(state?.odontograms),entityBuckets=record(state?.odontogramEntities),snapshotBuckets=record(state?.odontogramSnapshots);
  for(const [legacyPatientId,patientId] of patientMap){
    const toothMap=record(odontograms[String(legacyPatientId)]??odontograms[legacyPatientId]);
    const legacyEntities=arr(entityBuckets[String(legacyPatientId)]??entityBuckets[legacyPatientId]);
    const legacySnapshots=arr(snapshotBuckets[String(legacyPatientId)]??snapshotBuckets[legacyPatientId]);
    if(!Object.keys(toothMap).length&&!legacyEntities.length&&!legacySnapshots.length)continue;
    const odontogram=await prisma.odontogram.upsert({where:{clinicId_patientId:{clinicId,patientId}},create:{clinicId,patientId},update:{version:{increment:1}}});
    await prisma.periodontalMeasurement.deleteMany({where:{odontogramId:odontogram.id}});
    for(const [tooth,rawTooth] of Object.entries(toothMap)){
      const t=record(rawTooth),whole=arr<string>(t.whole_states).length?arr<string>(t.whole_states):(t.status&&t.status!=="healthy"?[String(t.status)]:[]);
      for(const code of whole){const id=safeId(`legacy-dental-${legacyPatientId}-${tooth}-whole`,code);await prisma.dentalEntity.upsert({where:{id},create:{id,odontogramId:odontogram.id,tooth:String(tooth),entityType:"tooth_state",status:String(code),attributesJson:{source:"legacy",legacyStatus:t.status??null}},update:{status:String(code),active:true,attributesJson:{source:"legacy",legacyStatus:t.status??null}}})}
      for(const [surface,code] of Object.entries(record(t.surfaces))){if(!code)continue;const id=safeId(`legacy-dental-${legacyPatientId}-${tooth}-surface-${surface}`,code);await prisma.dentalEntity.upsert({where:{id},create:{id,odontogramId:odontogram.id,tooth:String(tooth),entityType:"surface_state",status:String(code),surfacesJson:[String(surface)],attributesJson:{source:"legacy"}},update:{status:String(code),surfacesJson:[String(surface)],active:true}})}
      const perio=record(t.periodontal),depths=record(perio.depths),recession=record(perio.recession),bleeding=record(perio.bleeding),plaque=record(perio.plaque);
      const sites=new Set([...Object.keys(depths),...Object.keys(recession),...Object.keys(bleeding),...Object.keys(plaque)]);for(const site of sites){const pd=n(depths[site]),rec=n(recession[site]),b=Boolean(bleeding[site]),p=Boolean(plaque[site]);if(pd==null&&rec==null&&!b&&!p)continue;await prisma.periodontalMeasurement.create({data:{odontogramId:odontogram.id,tooth:String(tooth),site,probingDepth:pd,recession:rec,bleeding:b,plaque:p,mobility:n(perio.mobility),furcation:n(perio.furcation)}})}
    }
    for(const e of legacyEntities){const id=safeId("legacy-odontogram-entity",e.id??`${legacyPatientId}-${e.type}-${arr(e.teeth).join("-")}`),teeth=arr<string>(e.teeth);await prisma.dentalEntity.upsert({where:{id},create:{id,odontogramId:odontogram.id,tooth:teeth[0],arch:s(e.arch),entityType:s(e.type)??"legacy_entity",status:s(e.status)??"planned",attributesJson:{source:"legacy_v3",teeth,components:e.components??[],metadata:e.metadata??{},legacyId:e.id},active:e.active!==false},update:{tooth:teeth[0],arch:s(e.arch),entityType:s(e.type)??"legacy_entity",status:s(e.status)??"planned",attributesJson:{source:"legacy_v3",teeth,components:e.components??[],metadata:e.metadata??{},legacyId:e.id},active:e.active!==false}})}
    for(const snap of legacySnapshots){const id=safeId("legacy-dental-snapshot",snap.snapshot_id??snap.id??`${legacyPatientId}-${snap.captured_at}`);await prisma.dentalSnapshot.upsert({where:{id},create:{id,odontogramId:odontogram.id,label:s(snap.label),payloadJson:{odontogram:snap.odontogram??{},entities:snap.entities??[],clinicalPlanItemIds:snap.clinicalPlanItemIds??[]},createdAt:snap.captured_at?new Date(snap.captured_at):undefined},update:{label:s(snap.label),payloadJson:{odontogram:snap.odontogram??{},entities:snap.entities??[],clinicalPlanItemIds:snap.clinicalPlanItemIds??[]}}})}
  }

  // Clinical plan V7/V3: atomic items first, dependencies second.
  const legacyClinicalItems=arr(state?.clinicalPlanItems);
  const ensurePlan=async(legacyPatientId:any)=>{if(planByPatient.has(legacyPatientId))return planByPatient.get(legacyPatientId)!;const patientId=patientMap.get(legacyPatientId);if(!patientId)return undefined;const id=safeId("legacy-clinical-plan",legacyPatientId);await prisma.clinicalPlan.upsert({where:{id},create:{id,clinicId,patientId,title:"Plan clínico importado",status:"ACTIVE"},update:{title:"Plan clínico importado",status:"ACTIVE",version:{increment:1}}});planByPatient.set(legacyPatientId,id);return id};
  for(const x of legacyClinicalItems){const patientId=patientMap.get(x.patient_id??x.patientId),planId=await ensurePlan(x.patient_id??x.patientId);if(!patientId||!planId)continue;const id=safeId("legacy-clinical-item",x.id),staffId=staffMap.get(x.clinician_id??x.employee_id),status=clinicalStatus(x.status),treatmentCode=s(x.treatment)??s(x.treatmentCode)??"treatment";await prisma.clinicalPlanItem.upsert({where:{id},create:{id,planId,clinicianId:staffId,tooth:s(x.tooth),treatmentCode,label:s(x.title)??s(x.label)??s(x.treatment)??"Tratamiento",patientLabel:s(x.patient_title??x.patientLabel),clinicalReason:s(x.patient_reason??x.clinical_cause??x.priority_reason),phase:n(x.phase_rank??x.phase)??5,priority:n(x.priority)??0,status,durationMin:n(x.duration??x.duration_minutes),priceCents:cents(x.price),source:s(x.source)??"legacy",sourceRefId:s(x.source_key??x.id)},update:{clinicianId:staffId,tooth:s(x.tooth),treatmentCode,label:s(x.title)??s(x.label)??s(x.treatment)??"Tratamiento",patientLabel:s(x.patient_title??x.patientLabel),clinicalReason:s(x.patient_reason??x.clinical_cause??x.priority_reason),phase:n(x.phase_rank??x.phase)??5,priority:n(x.priority)??0,status,durationMin:n(x.duration??x.duration_minutes),priceCents:cents(x.price),source:s(x.source)??"legacy",sourceRefId:s(x.source_key??x.id)}});clinicalItemMap.set(x.id,id);const completedAt=x.completed_at??x.completedAt??x.completed_on??x.updated_at??x.updatedAt;if(status==="COMPLETED"&&completedAt){const eventId=safeId("legacy-analytics-treatment",x.id);await prisma.analyticsEvent.upsert({where:{id:eventId},create:{id:eventId,clinicId,occurredAt:new Date(completedAt),type:"treatment.completed",category:treatmentCode,specialty:legacySpecialtyForTreatmentCode(treatmentCode),patientId,staffId,clinicalPlanItemId:id,revenueCents:cents(x.price),costCents:0,metadataJson:{backfilled:true,historicalCostUnavailable:true}},update:{occurredAt:new Date(completedAt),category:treatmentCode,specialty:legacySpecialtyForTreatmentCode(treatmentCode),patientId,staffId,clinicalPlanItemId:id,revenueCents:cents(x.price),costCents:0,metadataJson:{backfilled:true,historicalCostUnavailable:true}}})}}
  for(const x of legacyClinicalItems){const itemId=clinicalItemMap.get(x.id),planId=planByPatient.get(x.patient_id??x.patientId);if(!itemId||!planId)continue;for(const dep of arr(x.depends_on??x.manual_depends_on)){const dependsOnId=clinicalItemMap.get(dep);if(dependsOnId&&dependsOnId!==itemId)await prisma.clinicalPlanDependency.upsert({where:{itemId_dependsOnId:{itemId,dependsOnId}},create:{planId,itemId,dependsOnId,reason:"Dependencia importada desde Denty legacy"},update:{reason:"Dependencia importada desde Denty legacy"}})}}

  // Older treatmentPlans are preserved as plan items when no equivalent atomic item exists.
  for(const plan of arr(state?.treatmentPlans)){const legacyPatientId=plan.patient_id??plan.patientId,planId=await ensurePlan(legacyPatientId);if(!planId)continue;let previous:string|undefined;for(const step of arr(plan.steps)){const id=safeId("legacy-plan-step",step.id??`${plan.id}-${step.order}`);await prisma.clinicalPlanItem.upsert({where:{id},create:{id,planId,treatmentCode:s(plan.type)??"legacy_step",label:s(step.title)??"Paso clínico",patientLabel:s(step.title),clinicalReason:s(step.reason),phase:n(step.order)??5,priority:0,status:clinicalStatus(step.status),durationMin:n(step.duration),source:"legacy_treatment_plan",sourceRefId:s(plan.id)},update:{label:s(step.title)??"Paso clínico",clinicalReason:s(step.reason),status:clinicalStatus(step.status),durationMin:n(step.duration)}});if(previous)await prisma.clinicalPlanDependency.upsert({where:{itemId_dependsOnId:{itemId:id,dependsOnId:previous}},create:{planId,itemId:id,dependsOnId:previous,reason:"Orden original del plan legacy"},update:{}});previous=id}}

  // Treatment alternatives, including patient preference and clinician selection where present.
  for(const group of arr(state?.clinicalAlternativeGroups)){
    const planId=await ensurePlan(group.patient_id??group.patientId);
    if(!planId)continue;
    const setId=safeId("legacy-alternative-set",group.id);
    await prisma.clinicalAlternativeSet.upsert({
      where:{id:setId},
      create:{id:setId,planId,title:s(group.title)??"Alternativas de tratamiento",toothOrZone:s(group.tooth??group.context),contextJson:{context:group.context??null,checks:group.context_checks??{},legacyStatus:group.status??null}},
      update:{title:s(group.title)??"Alternativas de tratamiento",toothOrZone:s(group.tooth??group.context),contextJson:{context:group.context??null,checks:group.context_checks??{},legacyStatus:group.status??null}}
    });
    for(const option of arr(group.options)){
      const optionId=safeId("legacy-alternative-option",option.id);
      await prisma.clinicalAlternativeOption.upsert({
        where:{id:optionId},
        create:{id:optionId,setId,code:s(option.key??option.code)??String(option.id),title:s(option.title)??"Alternativa",summary:s(option.summary),prosJson:json(arr(option.pros)),consJson:json(arr(option.cons)),maintenance:s(option.maintenance),invasiveness:s(option.invasiveness),stability:s(option.stability),relativeTime:s(option.time_relative??option.relativeTime),relativeCost:s(option.cost_relative??option.relativeCost),reversibility:s(option.reversibility),limitationsJson:json(arr(option.limitations)),requiredDataJson:json(arr(option.required_context)),missingDataJson:json(arr(option.required_context).filter((k:any)=>group.context_checks?.[k]!==true)),status:Number(group.approved_option_id)===Number(option.id)?"CLINICALLY_APPROVED":"AVAILABLE",routeJson:json(option.plan??[])},
        update:{title:s(option.title)??"Alternativa",summary:s(option.summary),prosJson:json(arr(option.pros)),consJson:json(arr(option.cons)),routeJson:json(option.plan??[])}
      });
      if(Number(group.patient_preference?.option_id)===Number(option.id)){
        const patientId=patientMap.get(group.patient_id??group.patientId);
        if(patientId){
          const pref=await prisma.patientTreatmentPreference.findFirst({where:{patientId,optionId}});
          if(!pref)await prisma.patientTreatmentPreference.create({data:{patientId,optionId,preference:"INTERESTED",note:"Preferencia importada desde Denty legacy"}});
        }
      }
    }
  }

  // Budgets retain their treatment links and monetary snapshot.
  for(const b of arr(state?.budgets)){const legacyPatientId=b.patient_id??b.patientId,patientId=patientMap.get(legacyPatientId);if(!patientId)continue;const id=safeId("legacy-budget",b.id),code=s(b.code)??`LEGACY-${String(b.id)}`,planId=planByPatient.get(legacyPatientId),rawItems=arr(b.items),total=cents(b.total),discount=cents(b.discount);await prisma.budget.upsert({where:{id},create:{id,clinicId,patientId,planId,code,status:budgetStatus(b.status),subtotalCents:Math.max(0,total+discount),discountCents:discount,totalCents:total,createdAt:b.created_at?new Date(b.created_at):undefined},update:{planId,status:budgetStatus(b.status),subtotalCents:Math.max(0,total+discount),discountCents:discount,totalCents:total}});await prisma.budgetItem.deleteMany({where:{budgetId:id}});for(const item of rawItems){const price=cents(item.price??item.unitPrice??item.total),qty=Math.max(1,n(item.qty??item.quantity)??1),clinicalPlanItemId=clinicalItemMap.get(item.clinical_plan_item_id??item.clinicalPlanItemId);await prisma.budgetItem.create({data:{budgetId:id,clinicalPlanItemId,description:s(item.title??item.label??item.description)??"Tratamiento",tooth:s(item.tooth),quantity:qty,unitPriceCents:price,totalCents:cents(item.total??(Number(item.price??0)*qty)),accepted:item.accepted==null?undefined:Boolean(item.accepted)}})}}

  for(const p of arr(state?.payments)){const patientId=patientMap.get(p.patient_id??p.patientId);if(!patientId)continue;const id=safeId("legacy-payment",p.id),receivedEvidence=p.received_at??p.date;const payment=await prisma.payment.upsert({where:{id},create:{id,clinicId,patientId,amountCents:cents(p.amount??p.total),method:paymentMethod(p.method??p.type),reference:s(p.reference??p.note),receivedAt:receivedEvidence?new Date(receivedEvidence):undefined},update:{amountCents:cents(p.amount??p.total),method:paymentMethod(p.method??p.type),reference:s(p.reference??p.note)}});if(receivedEvidence){const eventId=safeId("legacy-analytics-payment",p.id);await prisma.analyticsEvent.upsert({where:{id:eventId},create:{id:eventId,clinicId,occurredAt:new Date(receivedEvidence),type:"payment.received",patientId,paymentId:payment.id,revenueCents:cents(p.amount??p.total),costCents:0,metadataJson:{backfilled:true}},update:{occurredAt:new Date(receivedEvidence),patientId,paymentId:payment.id,revenueCents:cents(p.amount??p.total),costCents:0,metadataJson:{backfilled:true}}})}}

  return{clinicId,patients:patientMap.size,staff:staffMap.size,sites:siteMap.size,appointments:arr(state?.appointments).length,odontograms:Object.keys(odontograms).length,clinicalPlanItems:legacyClinicalItems.length,budgets:arr(state?.budgets).length,payments:arr(state?.payments).length};
}
