"use client";
import {FormEvent,useState} from "react";
import {api} from "../../../lib/api";
import {useApiData} from "../../../lib/use-api-data";
import {useSession} from "../../../features/auth/use-session";

export default function Documents(){
  const[patientId,setPatientId]=useState(""),[showTemplates,setShowTemplates]=useState(false),[showCreate,setShowCreate]=useState(false),[error,setError]=useState("");
  const{actor}=useSession(),canWrite=Boolean(actor?.permissions?.includes("documents.write")),canSign=Boolean(actor?.permissions?.includes("documents.sign")||actor?.permissions?.includes("documents.write")),canManageTemplates=Boolean(actor?.permissions?.includes("settings.manage")),{data,refresh}=useApiData<any>(`/api/documents${patientId?`?patientId=${patientId}`:""}`,{items:[]}),{data:templates,refresh:refreshTemplates}=useApiData<any>("/api/document-templates",{items:[]});
  async function run(fn:()=>Promise<unknown>){setError("");try{await fn();await refresh()}catch(e:any){setError(e?.payload?.error?.message??e?.message??"No se pudo completar la acción")}}
  async function finalize(id:string){await run(()=>api(`/api/documents/${id}/finalize`,{method:"POST",body:"{}"}))}
  async function sign(id:string){const signerName=window.prompt("Nombre de quien firma",actor?.displayName??"")?.trim();if(!signerName)return;await run(()=>api(`/api/documents/${id}/sign`,{method:"POST",body:JSON.stringify({signerName})}))}
  async function deliver(id:string){await run(()=>api(`/api/documents/${id}/deliver`,{method:"POST",body:JSON.stringify({channel:"PORTAL"})}))}
  async function archive(id:string){if(!window.confirm("Archivar este documento? El PDF y su hash se conservarán."))return;await run(()=>api(`/api/documents/${id}/archive`,{method:"POST",body:"{}"}))}
  async function createTemplate(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setError("");try{await api("/api/document-templates",{method:"POST",body:JSON.stringify({code:f.get("code"),title:f.get("title"),body:f.get("body")})});setShowCreate(false);await refreshTemplates()}catch(e:any){setError(e?.payload?.error?.message??e?.message??"No se pudo crear la plantilla")}}
  async function newVersion(t:any){const body=window.prompt(`Nueva versión de ${t.title}`,t.versions?.[0]?.body??"");if(body==null)return;const title=window.prompt("Título de la plantilla",t.title)??t.title;setError("");try{await api(`/api/document-templates/${t.id}/versions`,{method:"POST",body:JSON.stringify({title,body})});await refreshTemplates()}catch(e:any){setError(e?.payload?.error?.message??e?.message??"No se pudo crear la versión")}}
  return <><header className="native-topbar"><div><h1>Documentos</h1><p>Plantillas versionadas, PDF final inmutable, entrega y firma trazable.</p><small>La firma integrada de Denty es una firma electrónica simple con evidencia de identidad, fecha e integridad del documento.</small></div><div className="native-toolbar">{canManageTemplates&&<button className="native-button" onClick={()=>setShowTemplates(v=>!v)}>Plantillas</button>}{canManageTemplates&&<button className="native-button primary" onClick={()=>setShowCreate(v=>!v)}>+ Plantilla</button>}</div></header>
  {error&&<div className="native-error">{error}</div>}
  {showCreate&&<form className="native-card native-grid" onSubmit={createTemplate} style={{marginBottom:14}}><h2>Nueva plantilla</h2><div className="native-toolbar"><input className="native-input" name="code" placeholder="Código" required/><input className="native-input" name="title" placeholder="Título" required/></div><textarea className="native-input" name="body" rows={7} placeholder="Texto con variables como {{patientName}}" required/><div><button className="native-button primary">Crear versión 1</button></div></form>}
  {showTemplates&&<section className="native-card" style={{marginBottom:14}}><h2>Plantillas activas</h2><table className="native-table"><thead><tr><th>Plantilla</th><th>Versión activa</th><th>Historial</th><th></th></tr></thead><tbody>{templates.items.map((t:any)=><tr key={t.id}><td><b>{t.title}</b><br/><small>{t.code}</small></td><td>v{t.activeVersion}</td><td>{(t.versions??[]).map((v:any)=>`v${v.version}`).join(" · ")}</td><td><button className="native-button" onClick={()=>newVersion(t)}>Nueva versión</button></td></tr>)}</tbody></table></section>}
  <div className="native-toolbar"><input className="native-input" placeholder="Filtrar patientId" value={patientId} onChange={e=>setPatientId(e.target.value)}/></div><div className="native-card"><table className="native-table"><thead><tr><th>Documento</th><th>Tipo</th><th>Estado</th><th>Creado</th><th>Entrega</th><th>Acciones</th></tr></thead><tbody>{data.items.map((d:any)=><tr key={d.id}><td><b>{d.title}</b>{d.signatures?.length?<><br/><small>Firmas: {d.signatures.length}</small></>:null}</td><td>{d.type}</td><td><span className="native-badge">{d.status}</span></td><td>{new Date(d.createdAt).toLocaleDateString("es-ES")}</td><td>{d.deliveredAt?new Date(d.deliveredAt).toLocaleDateString("es-ES"):"—"}</td><td><div className="native-toolbar">{canWrite&&d.status==="DRAFT"&&<button className="native-button" onClick={()=>finalize(d.id)}>Finalizar PDF</button>}{canSign&&["FINAL","SIGNED"].includes(d.status)&&<button className="native-button" onClick={()=>sign(d.id)}>Firmar</button>}{canWrite&&["FINAL","SIGNED"].includes(d.status)&&!d.deliveredAt&&<button className="native-button" onClick={()=>deliver(d.id)}>Entregar al portal</button>}{canWrite&&d.status!=="DRAFT"&&<button className="native-button" onClick={()=>archive(d.id)}>Archivar</button>}</div></td></tr>)}</tbody></table>{!data.items.length&&<div className="native-empty">Sin documentos activos.</div>}</div></>}
