"use client";
import {useState} from "react";
import {api} from "../../lib/api";

export function PlanGraphEditor({plan,onChange}:{plan:any;onChange:()=>Promise<unknown>|unknown}){
 const[itemId,setItemId]=useState(""),[dependsOnId,setDependsOnId]=useState(""),[dependencyReason,setDependencyReason]=useState("Dependencia clínica definida por el profesional"),[overrideItemId,setOverrideItemId]=useState(""),[priority,setPriority]=useState("0"),[phase,setPhase]=useState("5"),[priorityOverrideReason,setPriorityOverrideReason]=useState("");
 const items=plan?.items??[],deps=plan?.dependencies??[];
 async function add(){if(!itemId||!dependsOnId||itemId===dependsOnId||!dependencyReason.trim())return;await api(`/api/clinical-plans/${plan.id}/dependencies`,{method:"POST",body:JSON.stringify({itemId,dependsOnId,reason:dependencyReason.trim()})});await onChange();}
 async function remove(dep:any){const reason=window.prompt("Motivo para quitar esta dependencia clínica");if(!reason?.trim())return;const q=new URLSearchParams({itemId:dep.itemId,dependsOnId:dep.dependsOnId,reason:reason.trim()});await api(`/api/clinical-plans/${plan.id}/dependencies?${q}`,{method:"DELETE"});await onChange();}
 async function override(){if(!overrideItemId||!priorityOverrideReason.trim())return;await api(`/api/clinical-plan/items/${overrideItemId}/priority-override`,{method:"POST",body:JSON.stringify({priority:Number(priority),phase:Number(phase),reason:priorityOverrideReason.trim()})});setPriorityOverrideReason("");await onChange();}
 function selectOverride(id:string){setOverrideItemId(id);const item=items.find((x:any)=>x.id===id);if(item){setPriority(String(item.priority??0));setPhase(String(item.phase??5));setPriorityOverrideReason(item.priorityOverrideReason??"")}}
 return <div>
  <div style={{display:"grid",gridTemplateColumns:"repeat(5,minmax(140px,1fr))",gap:8,overflowX:"auto"}}>{[1,2,3,4,5].map(p=><div key={p} style={{minWidth:140}}><small>FASE {p}</small>{items.filter((x:any)=>x.phase===p).map((x:any)=><div key={x.id} className="appointment-card" style={{marginTop:6}}><b>{x.label}</b><small style={{display:"block"}}>{x.tooth??""} · {x.status} · prioridad {x.priority??0}</small>{x.priorityOverrideReason&&<small style={{display:"block"}}>Motivo prioridad: {x.priorityOverrideReason}</small>}{deps.filter((d:any)=>d.itemId===x.id).map((d:any)=><span className="native-badge" key={d.id}>depende de {items.find((i:any)=>i.id===d.dependsOnId)?.label??"otro paso"} <button type="button" className="native-link-button" onClick={()=>void remove(d)}>Quitar</button></span>)}</div>)}</div>)}</div>
  <div className="native-toolbar" style={{marginTop:12}}><select className="native-select" value={itemId} onChange={e=>setItemId(e.target.value)}><option value="">Paso posterior…</option>{items.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select><span>depende de</span><select className="native-select" value={dependsOnId} onChange={e=>setDependsOnId(e.target.value)}><option value="">Paso previo…</option>{items.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select><label>Motivo<input className="native-input" value={dependencyReason} onChange={e=>setDependencyReason(e.target.value)}/></label><button className="native-button" onClick={add}>Añadir dependencia</button></div>
  <div className="native-card" style={{marginTop:12}}><h3>Cambiar prioridad clínica</h3><p>Un cambio manual de fase o prioridad exige dejar el motivo clínico.</p><div className="native-toolbar"><select className="native-select" value={overrideItemId} onChange={e=>selectOverride(e.target.value)}><option value="">Tratamiento…</option>{items.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select><label>Prioridad<input className="native-input" type="number" min="0" max="100" value={priority} onChange={e=>setPriority(e.target.value)} style={{width:90}}/></label><label>Fase<select className="native-select" value={phase} onChange={e=>setPhase(e.target.value)}>{[1,2,3,4,5].map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>Motivo<input className="native-input" value={priorityOverrideReason} onChange={e=>setPriorityOverrideReason(e.target.value)} placeholder="Motivo clínico obligatorio"/></label><button className="native-button" onClick={override}>Cambiar prioridad</button></div></div>
 </div>
}
