import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import https from "node:https";
import type { FiscalInvoiceSnapshot } from "./record-builder";
import { buildAeatSoapEnvelope } from "./xml-builder";

export interface VerifactuSubmissionResult{ok:boolean;status:number;providerReference?:string;responseCode?:string;raw:string;requestDigest:string}
function endpoint(){if(process.env.DENTY_AEAT_VERIFACTU_ENDPOINT)return process.env.DENTY_AEAT_VERIFACTU_ENDPOINT;return String(process.env.DENTY_AEAT_ENV??"test").toLowerCase()==="production"?"https://www1.agenciatributaria.gob.es/wlpl/TIKE-CONT/ws/SistemaFacturacion/VerifactuSOAP":"https://prewww1.aeat.es/wlpl/TIKE-CONT/ws/SistemaFacturacion/VerifactuSOAP"}
async function tlsOptions(){const pfxPath=process.env.DENTY_AEAT_PFX_PATH;if(pfxPath)return{pfx:await readFile(pfxPath),passphrase:process.env.DENTY_AEAT_PFX_PASSPHRASE};const certPath=process.env.DENTY_AEAT_CERT_PATH,keyPath=process.env.DENTY_AEAT_KEY_PATH;if(certPath&&keyPath)return{cert:await readFile(certPath),key:await readFile(keyPath),passphrase:process.env.DENTY_AEAT_KEY_PASSPHRASE};throw Object.assign(new Error("Configura DENTY_AEAT_PFX_PATH o DENTY_AEAT_CERT_PATH + DENTY_AEAT_KEY_PATH antes de remitir a AEAT"),{statusCode:503,code:"AEAT_CERTIFICATE_NOT_CONFIGURED"})}
function extract(xml:string,tag:string){const m=xml.match(new RegExp(`<[^>]*:?${tag}[^>]*>([^<]*)<\\/[^>]*:?${tag}>`,"i"));return m?.[1]?.trim()}
export async function submitVerifactuRecord(snapshot:FiscalInvoiceSnapshot,recordHash:string):Promise<VerifactuSubmissionResult>{const xml=buildAeatSoapEnvelope(snapshot,recordHash),url=new URL(endpoint()),tls=await tlsOptions(),requestDigest=createHash("sha256").update(xml).digest("hex");const raw=await new Promise<string>((resolve,reject)=>{const req=https.request({protocol:url.protocol,hostname:url.hostname,port:url.port||443,path:url.pathname+url.search,method:"POST",headers:{"content-type":"text/xml; charset=utf-8","content-length":Buffer.byteLength(xml),"soapaction":""},...tls,rejectUnauthorized:process.env.DENTY_AEAT_TLS_INSECURE!=="1"},res=>{const chunks:Buffer[]=[];res.on("data",c=>chunks.push(Buffer.from(c)));res.on("end",()=>{const body=Buffer.concat(chunks).toString("utf8");if((res.statusCode??500)>=400)return reject(Object.assign(new Error(`AEAT HTTP ${res.statusCode}: ${body.slice(0,500)}`),{statusCode:502,providerStatus:res.statusCode,providerBody:body}));resolve(body)})});req.on("error",reject);req.end(xml)});const estado=extract(raw,"EstadoEnvio")??extract(raw,"EstadoRegistro")??"UNKNOWN",providerReference=extract(raw,"IdPeticion");const responseCode=extract(raw,"CodigoErrorRegistro");return{ok:/correct|aceptad/i.test(estado),status:200,providerReference,responseCode:responseCode??estado,raw,requestDigest}}
