"use client";
import {useMemo,useState} from "react";
import {api} from "../../../lib/api";
import {useApiData,useRealtime} from "../../../lib/use-api-data";
function dateISO(d=new Date()){return d.toISOString().slice(0,10)}
function hhmm(d:string){return new Date(d).toLocaleTimeString("es-ES",{hour:"2-digit",minute:"2-digit"})}
function statusClass(a:any){if(a.status==="IN_CHAIR")return"state-green";if(a.status==="NO_SHOW")return"state-blue";if(a.status==="ARRIVED"&&a.arrivedAt)return Date.now()-new Date(a.arrivedAt).getTime()>15*60000?"state-red":"state-yellow";return""}
export default function Agenda(){
 const[date,setDate]=useState(dateISO()),{data:ctx}=useApiData<any>("/api/agenda/context",{staff:[],sites:[]}),{data,setData,refresh}=useApiData<any[]>(`/api/appointments?date=${date}`,[]),{data:requestData,refresh:refreshRequests}=useApiData<any>("/api/agenda/appointment-requests",{items:[]}),{data:gameStatusData,refresh:refreshGameStatus}=useApiData<any>(`/api/agenda/game-status?date=${date}`,{items:[]}),[selected,setSelected]=useState<any>(null),[view,setView]=useState<"doctors"|"day"|"list">("doctors"),[selectedRequest,setSelectedRequest]=useState<any>(null),[requestError,setRequestError]=useState("");
 useRealtime(()=>{void refresh();void refreshRequests();void refreshGameStatus()});
 const slots=useMemo(()=>Array.from({length:34},(_,i)=>{const m=8*60+i*20;return`${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`}),[]);
 async function action(a:any,name:string){const res=await api<any>(`/api/appointments/${a.id}/${name}`,{method:"POST",body:JSON.stringify({expectedVersion:a.version})});setSelected(res);await Promise.all([refresh(),refreshGameStatus()])}
 async function confirmWaitingRoom(id:string){await api(`/api/appointments/${id}/confirm-waiting-room`,{method:"POST",body:"{}"});await refreshGameStatus()}
 async function applyVoucher(id:string){await api(`/api/game-vouchers/${id}/apply`,{method:"POST",body:"{}"});await refreshGameStatus()}
 function gameStateFor(id:string){return (gameStatusData.items??[]).find((item:any)=>item.id===id)}
 async function move(a:any,staffId:string,time:string){const [h,m]=time.split(":").map(Number),start=new Date(`${date}T00:00:00`),duration=(new Date(a.endsAt).getTime()-new Date(a.startsAt).getTime())/60000;start.setHours(h,m,0,0);const end=new Date(start.getTime()+duration*60000);await api(`/api/appointments/${a.id}`,{method:"PATCH",body:JSON.stringify({expectedVersion:a.version,staffId,startsAt:start.toISOString(),endsAt:end.toISOString()})});await refresh()}
 async function resize(a:any,min:number){const start=new Date(a.startsAt),end=new Date(start.getTime()+min*60000);const res=await api<any>(`/api/appointments/${a.id}`,{method:"PATCH",body:JSON.stringify({expectedVersion:a.version,endsAt:end.toISOString()})});setSelected(res);await refresh()}
 async function scheduleRequest(form:FormData){if(!selectedRequest)return;setRequestError("");try{const day=String(form.get("date")),time=String(form.get("time")),duration=Number(form.get("duration")??30),staffId=String(form.get("staffId")??""),siteId=String(form.get("siteId")??"");const start=new Date(`${day}T${time}:00`),end=new Date(start.getTime()+duration*60000);await api(`/api/agenda/appointment-requests/${selectedRequest.id}/schedule`,{method:"POST",body:JSON.stringify({staffId,siteId,startsAt:start.toISOString(),endsAt:end.toISOString(),reason:selectedRequest.note||undefined})});setSelectedRequest(null);await Promise.all([refresh(),refreshRequests()])}catch(e:any){setRequestError(e?.payload?.error?.message??e?.message??"No se pudo crear la cita.")}}
 async function cancelRequest(id:string){await api(`/api/agenda/appointment-requests/${id}/cancel`,{method:"POST",body:"{}"});setSelectedRequest(null);await refreshRequests()}
 function card(a:any){return <div key={a.id} draggable onDragStart={e=>e.dataTransfer.setData("text/denty-appointment",a.id)} onClick={()=>setSelected(a)} className={`appointment-card ${statusClass(a)}`}><small>{hhmm(a.startsAt)}–{hhmm(a.endsAt)}</small><b style={{display:"block"}}>{a.title}</b><span className="native-badge">{a.status.replaceAll("_"," ")}</span>{a.status==="ARRIVED"&&a.arrivedAt&&<small style={{display:"block",marginTop:4}}>Espera {Math.max(0,Math.floor((Date.now()-new Date(a.arrivedAt).getTime())/60000))} min</small>}</div>}
 return <><header className="native-topbar"><div><h1>Agenda</h1><p>La misma cita cambia de estado sobre la agenda. No existe una sala de espera paralela.</p></div><button className="native-button primary">+ Cita</button></header>
 {(requestData.items??[]).length>0&&<section className="native-card" style={{marginBottom:14}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"baseline",gap:12}}><div><small>Solicitudes de cita</small><h2 style={{margin:"3px 0 0"}}>{requestData.items.length} pendiente{requestData.items.length===1?"":"s"}</h2></div><span className="native-badge">Administración / Secretaría</span></div><div className="native-grid" style={{marginTop:10}}>{requestData.items.map((r:any)=><button key={r.id} className="appointment-card" style={{textAlign:"left",cursor:"pointer"}} onClick={()=>setSelectedRequest(r)}><b>{r.patient.firstName} {r.patient.lastName}</b><small style={{display:"block",marginTop:3}}>{new Date(r.requestedAt).toLocaleString("es-ES")}</small>{r.note&&<p style={{marginBottom:0}}>{r.note}</p>}</button>)}</div></section>}
 <div className="native-toolbar"><button className="native-button" onClick={()=>{const d=new Date(date);d.setDate(d.getDate()-1);setDate(dateISO(d))}}>‹</button><input className="native-input" type="date" value={date} onChange={e=>setDate(e.target.value)}/><button className="native-button" onClick={()=>setDate(dateISO())}>Hoy</button><button className="native-button" onClick={()=>{const d=new Date(date);d.setDate(d.getDate()+1);setDate(dateISO(d))}}>›</button><span style={{flex:1}}/>{(["doctors","day","list"] as const).map(v=><button key={v} className={`native-button ${view===v?"soft":""}`} onClick={()=>setView(v)}>{v==="doctors"?"Doctores":v==="day"?"Día":"Lista"}</button>)}</div>
 {view==="list"?<div className="native-card native-grid">{[...data].sort((a,b)=>a.startsAt.localeCompare(b.startsAt)).map(card)}</div>:view==="doctors"?<div className="agenda-columns">{ctx.staff.map((s:any)=><section className="agenda-column" key={s.id}><h3>{s.displayName} · {data.filter(a=>a.staffId===s.id&&a.status==="ARRIVED").length} esperando</h3><div className="native-grid">{data.filter(a=>a.staffId===s.id).sort((a,b)=>a.startsAt.localeCompare(b.startsAt)).map(card)}</div></section>)}</div>:<div style={{overflowX:"auto"}}><div style={{display:"grid",gridTemplateColumns:`70px repeat(${Math.max(1,ctx.staff.length)},minmax(220px,1fr))`,minWidth:700,gap:1,background:"var(--denty-line)"}}><div className="native-card"/><>{ctx.staff.map((s:any)=><div className="native-card" key={s.id}><b>{s.displayName}</b></div>)}</>{slots.flatMap(time=>[<div key={`t-${time}`} style={{padding:8,background:"white",fontSize:11,color:"var(--denty-muted)"}}>{time}</div>,...ctx.staff.map((s:any)=><div key={`${s.id}-${time}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{const id=e.dataTransfer.getData("text/denty-appointment"),a=data.find(x=>x.id===id);if(a)void move(a,s.id,time)}} style={{minHeight:44,padding:3,background:"#fbfcfe"}}>{data.filter(a=>a.staffId===s.id&&hhmm(a.startsAt)===time).map(card)}</div>)])}</div></div>}
 {selected&&<aside className="native-card native-floating-panel" style={{position:"fixed",right:20,bottom:20,width:"min(420px,calc(100vw - 40px))",zIndex:50}}><div style={{display:"flex",justifyContent:"space-between"}}><div><b>{selected.title}</b><p>{hhmm(selected.startsAt)} · {selected.status}</p></div><button className="native-button" onClick={()=>setSelected(null)}>×</button></div><div className="native-toolbar">{["PLANNED","CONFIRMED"].includes(selected.status)&&<button className="native-button" onClick={()=>action(selected,"arrive")}>Ha llegado</button>}{selected.status==="ARRIVED"&&!gameStateFor(selected.id)?.visitSession&&["ADMIN","RECEPTION"].includes(ctx.actor?.role)&&<button className="native-button primary" onClick={()=>void confirmWaitingRoom(selected.id)}>Confirmar en sala</button>}<button className="native-button" onClick={()=>action(selected,"chair")}>A gabinete</button><button className="native-button" onClick={()=>action(selected,"no-show")}>Ausente/NPA</button><button className="native-button" onClick={()=>action(selected,"complete")}>Completar</button></div>{gameStateFor(selected.id)?.visitSession?.rewardStatus==="ACTIVE"&&!gameStateFor(selected.id)?.voucher&&<div className="appointment-card" style={{margin:"10px 0"}}><b>Juegos: {gameStateFor(selected.id).visitSession.rewardGamesCount}/15</b><small style={{display:"block",marginTop:3}}>El paciente puede generar un único bono durante esta cita.</small></div>}{gameStateFor(selected.id)?.voucher?.status==="AVAILABLE"&&<div className="appointment-card" style={{margin:"10px 0"}}><b>Bono disponible: {(gameStateFor(selected.id).voucher.amountCents/100).toFixed(0)} €</b>{["ADMIN","RECEPTION"].includes(ctx.actor?.role)&&<button className="native-button primary" style={{marginTop:8}} onClick={()=>void applyVoucher(gameStateFor(selected.id).voucher.id)}>Aplicar bono completo</button>}</div>}{gameStateFor(selected.id)?.voucher?.status==="APPLIED"&&<span className="native-badge" style={{marginBottom:10}}>Bono aplicado: {(gameStateFor(selected.id).voucher.amountCents/100).toFixed(0)} €</span>}<label>Duración <select className="native-select" value={Math.round((new Date(selected.endsAt).getTime()-new Date(selected.startsAt).getTime())/60000)} onChange={e=>resize(selected,Number(e.target.value))}>{[20,30,45,60,90,120].map(x=><option key={x}>{x}</option>)}</select> min</label></aside>}
 {selectedRequest&&<aside className="native-card native-floating-panel" style={{position:"fixed",right:20,bottom:20,width:"min(460px,calc(100vw - 40px))",zIndex:60}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><small>Solicitud de cita</small><h3 style={{margin:"3px 0"}}>{selectedRequest.patient.firstName} {selectedRequest.patient.lastName}</h3>{selectedRequest.note&&<p>{selectedRequest.note}</p>}</div><button className="native-button" onClick={()=>setSelectedRequest(null)}>×</button></div><form onSubmit={e=>{e.preventDefault();void scheduleRequest(new FormData(e.currentTarget))}} className="native-grid"><label>Fecha<input className="native-input" name="date" type="date" required defaultValue={dateISO()}/></label><label>Hora<input className="native-input" name="time" type="time" required defaultValue="10:00" step="1200"/></label><label>Duración<select className="native-select" name="duration" defaultValue="30">{[20,30,45,60,90].map(x=><option key={x} value={x}>{x} min</option>)}</select></label><label>Profesional<select className="native-select" name="staffId" required>{ctx.staff.map((s:any)=><option key={s.id} value={s.id}>{s.displayName}</option>)}</select></label><label>Sede<select className="native-select" name="siteId" required>{ctx.sites.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{requestError&&<p style={{color:"#b33"}}>{requestError}</p>}<div className="native-toolbar"><button className="native-button primary" type="submit">Dar cita</button><button className="native-button" type="button" onClick={()=>void cancelRequest(selectedRequest.id)}>Cerrar solicitud</button></div></form></aside>}</>}
