import type { FastifyInstance } from "fastify";
import { can, samePeriodPreviousYear } from "@denty/domain";
import { prisma, runBusinessTransaction, writeAnalyticsEvent, writeAudit, writeDomainEvent } from "@denty/db";
import { getActor } from "../../plugins/actor";
import { getCorrelationId } from "../../plugins/correlation";
import { createTreatmentCostRecipe, retireTreatmentCostRecipe } from "./cost-recipes";
import { computeAnalyticsStats, groupSpecialtyProfitability, groupTreatmentProfitability, specialtyForTreatmentCode, sumAttributedFinancialsByStaff } from "./metrics";

function range(q:any){const end=q.end?new Date(String(q.end)):new Date();const start=q.start?new Date(String(q.start)):new Date(Date.UTC(end.getUTCFullYear(),0,1));return{start,end}}
function filters(actor:any,q:any,override?:{start:Date;end:Date}){const {start,end}=override??range(q);return{clinicId:actor.clinicId,occurredAt:{gte:start,lte:end},staffId:q.staffId||undefined,siteId:q.siteId||undefined,specialty:q.specialty||undefined}}
function assertAnalysis(actor:any){if(!can(actor,"analysis.read"))throw Object.assign(new Error("Forbidden"),{statusCode:403})}
function sum(xs:any[],field:string){return xs.reduce((n,x)=>n+Number(x[field]??0),0)}
function stats(events:any[]){return computeAnalyticsStats(events)}
function groupLosses(xs:any[],key:(x:any)=>string){const m=new Map<string,any[]>();for(const x of xs){const k=key(x)||"Sin clasificar";(m.get(k)??m.set(k,[]).get(k)!).push(x)}return [...m].map(([name,events])=>{const lossCents=sum(events,"lossCents"),costCents=sum(events,"costCents");return{name,lossCents,costCents,impactCents:lossCents+costCents,quantity:events.reduce((n,e)=>n+Number(e.quantity??1),0)}})}

export async function registerAnalyticsRoutes(server:FastifyInstance){
  server.get<{Querystring:any}>("/api/analytics/summary",async request=>{const actor=await getActor(request);assertAnalysis(actor);const events=await prisma.analyticsEvent.findMany({where:filters(actor,request.query)});return stats(events)});
  server.get<{Querystring:any}>("/api/analytics/comparison",async request=>{const actor=await getActor(request);assertAnalysis(actor);const current=range(request.query),previous=samePeriodPreviousYear(current.start,current.end);const [nowEvents,priorEvents]=await Promise.all([prisma.analyticsEvent.findMany({where:filters(actor,request.query,current)}),prisma.analyticsEvent.findMany({where:filters(actor,request.query,previous)})]);const currentStats=stats(nowEvents),previousStats=stats(priorEvents);const delta=(a:number,b:number)=>({amountCents:a-b,percent:b===0?(a===0?0:null):Math.round(((a-b)/Math.abs(b))*1000)/10});return{period:{start:current.start,end:current.end},comparisonPeriod:previous,current:currentStats,previous:previousStats,delta:{produced:delta(currentStats.producedCents,previousStats.producedCents),invoiced:delta(currentStats.invoicedCents,previousStats.invoicedCents),collected:delta(currentStats.collectedCents,previousStats.collectedCents),margin:currentStats.marginIsComplete&&previousStats.marginIsComplete?delta(currentStats.marginCents,previousStats.marginCents):{amountCents:null,percent:null,incomplete:true,currentCoveragePercent:currentStats.marginCoveragePercent,previousCoveragePercent:previousStats.marginCoveragePercent},losses:delta(currentStats.inefficiencyCostCents,previousStats.inefficiencyCostCents)}}});
  server.get<{Querystring:any}>("/api/analytics/specialties",async request=>{const actor=await getActor(request);assertAnalysis(actor);const events=await prisma.analyticsEvent.findMany({where:filters(actor,request.query)});return{items:groupSpecialtyProfitability(events)}});
  server.get<{Querystring:any}>("/api/analytics/treatments",async request=>{const actor=await getActor(request);assertAnalysis(actor);const events=await prisma.analyticsEvent.findMany({where:filters(actor,request.query)});return{items:groupTreatmentProfitability(events)}});
  server.get<{Querystring:any}>("/api/analytics/profitability",async request=>{const actor=await getActor(request);assertAnalysis(actor);const events=await prisma.analyticsEvent.findMany({where:filters(actor,request.query)});const items=groupTreatmentProfitability(events).sort((a,b)=>b.marginCents-a.marginCents);return{items}});
  server.get<{Querystring:any}>("/api/analytics/doctors",async request=>{
    const actor=await getActor(request);assertAnalysis(actor);
    const q=(request.query??{}) as any,period=range(q),eventWhere=filters(actor,q);
    const [events,staff,allAppointments]=await Promise.all([
      prisma.analyticsEvent.findMany({where:eventWhere}),
      prisma.staffProfile.findMany({where:{clinicId:actor.clinicId,role:"DENTIST",id:q.staffId||undefined},orderBy:{displayName:"asc"}}),
      prisma.appointment.findMany({where:{clinicId:actor.clinicId,startsAt:{gte:period.start,lte:period.end},status:{not:"CANCELLED"},siteId:q.siteId||undefined,staffId:q.staffId||undefined},include:{clinicalPlanItem:{select:{treatmentCode:true}}}})
    ]);
    const financialByStaff=sumAttributedFinancialsByStaff(events);
    const appointments=q.specialty?allAppointments.filter(a=>specialtyForTreatmentCode(a.clinicalPlanItem?.treatmentCode)===q.specialty):allAppointments;
    const items=staff.map(doc=>{
      const doctorEvents=events.filter(e=>e.staffId===doc.id),base=stats(doctorEvents),doctorAppointments=appointments.filter(a=>a.staffId===doc.id),completed=doctorAppointments.filter(a=>a.status==="COMPLETED"),noShowCount=doctorAppointments.filter(a=>a.status==="NO_SHOW").length;
      const chairMinutes=Math.round(completed.reduce((n,a)=>{const start=a.chairAt??a.startsAt,end=a.completedAt??a.endsAt;return n+Math.max(0,(end.getTime()-start.getTime())/60000)},0)),hours=chairMinutes/60,margin=base.marginCents,reworkCount=doctorEvents.filter(e=>e.type==="treatment.rework").length,financial=financialByStaff[doc.id]??{billedCents:0,collectedCents:0};
      return{id:doc.id,name:doc.displayName,...base,billedCents:financial.billedCents,collectedCents:financial.collectedCents,chairMinutes,producedPerHourCents:hours>0?Math.round(base.producedCents/hours):0,marginPerHourCents:hours>0?Math.round(margin/hours):0,noShowCount,noShowRatePercent:doctorAppointments.length?Math.round((noShowCount/doctorAppointments.length)*1000)/10:0,reworkCount,appointmentCount:doctorAppointments.length,completedAppointmentCount:completed.length};
    }).sort((a,b)=>b.producedCents-a.producedCents);
    return{items};
  });
  server.get<{Querystring:any}>("/api/analytics/losses",async request=>{const actor=await getActor(request);assertAnalysis(actor);const events=await prisma.analyticsEvent.findMany({where:{...filters(actor,request.query),OR:[{lossCents:{gt:0}},{type:{in:["appointment.no_show","treatment.rework","discount.applied","refund.recorded","writeoff.recorded"]}}]}});const items=groupLosses(events,e=>e.type).sort((a,b)=>b.impactCents-a.impactCents);return{totalLossCents:sum(events,"lossCents"),totalCostCents:sum(events,"costCents"),totalImpactCents:items.reduce((n,x)=>n+x.impactCents,0),items}});
  server.get<{Querystring:any}>("/api/analytics/monthly",async request=>{const actor=await getActor(request);assertAnalysis(actor);const events=await prisma.analyticsEvent.findMany({where:filters(actor,request.query),orderBy:{occurredAt:"asc"}}),by=new Map<string,any[]>();for(const e of events){const k=e.occurredAt.toISOString().slice(0,7);(by.get(k)??by.set(k,[]).get(k)!).push(e)}return{items:[...by].map(([month,x])=>({month,...stats(x)}))}});
  server.get<{Querystring:any}>("/api/analytics/events",async request=>{const actor=await getActor(request);assertAnalysis(actor);const q=(request.query??{}) as any,limit=Math.min(200,Math.max(1,Number(q.limit??50))),where:any={...filters(actor,q),type:q.type||undefined,category:q.category||undefined};const items=await prisma.analyticsEvent.findMany({where,include:{patient:{select:{id:true,firstName:true,lastName:true}},staff:{select:{id:true,displayName:true}},site:{select:{id:true,name:true}},clinicalPlanItem:{select:{id:true,label:true,tooth:true,treatmentCode:true}},labWork:{select:{id:true,title:true}}},orderBy:[{occurredAt:"desc"},{id:"desc"}],take:limit});return{items,limit};});
  server.get<{Querystring:any}>("/api/analytics/treatments/drilldown",async request=>{const actor=await getActor(request);assertAnalysis(actor);const q=(request.query??{}) as any,category=String(q.category??"").trim();if(!category)throw Object.assign(new Error("category is required"),{statusCode:400});const all=await prisma.analyticsEvent.findMany({where:filters(actor,q),include:{patient:{select:{id:true,firstName:true,lastName:true}},staff:{select:{id:true,displayName:true}},site:{select:{id:true,name:true}},clinicalPlanItem:{select:{id:true,label:true,tooth:true,treatmentCode:true}},labWork:{select:{id:true,title:true}}},orderBy:{occurredAt:"desc"}});const completions=all.filter(e=>e.type==="treatment.completed"&&(e.category===category||e.specialty===category)),planIds=new Set(completions.map(e=>e.clinicalPlanItemId).filter(Boolean)),items=all.filter(e=>completions.some(c=>c.id===e.id)||(e.clinicalPlanItemId&&planIds.has(e.clinicalPlanItemId)));return{category,summary:groupTreatmentProfitability(items).find(x=>x.name===category)??null,items};});

  server.get<{Querystring:any}>("/api/analytics/purchases",async request=>{const actor=await getActor(request);assertAnalysis(actor);const q=(request.query??{}) as any,{start,end}=range(q);const invoices=await prisma.supplierInvoice.findMany({where:{clinicId:actor.clinicId,issuedAt:{gte:start,lte:end},siteId:q.siteId||undefined},include:{supplier:true,items:true},orderBy:{issuedAt:"desc"}});const totalCents=invoices.reduce((n,x)=>n+x.totalCents,0),bySupplier=new Map<string,number>(),byCategory=new Map<string,number>();for(const inv of invoices){bySupplier.set(inv.supplier.name,(bySupplier.get(inv.supplier.name)??0)+inv.totalCents);for(const item of inv.items)byCategory.set(item.category,(byCategory.get(item.category)??0)+item.totalCents)}return{totalCents,bySupplier:[...bySupplier].map(([name,costCents])=>({name,costCents})).sort((a,b)=>b.costCents-a.costCents),byCategory:[...byCategory].map(([name,costCents])=>({name,costCents})).sort((a,b)=>b.costCents-a.costCents),invoices}});
  server.get("/api/suppliers",async request=>{const actor=await getActor(request);if(!can(actor,"finance.read")&&!can(actor,"analysis.read"))throw Object.assign(new Error("Forbidden"),{statusCode:403});return{items:await prisma.supplier.findMany({where:{clinicId:actor.clinicId,active:true},orderBy:{name:"asc"}})}});
  server.post("/api/supplier-invoices",async(request,reply)=>{const actor=await getActor(request);if(!can(actor,"finance.write"))throw Object.assign(new Error("Forbidden"),{statusCode:403});const b=request.body as any;return reply.code(201).send(await runBusinessTransaction(prisma,async tx=>{let supplier=b.supplierId?await tx.supplier.findFirst({where:{id:b.supplierId,clinicId:actor.clinicId}}):null;if(!supplier)supplier=await tx.supplier.create({data:{clinicId:actor.clinicId,name:String(b.supplierName),taxId:b.supplierTaxId,category:b.supplierCategory}});const items=Array.isArray(b.items)?b.items:[];const totalCents=Number(b.totalCents??items.reduce((n:number,x:any)=>n+Number(x.totalCents??Number(x.quantity??1)*Number(x.unitCostCents??0)),0));const inv=await tx.supplierInvoice.create({data:{clinicId:actor.clinicId,supplierId:supplier.id,siteId:b.siteId,invoiceNumber:String(b.invoiceNumber),issuedAt:new Date(b.issuedAt),totalCents,documentPath:b.documentPath,items:{create:items.map((i:any)=>({category:String(i.category??"materials"),productCode:i.productCode,description:String(i.description),quantity:Number(i.quantity??1),unitCostCents:Number(i.unitCostCents),totalCents:Number(i.totalCents??Number(i.quantity??1)*Number(i.unitCostCents??0))}))}}});await writeAnalyticsEvent(tx,{clinicId:actor.clinicId,type:"purchase.recorded",siteId:b.siteId,costCents:inv.totalCents,metadata:{supplierId:supplier.id,supplier:supplier.name,invoiceNumber:inv.invoiceNumber},correlationId:getCorrelationId(request)});await writeAudit(tx,{clinicId:actor.clinicId,actorUserId:actor.userId,action:"purchase.recorded",entityType:"supplier_invoice",entityId:inv.id,correlationId:getCorrelationId(request),after:{totalCents:inv.totalCents,supplier:supplier.name}});await writeDomainEvent(tx,{clinicId:actor.clinicId,actorUserId:actor.userId,type:"purchase.recorded",entityType:"supplier_invoice",entityId:inv.id,correlationId:getCorrelationId(request),payload:{totalCents:inv.totalCents,supplierId:supplier.id}});return inv;}))});

  server.get("/api/analytics/cost-recipes",async request=>{const actor=await getActor(request);assertAnalysis(actor);return{items:await prisma.treatmentCostRecipe.findMany({where:{clinicId:actor.clinicId},include:{items:true},orderBy:[{treatmentCode:"asc"},{activeFrom:"desc"}]})}});
  server.post("/api/analytics/cost-recipes",async(request,reply)=>{const actor=await getActor(request);if(!can(actor,"settings.manage"))throw Object.assign(new Error("Forbidden"),{statusCode:403});return reply.code(201).send(await createTreatmentCostRecipe(actor,request.body as any,getCorrelationId(request)))});
  server.post<{Params:{id:string}}>("/api/analytics/cost-recipes/:id/retire",async request=>{const actor=await getActor(request);if(!can(actor,"settings.manage"))throw Object.assign(new Error("Forbidden"),{statusCode:403});const body=request.body as any;return retireTreatmentCostRecipe(actor,request.params.id,body?.activeUntil?new Date(body.activeUntil):new Date(),getCorrelationId(request))});
}
