"use client";
import {FormEvent,useState} from "react";
import {api} from "../../../lib/api";
import {useApiData} from "../../../lib/use-api-data";

export default function Settings(){
 const{data:users,refresh}=useApiData<any>("/api/users",{items:[]});
 const{data:backups,refresh:refreshBackups}=useApiData<any>("/api/security/backups",{items:[]});
 const{data:sessions,refresh:refreshSessions}=useApiData<any>("/api/security/sessions",{items:[]});
 const{data:privacy,refresh:refreshPrivacy}=useApiData<any>("/api/security/privacy-requests",{items:[]});
 const[show,setShow]=useState(false),[error,setError]=useState(""),[privacyPatient,setPrivacyPatient]=useState(""),[privacyType,setPrivacyType]=useState("EXPORT"),[privacyNote,setPrivacyNote]=useState("");
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setError("");try{await api("/api/users",{method:"POST",body:JSON.stringify({displayName:f.get("displayName"),email:f.get("email")||undefined,username:f.get("username")||undefined,role:f.get("role"),password:f.get("password")})});setShow(false);await refresh()}catch(e:any){setError(e?.payload?.error?.message??e?.message??"No se pudo crear el usuario")}}
 async function backup(){setError("");try{await api("/api/security/backups",{method:"POST",body:"{}"});await refreshBackups()}catch(e:any){setError(e?.payload?.error?.message??e?.message??"No se pudo crear la copia")}}
 async function verify(id:string){setError("");try{await api(`/api/security/backups/${id}/verify`,{method:"POST",body:"{}"});await refreshBackups()}catch(e:any){setError(e?.payload?.error?.message??e?.message??"No se pudo verificar la copia")}}
 async function revoke(id:string){if(!window.confirm("Cerrar esta sesión en ese dispositivo?"))return;await api(`/api/security/sessions/${id}`,{method:"DELETE"});await refreshSessions()}
 async function createPrivacyRequest(){if(!privacyPatient.trim())return;setError("");try{await api("/api/security/privacy-requests",{method:"POST",body:JSON.stringify({patientId:privacyPatient.trim(),type:privacyType,note:privacyNote||undefined})});setPrivacyNote("");await refreshPrivacy()}catch(e:any){setError(e?.payload?.error?.message??e?.message??"No se pudo registrar la solicitud")}}
 async function updatePrivacy(id:string,status:"IN_REVIEW"|"COMPLETED"|"REJECTED"){const resolutionNote=status==="COMPLETED"?window.prompt("Nota de resolución (opcional)")??undefined:undefined;setError("");try{await api(`/api/security/privacy-requests/${id}`,{method:"PATCH",body:JSON.stringify({status,resolutionNote})});await refreshPrivacy()}catch(e:any){setError(e?.payload?.error?.message??e?.message??"No se pudo actualizar la solicitud")}}
 async function exportPatient(patientId:string){setError("");try{const payload=await api<any>(`/api/security/patient-export/${patientId}`);const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),href=URL.createObjectURL(blob),a=document.createElement("a");a.href=href;a.download=`denty-paciente-${patientId}-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(href)}catch(e:any){setError(e?.payload?.error?.message??e?.message??"No se pudo exportar el paciente")}}
 return <><header className="native-topbar"><div><h1>Ajustes</h1><p>Usuarios, roles, sesiones, privacidad y copias cifradas.</p></div><button className="native-button primary" onClick={()=>setShow(!show)}>+ Usuario</button></header>{error&&<div className="native-error">{error}</div>}
 {show&&<form className="native-card native-toolbar" onSubmit={create}><input className="native-input" name="displayName" placeholder="Nombre visible" required/><input className="native-input" name="email" placeholder="Email"/><input className="native-input" name="username" placeholder="Usuario"/><select className="native-select" name="role"><option>RECEPTION</option><option>DENTIST</option><option>ASSISTANT</option><option>ADMIN</option><option>PATIENT</option></select><input className="native-input" type="password" name="password" placeholder="Contraseña ≥10" required/><button className="native-button primary">Crear</button></form>}
 <section className="native-grid two">
  <div className="native-card"><h2>Usuarios</h2><table className="native-table"><thead><tr><th>Nombre</th><th>Rol</th><th>Estado</th></tr></thead><tbody>{users.items.map((u:any)=><tr key={u.id}><td>{u.displayName}<br/><small>{u.email??u.username}</small></td><td>{u.role}</td><td>{u.active?"Activo":"Desactivado"}</td></tr>)}</tbody></table></div>
  <div className="native-card"><h2>Sesiones activas</h2>{sessions.items.map((s:any)=><div key={s.id} className="appointment-card" style={{marginBottom:8}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><div><b>{s.deviceLabel||"Dispositivo"}</b><small style={{display:"block"}}>Última actividad {new Date(s.lastSeenAt).toLocaleString("es-ES")} · caduca {new Date(s.expiresAt).toLocaleDateString("es-ES")}</small></div><button className="native-button" onClick={()=>void revoke(s.id)}>Cerrar sesión</button></div></div>)}{!sessions.items.length&&<div className="native-empty">No hay otras sesiones activas.</div>}</div>
  <div className="native-card"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h2>Copias cifradas</h2><button className="native-button" onClick={backup}>Crear copia</button></div>{backups.items.map((b:any)=><div key={b.id} className="appointment-card" style={{marginBottom:8}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><div><b>{new Date(b.createdAt).toLocaleString("es-ES")}</b><small style={{display:"block"}}>{Math.round(b.sizeBytes/1024)} KB · {b.verifiedAt?`verificada ${new Date(b.verifiedAt).toLocaleString("es-ES")}`:"sin verificar"}</small></div><button className="native-button" onClick={()=>void verify(b.id)}>Verificar</button></div></div>)}<p><small>Los backups automáticos usan la misma copia cifrada y se verifican inmediatamente. La restauración se hace mediante el CLI de restore antes de reemplazar la base activa.</small></p></div>
  <div className="native-card"><h2>Privacidad y derechos del paciente</h2><p><small>Registra la solicitud y su resolución. Una solicitud de supresión no borra silenciosamente historia clínica/fiscal: archiva el paciente y revoca accesos mientras queda trazabilidad.</small></p><div className="native-toolbar"><input className="native-input" value={privacyPatient} onChange={e=>setPrivacyPatient(e.target.value)} placeholder="patientId"/><select className="native-select" value={privacyType} onChange={e=>setPrivacyType(e.target.value)}><option>ACCESS</option><option>EXPORT</option><option>RECTIFICATION</option><option>RESTRICTION</option><option>ERASURE</option></select><input className="native-input" value={privacyNote} onChange={e=>setPrivacyNote(e.target.value)} placeholder="Nota de solicitud"/><button className="native-button primary" onClick={()=>void createPrivacyRequest()}>Registrar</button></div>{privacy.items.map((r:any)=><div key={r.id} className="appointment-card" style={{marginBottom:8}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"flex-start"}}><div><b>{r.patient?.firstName} {r.patient?.lastName}</b><small style={{display:"block"}}>{r.type} · {r.status} · {new Date(r.requestedAt).toLocaleDateString("es-ES")}</small>{r.requestNote&&<small style={{display:"block"}}>{r.requestNote}</small>}</div><div className="native-toolbar">{r.type==="EXPORT"&&<button className="native-button" onClick={()=>void exportPatient(r.patientId)}>Exportar</button>}{r.status==="OPEN"&&<button className="native-button" onClick={()=>void updatePrivacy(r.id,"IN_REVIEW")}>En revisión</button>}{!["COMPLETED","REJECTED"].includes(r.status)&&<button className="native-button primary" onClick={()=>void updatePrivacy(r.id,"COMPLETED")}>Completar</button>}</div></div></div>)}{!privacy.items.length&&<div className="native-empty">Sin solicitudes de privacidad abiertas o históricas.</div>}</div>
 </section></>}
