packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': false
  '@prisma/engines': true
  esbuild: true
  prisma: true
onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - prisma
