import type { FastifyInstance } from "fastify";
import { can, slotIsAvailable } from "@denty/domain";
import { prisma, runBusinessTransaction, writeAudit, writeDomainEvent } from "@denty/db";
import { getActor } from "../../plugins/actor";
import { getCorrelationId } from "../../plugins/correlation";

function assertAgenda(actor:any){if(!can(actor,"agenda.write"))throw Object.assign(new Error("Forbidden"),{statusCode:403})}
export async function registerAgendaOperationsRoutes(server:FastifyInstance){
 server.get("/api/agenda/context",async request=>{const actor=await getActor(request);const staff=await prisma.staffProfile.findMany({where:{clinicId:actor.clinicId,active:true,...(can(actor,"agenda.read.all")?{}:{id:actor.staffId??"__none__"})},orderBy:{displayName:"asc"}}),sites=await prisma.site.findMany({where:{clinicId:actor.clinicId,active:true},include:{cabinets:{where:{active:true}}},orderBy:{name:"asc"}});return{staff,sites,actor:{role:actor.role,staffId:actor.staffId}}});
 server.get<{Querystring:any}>("/api/agenda/availability",async request=>{const actor=await getActor(request);const q=request.query as any,date=String(q.date??new Date().toISOString().slice(0,10)),staffId=String(q.staffId??actor.staffId??""),duration=Number(q.durationMin??30);if(!staffId)return{slots:[]};const day=new Date(`${date}T00:00:00`),start=new Date(day);start.setHours(Number(q.startHour??8),0,0,0);const end=new Date(day);end.setHours(Number(q.endHour??20),0,0,0);const [appointments,blocks,absence]=await Promise.all([prisma.appointment.findMany({where:{clinicId:actor.clinicId,staffId,startsAt:{gte:start,lt:end},status:{not:"CANCELLED"}}}),prisma.appointmentBlock.findMany({where:{clinicId:actor.clinicId,startsAt:{lt:end},endsAt:{gt:start},OR:[{staffId},{staffId:null}]}}),prisma.absence.findMany({where:{clinicId:actor.clinicId,staffId,startsAt:{lt:end},endsAt:{gt:start}}})]);const busy=appointments.map(a=>({startsAt:a.startsAt,endsAt:a.endsAt})),blocked=[...blocks,...absence].map(b=>({startsAt:b.startsAt,endsAt:b.endsAt}));const slots=[];for(let t=start.getTime();t+duration*60000<=end.getTime();t+=20*60000){const slot={startsAt:new Date(t),endsAt:new Date(t+duration*60000)};if(slotIsAvailable(slot,busy,blocked))slots.push(slot)}return{date,staffId,durationMin:duration,slots};});
 server.post("/api/agenda/blocks",async(request,reply)=>{const actor=await getActor(request);assertAgenda(actor);const b=request.body as any;return reply.code(201).send(await prisma.appointmentBlock.create({data:{clinicId:actor.clinicId,staffId:b.staffId,siteId:b.siteId,cabinetId:b.cabinetId,startsAt:new Date(b.startsAt),endsAt:new Date(b.endsAt),kind:String(b.kind??"BLOCK"),reason:b.reason}}))});
 server.post("/api/agenda/waitlist",async(request,reply)=>{const actor=await getActor(request);assertAgenda(actor);const b=request.body as any;return reply.code(201).send(await prisma.waitlistEntry.create({data:{clinicId:actor.clinicId,patientId:b.patientId,preferredStaffId:b.preferredStaffId,siteId:b.siteId,earliestAt:b.earliestAt?new Date(b.earliestAt):undefined,latestAt:b.latestAt?new Date(b.latestAt):undefined,durationMin:Number(b.durationMin??30),reason:b.reason,priority:Number(b.priority??0)}}))});
 server.get("/api/agenda/waitlist",async request=>{const actor=await getActor(request);return{items:await prisma.waitlistEntry.findMany({where:{clinicId:actor.clinicId,active:true},include:{patient:true,preferredStaff:true},orderBy:[{priority:"desc"},{createdAt:"asc"}]})}});
 server.post<{Params:{id:string}}>("/api/appointments/:id/cancel-cascade",async request=>{const actor=await getActor(request);assertAgenda(actor);const b=request.body as any;return runBusinessTransaction(prisma,async tx=>{const ap=await tx.appointment.findFirstOrThrow({where:{id:request.params.id,clinicId:actor.clinicId}});const cancelled=await tx.appointment.update({where:{id:ap.id},data:{status:"CANCELLED",cancelledAt:new Date(),cancellationReason:b.reason,version:{increment:1}}});const affected=ap.clinicalPlanItemId?await tx.appointment.findMany({where:{clinicalPlanItemId:ap.clinicalPlanItemId,startsAt:{gt:ap.startsAt},status:{in:["PLANNED","CONFIRMED"]}},orderBy:{startsAt:"asc"}}):[];await writeAudit(tx,{clinicId:actor.clinicId,actorUserId:actor.userId,action:"appointment.cancelled",entityType:"appointment",entityId:ap.id,correlationId:getCorrelationId(request),before:{status:ap.status},after:{status:"CANCELLED",reason:b.reason}});await writeDomainEvent(tx,{clinicId:actor.clinicId,actorUserId:actor.userId,type:"appointment.cancelled",entityType:"appointment",entityId:ap.id,correlationId:getCorrelationId(request),payload:{patientId:ap.patientId,affectedAppointmentIds:affected.map(x=>x.id)}});return{cancelled,proposal:{affected:affected.map(x=>({id:x.id,startsAt:x.startsAt,title:x.title})),autoApplied:false,message:affected.length?"Hay citas posteriores relacionadas. Revisa la cascada antes de moverlas.":"No hay citas posteriores relacionadas."}};})});
 server.post<{Params:{planItemId:string}}>("/api/agenda/schedule-plan-item",async request=>{const actor=await getActor(request);assertAgenda(actor);const b=request.body as any,item=await prisma.clinicalPlanItem.findFirstOrThrow({where:{id:request.params.planItemId,plan:{clinicId:actor.clinicId}},include:{plan:true}}),count=Math.max(1,Math.trunc(Number(b.visits??1))),duration=Math.max(10,Math.trunc(Number(b.durationMin??item.durationMin??45))),staffId=String(b.staffId??actor.staffId??item.clinicianId??""),siteId=String(b.siteId??"");if(!staffId||!siteId)throw Object.assign(new Error("Falta doctor o sede"),{statusCode:400});await prisma.staffProfile.findFirstOrThrow({where:{id:staffId,clinicId:actor.clinicId,active:true}});await prisma.site.findFirstOrThrow({where:{id:siteId,clinicId:actor.clinicId,active:true}});if(actor.staffId&&actor.permissions.includes("agenda.read.own")&&!actor.permissions.includes("agenda.read.all")&&staffId!==actor.staffId)throw Object.assign(new Error("Forbidden"),{statusCode:403});const rawInterval=b.gapDays!==undefined&&b.gapDays!==null?Number(b.gapDays):item.biologicalWaitDays;const intervalDays=rawInterval===undefined||rawInterval===null?null:Math.max(0,Math.trunc(Number(rawInterval)));if(count>1&&intervalDays===null)throw Object.assign(new Error("Indica el intervalo entre visitas; Denty no inventa tiempos clínicos."),{statusCode:400,code:"MULTI_VISIT_INTERVAL_REQUIRED"});let cursor=new Date(b.startDate??new Date());if(Number.isNaN(cursor.getTime()))throw Object.assign(new Error("Fecha inicial no válida"),{statusCode:400});const created=[];let searchedDays=0;for(let i=0;i<count;i++){let slot:any=null;while(!slot&&searchedDays<366){const day=cursor.toISOString().slice(0,10);const startDay=new Date(`${day}T09:00:00`),endDay=new Date(`${day}T19:00:00`),busy=await prisma.appointment.findMany({where:{clinicId:actor.clinicId,staffId,startsAt:{gte:startDay,lt:endDay},status:{not:"CANCELLED"}}});for(let t=Math.max(startDay.getTime(),cursor.getTime());t+duration*60000<=endDay.getTime();t+=20*60000){const candidate={startsAt:new Date(t),endsAt:new Date(t+duration*60000)};if(slotIsAvailable(candidate,busy,[])){slot=candidate;break}}if(!slot){cursor=new Date(startDay);cursor.setUTCDate(cursor.getUTCDate()+1);searchedDays++;}}if(!slot)throw Object.assign(new Error("No se encontró hueco en los próximos 366 días"),{statusCode:409,code:"NO_AVAILABLE_SLOT"});const createdAppointment=await prisma.appointment.create({data:{clinicId:actor.clinicId,patientId:item.plan.patientId,staffId,siteId,clinicalPlanItemId:item.id,startsAt:slot.startsAt,endsAt:slot.endsAt,title:item.label}});created.push(createdAppointment);cursor=new Date(slot.endsAt);if(i<count-1&&intervalDays!==null&&intervalDays>0){cursor=new Date(slot.startsAt);cursor.setUTCDate(cursor.getUTCDate()+intervalDays)}}return{items:created,intervalDays};});
}
