import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const exists=(p)=>fs.existsSync(path.join(root,p));
const checks=[];
function check(name,ok){checks.push([name,!!ok]); if(!ok) console.error('FAIL',name)}
check('AEAT provider exists',exists('apps/api/src/modules/billing/verifactu/provider.ts'));
check('AEAT XML builder exists',exists('apps/api/src/modules/billing/verifactu/xml-builder.ts'));
check('fiscal submit route',/verifactu\/submit/.test(read('apps/api/src/modules/billing/routes.ts')));
check('cost recipe service exists',exists('apps/api/src/modules/analytics/cost-recipes.ts'));
check('cost recipe routes',/cost-recipes/.test(read('apps/api/src/modules/analytics/routes.ts')));
check('treatment completion snapshots recipe cost',/resolveStandardTreatmentCost/.test(read('apps/api/src/modules/clinical/service.ts')));
check('advanced alternatives',/toothPrognosisAlternatives/.test(read('packages/domain/src/treatment-plan/index.ts')) && /kennedy/.test(read('packages/domain/src/treatment-plan/index.ts')));
check('voice executes payments',/case\s*"payment\.record"/.test(read('apps/api/src/modules/voice/service.ts')) && /recordPaymentTx/.test(read('apps/api/src/modules/voice/service.ts')));
check('voice executes lab transitions',/case\s*"lab\.transition"/.test(read('apps/api/src/modules/voice/service.ts')) && /transitionLabWorkTx/.test(read('apps/api/src/modules/voice/service.ts')));
check('document template versioning',/createTemplateVersion/.test(read('apps/api/src/modules/documents/service.ts')));
check('document delivery/archive',/deliverDocument/.test(read('apps/api/src/modules/documents/service.ts')) && /archiveDocument/.test(read('apps/api/src/modules/documents/service.ts')));
check('lab attachment service',exists('apps/api/src/modules/laboratory/attachments.ts'));
check('patient family grants',/family-grants/.test(read('apps/api/src/modules/portal/routes.ts')));
check('analysis YTD helper usage',/samePeriodPreviousYear/.test(read('apps/api/src/modules/analytics/routes.ts')));
check('legacy importer covers clinical data',/odontogram/.test(read('packages/db/src/import/legacy.ts')) && /clinicalPlan/.test(read('packages/db/src/import/legacy.ts')) && /budget/.test(read('packages/db/src/import/legacy.ts')));
const failed=checks.filter(([,ok])=>!ok);
console.log(`${checks.length-failed.length}/${checks.length} production-completion checks pass`);
if(failed.length) process.exit(1);
