import fs from 'node:fs';
import assert from 'node:assert/strict';
const app=fs.readFileSync('apps/legacy-preview/app.js','utf8');
const css=fs.readFileSync('apps/legacy-preview/styles/styles.css','utf8');
assert.match(app,/function renderPatientTreatmentDisclosure\(/,'debe existir un componente desplegable específico para tratamiento');
assert.match(app,/patient-treatment-disclosure/,'tratamiento debe renderizarse con bloques desplegables');
assert.match(app,/summary>[^<]*Ruta hasta terminar|Ruta hasta terminar[\s\S]{0,300}renderPatientTreatmentDisclosure/,'la ruta debe formar parte de la experiencia desplegable');
assert.match(app,/Opciones de tratamiento/,'las alternativas deben quedar en un bloque desplegable identificable');
assert.match(css,/\.patient-treatment-disclosure/,'debe existir CSS específico para los desplegables de tratamiento');
assert.match(css,/\.patient-treatment-disclosure\[open\]/,'el estado abierto debe estar estilizado');
console.log('verify_patient_treatment_accordion: OK');
