import fs from 'node:fs';
const svc=fs.readFileSync('apps/api/src/modules/portal/service.ts','utf8');
const routes=fs.readFileSync('apps/api/src/modules/portal/routes.ts','utf8');
const schema=fs.readFileSync('packages/db/prisma/schema.prisma','utf8');
let p=0,f=0;const ok=(v,m)=>{if(v){console.log('PASS',m);p++}else{console.error('FAIL',m);f++}};
ok(/createPatientInvitation[\s\S]*patient\.findFirstOrThrow[\s\S]*clinicId:actor\.clinicId/.test(svc),'patient invitation verifies tenant ownership before issuing token');
ok(svc.includes('assertPositivePaymentAmount'),'portal rejects zero, negative or non-integer payment intents');
ok(svc.includes('validatePaymentTarget'),'payment intent validates invoice/budget belongs to same clinic and patient');
ok(svc.includes('remainingCents')&&svc.includes('PAYMENT_EXCEEDS_BALANCE'),'payment intent cannot exceed target outstanding balance');
ok(svc.includes('provider:providerName')&&svc.includes('providerRef'),'provider settlement resolves provider and reference together');
ok(svc.includes('INVOICE_OVER_ALLOCATION')&&svc.includes('allocations.reduce'),'provider webhook cannot over-allocate an invoice');
ok(schema.includes('@@unique([provider, providerRef])'),'database constrains provider payment reference uniqueness');
ok(routes.includes('provider:String(b.provider??process.env.DENTY_PAYMENT_PROVIDER'),'webhook binds callback to configured/provider identity');
console.log(`\n${p} passed, ${f} failed`);if(f)process.exit(1);
