import fs from 'fs';
let p=0,f=0;const ok=(v,m)=>{(v?p++:f++);console[v?'log':'error'](v?'PASS':'FAIL',m)};
const page=fs.readFileSync('apps/web/src/app/app/analysis/page.tsx','utf8');
const routes=fs.readFileSync('apps/api/src/modules/analytics/routes.ts','utf8');
ok(page.includes('/api/analytics/comparison'),'analysis uses same-period comparison endpoint');
ok(page.includes('/api/supplier-invoices'),'admin can register supplier invoices from Analysis');
ok(page.includes('/api/analytics/cost-recipes'),'admin can manage treatment cost recipes from Analysis');
ok(routes.includes('chairMinutes'),'doctor metrics expose chair time');
ok(routes.includes('producedPerHourCents'),'doctor metrics expose production per hour');
ok(routes.includes('marginPerHourCents'),'doctor metrics expose margin per hour');
ok(routes.includes('billedCents')&&routes.includes('collectedCents'),'doctor metrics distinguish billing and collection');
ok(routes.includes('noShowRatePercent')&&routes.includes('reworkCount'),'doctor metrics expose NPA and rework quality signals');
console.log(`\n${p} passed, ${f} failed`);if(f)process.exit(1);
