import fs from 'fs';let p=0,f=0;const ok=(v,m)=>{(v?p++:f++);console[v?'log':'error'](v?'PASS':'FAIL',m)};
const providers=fs.existsSync('apps/api/src/modules/voice/providers.ts')?fs.readFileSync('apps/api/src/modules/voice/providers.ts','utf8'):'';
const routes=fs.readFileSync('apps/api/src/modules/voice/routes.ts','utf8'),svc=fs.readFileSync('apps/api/src/modules/voice/service.ts','utf8'),ui=fs.readFileSync('apps/web/src/features/voice/VoiceCommandBar.tsx','utf8');
ok(providers.includes('DENTY_ASR_ENDPOINT')&&providers.includes('transcribeAudio'),'voice supports local/Vosk-compatible ASR adapter endpoint');
ok(providers.includes('DENTY_LLM_VOICE_ENDPOINT')&&providers.includes('planVoiceHybrid'),'LLM is optional planner fallback');
ok(providers.includes('allowedActionTypes'),'LLM plans are allow-listed before execution');
ok(routes.includes('/api/voice/transcribe')&&routes.includes('/api/voice/capabilities'),'voice API exposes ASR and capability negotiation');
ok(svc.includes('assertVoicePermissions')&&svc.includes('finance.write')&&svc.includes('clinical.write'),'server enforces permissions per voice action');
ok(ui.includes('MediaRecorder')&&ui.includes('/api/voice/transcribe'),'native voice UI can send recorded audio to local ASR backend');
ok(svc.includes('planVoiceHybrid'),'preview and execution share hybrid planner, not separate interpretations');
console.log(`\n${p} passed, ${f} failed`);if(f)process.exit(1);
