import fs from 'node:fs';
const read=p=>fs.existsSync(p)?fs.readFileSync(p,'utf8'):'';
let pass=0,fail=0;function ok(cond,msg){if(cond){console.log('PASS',msg);pass++}else{console.error('FAIL',msg);fail++}}
const events=read('apps/api/src/modules/events/routes.ts');
const security=read('apps/api/src/modules/security/routes.ts');
const audit=read('packages/db/src/audit/verify-audit-chain.ts');
const attachments=read('apps/api/src/modules/laboratory/attachments.ts');
const config=read('apps/api/src/config/production.ts');
const server=read('apps/api/src/server.ts');
const scheduler=read('apps/api/src/modules/security/backup-scheduler.ts');
const pkg=JSON.parse(read('package.json')||'{}');
ok(events.includes('last-event-id')&&events.includes('resumeFromEventId'),'SSE resumes from Last-Event-ID instead of replaying an arbitrary five-second window');
ok(security.includes('/api/security/audit/verify')&&security.includes('verifyAuditChain'),'admin can verify the server-side audit chain');
ok(audit.includes('previousHash')&&audit.includes('eventHash')&&audit.includes('AUDIT_CHAIN_BROKEN'),'audit verifier detects tampering or broken links');
ok(attachments.includes('safeStoragePath')&&attachments.includes('ATTACHMENT_PATH_INVALID'),'lab attachment reads reject storage paths that escape the configured root');
ok(config.includes('assertProductionConfig')&&config.includes('DENTY_BACKUP_KEY')&&config.includes('DENTY_ATTACHMENT_KEY_BASE64'),'production startup validates critical encryption configuration');
ok(server.includes('assertProductionConfig()'),'API refuses unsafe production startup before serving requests');
ok(scheduler.includes('verifyRestoreCandidate')&&scheduler.includes('DENTY_RESTORE_DRILL_INTERVAL_DAYS'),'backup scheduler periodically performs a restore drill, not only decryption verification');
ok(typeof pkg.scripts?.['production:check']==='string'&&(pkg.scripts['production:check'].includes('verify_production_hardening_v2')||pkg.scripts['production:check'].includes('verify:all')),'production:check includes the hardening verification directly or through verify:all');
console.log(`\n${pass} passed, ${fail} failed`);if(fail)process.exit(1);
