import fs from 'node:fs';
import assert from 'node:assert/strict';

const root = JSON.parse(fs.readFileSync('package.json','utf8'));
const db = JSON.parse(fs.readFileSync('packages/db/package.json','utf8'));
const baseline = fs.existsSync('packages/db/scripts/generate-baseline.mjs') ? fs.readFileSync('packages/db/scripts/generate-baseline.mjs','utf8') : '';
const preflight = fs.existsSync('packages/db/scripts/assert-migrations.mjs') ? fs.readFileSync('packages/db/scripts/assert-migrations.mjs','utf8') : '';
const deploy = db.scripts?.['db:migrate'] ?? '';

const checks = [
  ['root exposes a db:baseline command', /db:baseline/.test(JSON.stringify(root.scripts ?? {}))],
  ['db package exposes baseline and migration status commands', Boolean(db.scripts?.['db:baseline']) && Boolean(db.scripts?.['db:status'])],
  ['baseline is generated by prisma migrate diff from empty schema', /migrate["'`,\s]+diff/.test(baseline) && /--from-empty/.test(baseline) && /--to-schema/.test(baseline) && /--script/.test(baseline)],
  ['baseline generator refuses silent overwrite unless explicitly forced', /--force/.test(baseline) && /(already exists|refus|overwrite)/i.test(baseline)],
  ['baseline generator detects any pre-existing migration history before rebuilding', /existingMigrationDirs/.test(baseline) && /readdirSync/.test(baseline)],
  ['forced unpublished baseline rebuild removes old migration directories', /existingMigrationDirs/.test(baseline) && /rmSync/.test(baseline) && /recursive:\s*true/.test(baseline)],
  ['migration preflight requires versioned migration sql', /migration\.sql/.test(preflight) && /(no versioned prisma migrations|missing.*migration)/i.test(preflight)],
  ['migration preflight validates sqlite migration lock', /migration_lock\.toml/.test(preflight) && /sqlite/.test(preflight)],
  ['production check includes migration preflight before typecheck/build tests', /db:migrations:check/.test(root.scripts?.['production:check'] ?? '')],
  ['production deployment uses prisma migrate deploy', /prisma migrate deploy/.test(deploy)],
];

let passed=0;
for (const [name,ok] of checks) {
  if (ok) { console.log(`PASS ${name}`); passed++; }
  else console.error(`FAIL ${name}`);
}
console.log(`${passed}/${checks.length} checks passed`);
assert.equal(passed, checks.length);
