import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const app=readFileSync(new URL('../apps/legacy-preview/app.js',import.meta.url),'utf8');
const css=readFileSync(new URL('../apps/legacy-preview/styles/styles.css',import.meta.url),'utf8');
assert.match(app,/Sincronizar desde odontograma/,'la planificación profesional debe poder leer el odontograma');
assert.match(app,/Planes alternativos/,'la planificación debe mostrar alternativas');
assert.match(app,/data-approve-alt/,'la clínica debe poder validar una alternativa');
assert.match(app,/Me interesa esta opción/,'el paciente debe poder registrar preferencia');
assert.match(app,/¿Por qué va ahora\?/,'la ruta paciente debe explicar el orden');
assert.match(app,/Ventajas/,'las alternativas deben mostrar ventajas');
assert.match(app,/Inconvenientes/,'las alternativas deben mostrar inconvenientes');
assert.match(css,/\.clinical-alt-options/,'debe existir layout visual para alternativas profesionales');
assert.match(css,/\.patient-alt-options/,'debe existir layout visual para alternativas del paciente');
console.log('verify_clinical_plan_ui: OK');
