import fs from 'fs';
let p=0,f=0;const ok=(v,m)=>{(v?p++:f++);console[v?'log':'error'](v?'PASS':'FAIL',m)};
const schema=fs.readFileSync('packages/db/prisma/schema.prisma','utf8');
const sec=fs.readFileSync('apps/api/src/modules/security/routes.ts','utf8');
const server=fs.readFileSync('apps/api/src/server.ts','utf8');
const sched=fs.existsSync('apps/api/src/modules/security/backup-scheduler.ts')?fs.readFileSync('apps/api/src/modules/security/backup-scheduler.ts','utf8'):'';
ok(schema.includes('model PrivacyRequest'),'database stores data-subject/privacy requests');
ok(sec.includes('/api/security/privacy-requests'),'admin can register and review privacy requests');
ok(sec.includes('privacy_request.created'),'privacy requests are audited/domain-evented');
ok(sec.includes('ERASURE')&&sec.includes('archivedAt'),'erasure workflow uses retention-safe archival instead of deleting records');
ok(sched.includes('createEncryptedBackup')&&sched.includes('verifyEncryptedBackup'),'automatic backup creates and verifies encrypted copy');
ok(sched.includes('unref'),'backup timer does not prevent graceful shutdown');
ok(server.includes('startBackupScheduler'),'API starts automatic backup scheduler');
console.log(`\n${p} passed, ${f} failed`);if(f)process.exit(1);
