"use client";
import {useParams} from "next/navigation";
import {useApiData} from "../../../../lib/use-api-data";
import {api} from "../../../../lib/api";
import {useState} from "react";
import {PlanGraphEditor} from "../../../../features/treatment-plan/PlanGraphEditor";
import {NativeOdontogram} from "../../../../features/odontogram/NativeOdontogram";
export default function PatientProfile(){
 const{id}=useParams<{id:string}>(),{data:patient}=useApiData<any>(`/api/patients/${id}`,{}),{data:plan,refresh:refreshPlan}=useApiData<any>(`/api/patients/${id}/clinical-plan`,{route:[],alternativeSets:[]}),{data:od,refresh:refreshOd}=useApiData<any>(`/api/patients/${id}/odontogram`,{entities:[],version:1}),{data:docs}=useApiData<any>(`/api/documents?patientId=${id}`,{items:[]}),{data:users}=useApiData<any>("/api/users",{items:[]}),{data:grants,refresh:refreshGrants}=useApiData<any>(`/api/patients/${id}/family-grants`,{items:[]}),[tooth,setTooth]=useState("26"),[alternativeKind,setAlternativeKind]=useState("missing_tooth"),[familyUserId,setFamilyUserId]=useState(""),[familyRelation,setFamilyRelation]=useState("AUTHORIZED"),[portalMessage,setPortalMessage]=useState("");
 async function addCrown(){await api(`/api/patients/${id}/odontogram/entities`,{method:"POST",body:JSON.stringify({expectedVersion:od.version,entity:{tooth,entityType:"CROWN",status:"crown_pending",active:true}})});await refreshOd();await refreshPlan()}
 async function alternatives(){const availableData=alternativeKind==="missing_tooth"?["tooth_or_zone","adjacent_teeth","periodontal_context","occlusion","patient_priorities"]:["tooth","periodontal_context","occlusion","patient_priorities"];await api(`/api/patients/${id}/clinical-plan/alternatives`,{method:"POST",body:JSON.stringify({kind:alternativeKind,toothOrZone:tooth,missingTeeth:alternativeKind==="removable_design"?tooth.split(/[ ,]+/).filter(Boolean):undefined,availableData})});await refreshPlan()}
 async function budget(){await api(`/api/patients/${id}/clinical-plan/budget`,{method:"POST",body:"{}"});await refreshPlan()}
 async function rework(itemId:string){const reason=window.prompt("Motivo del retratamiento")?.trim();if(!reason)return;await api(`/api/clinical-plan/items/${itemId}/rework`,{method:"POST",body:JSON.stringify({reason})});await refreshPlan()}
 async function approveAlternative(optionId:string){await api(`/api/clinical-plan/alternatives/${optionId}/approve`,{method:"POST",body:"{}"});await refreshPlan()}
 async function confirmKennedy(set:any){const classification=window.prompt("Confirma la clasificación de Kennedy",set.suggestedClassification??"")?.trim();if(!classification)return;await api(`/api/clinical-plan/alternative-sets/${set.id}/classification`,{method:"POST",body:JSON.stringify({classification})});await refreshPlan()}
 async function invite(){const email=window.prompt("Email para enviar la invitación",patient.email??"")?.trim();if(!email)return;const r=await api<any>(`/api/patients/${id}/invitations`,{method:"POST",body:JSON.stringify({email,expiresHours:72})});setPortalMessage(`Invitación creada hasta ${new Date(r.expiresAt).toLocaleString("es-ES")}. Token de un solo uso: ${r.token}`);if(navigator.clipboard)void navigator.clipboard.writeText(r.token)}
 async function addFamily(){if(!familyUserId)return;await api(`/api/patients/${id}/family-grants`,{method:"POST",body:JSON.stringify({userId:familyUserId,relation:familyRelation})});setFamilyUserId("");await refreshGrants()}
 async function revokeFamily(grantId:string){await api(`/api/patients/${id}/family-grants/${grantId}`,{method:"DELETE"});await refreshGrants()}
 const patientUsers=(users.items??[]).filter((u:any)=>u.role==="PATIENT"&&u.active);
 return <><header className="native-topbar"><div><h1>{patient.firstName} {patient.lastName}</h1><p>{patient.recordNumber??"Ficha clínica"} · {patient.phone??"sin teléfono"}</p></div><button className="native-button" onClick={budget}>Presupuesto desde plan</button></header>
 <section className="native-grid two"><div className="native-card"><h2>Odontograma V3</h2><NativeOdontogram patientId={id} odontogram={od} refresh={async()=>{await refreshOd();await refreshPlan();}}/><div className="native-toolbar" style={{marginTop:10}}><input className="native-input" value={tooth} onChange={e=>setTooth(e.target.value)} style={{width:100}}/><select className="native-select" value={alternativeKind} onChange={e=>setAlternativeKind(e.target.value)}><option value="missing_tooth">Diente ausente</option><option value="tooth_prognosis">Conservar vs extraer</option><option value="restoration_choice">Restauración vs corona</option><option value="removable_design">Removible / Kennedy</option></select><button className="native-button" onClick={alternatives}>Crear alternativas</button></div></div><div className="native-card"><h2>Ruta hasta terminar</h2>{plan.route?.map((x:any,i:number)=>{const full=(plan.items??[]).find((p:any)=>p.id===x.id);return <div className="appointment-card" key={x.id} style={{marginBottom:8}}><small>Paso {i+1}</small><b style={{display:"block"}}>{x.patientLabel??x.label}</b><span>{x.status}</span>{x.clinicalReason&&<p>{x.clinicalReason}</p>}{x.status==="COMPLETED"&&full?.source!=="rework"&&<button className="native-button" style={{marginTop:8}} onClick={()=>void rework(x.id)}>Registrar retratamiento</button>}</div>})}{!plan.route?.length&&<div className="native-empty">Todavía no hay pasos clínicos definidos.</div>}</div></section>
 <section className="native-card" style={{marginTop:14}}><h2>Dependencias del plan</h2><PlanGraphEditor plan={plan} onChange={refreshPlan}/></section>
 <section className="native-grid two" style={{marginTop:14}}><div className="native-card"><h2>Opciones de tratamiento</h2>{plan.alternativeSets?.map((s:any)=><div key={s.id} className="native-card" style={{marginBottom:10}}><h3>{s.title}</h3>{s.suggestedClassification&&<div className="appointment-card" style={{marginBottom:8}}><b>Clasificación sugerida: Kennedy {s.suggestedClassification}</b><p>{s.confirmedClassification?`Confirmada por el profesional: Kennedy ${s.confirmedClassification}`:"Pendiente de confirmación clínica. Denty solo la sugiere."}</p>{!s.confirmedClassification&&<button className="native-button" onClick={()=>void confirmKennedy(s)}>Confirmar clasificación</button>}</div>}{s.options.map((o:any)=><details key={o.id}><summary><b>{o.title}</b> · {o.status}</summary><p><b>Ventajas:</b> {(o.prosJson??[]).join(" · ")}</p><p><b>Inconvenientes:</b> {(o.consJson??[]).join(" · ")}</p><p>Tiempo: {o.relativeTime??"—"} · Coste: {o.relativeCost??"—"}</p><p>Datos pendientes: {(o.missingDataJson??[]).join(", ")||"Ninguno"}</p>{o.preferences?.length?<p><b>Preferencia paciente:</b> {o.preferences.at(-1)?.preference}</p>:null}{o.status!=="CLINICALLY_APPROVED"&&!(o.missingDataJson??[]).length&&(!s.suggestedClassification||s.confirmedClassification)&&<button className="native-button primary" onClick={()=>void approveAlternative(o.id)}>Aprobar clínicamente</button>}</details>)}</div>)}</div><div className="native-card"><h2>Documentos</h2>{docs.items?.map((d:any)=><div key={d.id}><b>{d.title}</b> · {d.status}</div>)}</div></section>
 <section className="native-card" style={{marginTop:14}}><div className="native-topbar"><div><h2 style={{margin:0}}>Denty Paciente</h2><p>Invitación remota y acceso familiar/dependientes.</p></div><button className="native-button primary" onClick={()=>void invite()}>Invitar al portal</button></div>{portalMessage&&<div className="appointment-card state-green" style={{marginBottom:10}}>{portalMessage}</div>}<div className="native-toolbar"><select className="native-select" value={familyUserId} onChange={e=>setFamilyUserId(e.target.value)}><option value="">Cuenta de paciente/familiar…</option>{patientUsers.map((u:any)=><option key={u.id} value={u.id}>{u.displayName} · {u.email??u.username??u.id}</option>)}</select><select className="native-select" value={familyRelation} onChange={e=>setFamilyRelation(e.target.value)}><option value="GUARDIAN">Tutor/a</option><option value="AUTHORIZED">Autorizado/a</option><option value="FAMILY">Familiar</option></select><button className="native-button" onClick={()=>void addFamily()} disabled={!familyUserId}>Dar acceso</button></div>{grants.items?.map((g:any)=><div key={g.id} className="appointment-card" style={{marginBottom:8}}><b>{g.user?.displayName}</b><span style={{marginLeft:8}}>{g.relation}</span>{g.relation!=="self"&&<button className="native-button" style={{float:"right"}} onClick={()=>void revokeFamily(g.id)}>Revocar</button>}</div>)}</section>
 </>}
