import type { FastifyInstance } from "fastify";
import { createInvoiceDraftSchema, recordPaymentSchema, allocatePaymentSchema } from "@denty/contracts";
import { can } from "@denty/domain";
import { prisma } from "@denty/db";
import { getActor } from "../../plugins/actor";
import { getCorrelationId } from "../../plugins/correlation";
import { allocatePayment, createInvoiceDraft, issueInvoice, recordPayment, rectifyInvoice, submitInvoiceToVerifactu } from "./service";
import { renderInvoicePdf } from "./invoice-pdf";
function finance(actor:any,issue=false){if(!can(actor,issue?"billing.issue":"finance.write"))throw Object.assign(new Error("Forbidden"),{statusCode:403});}
export async function registerBillingRoutes(server:FastifyInstance){
 server.get("/api/budgets",async request=>{const actor=await getActor(request);if(!can(actor,"finance.read"))throw Object.assign(new Error("Forbidden"),{statusCode:403});return{items:await prisma.budget.findMany({where:{clinicId:actor.clinicId},include:{patient:true,items:true},orderBy:{createdAt:"desc"}})}});
 server.get("/api/invoice-series",async request=>{const actor=await getActor(request);if(!can(actor,"finance.read"))throw Object.assign(new Error("Forbidden"),{statusCode:403});return{items:await prisma.invoiceSeries.findMany({where:{clinicId:actor.clinicId,active:true},orderBy:{code:"asc"}})}});
 server.post<{Params:{id:string}}>("/api/budgets/:id/invoice-draft",async(request,reply)=>{const actor=await getActor(request);finance(actor);const budget=await prisma.budget.findFirstOrThrow({where:{id:request.params.id,clinicId:actor.clinicId},include:{patient:true,items:true}}),series=await prisma.invoiceSeries.findFirst({where:{clinicId:actor.clinicId,active:true}});if(!series)throw Object.assign(new Error("Configura una serie de facturación antes de crear facturas."),{statusCode:409});const accepted=budget.items.filter(i=>i.accepted!==false);return reply.code(201).send(await createInvoiceDraft(actor,{patientId:budget.patientId,budgetId:budget.id,seriesId:series.id,type:"STANDARD",customerName:`${budget.patient.firstName} ${budget.patient.lastName}`,customerTaxId:budget.patient.dni,lines:accepted.map(i=>({description:i.description,quantity:i.quantity,unitPriceCents:i.unitPriceCents,taxRateBps:0,clinicalPlanItemId:i.clinicalPlanItemId}))},getCorrelationId(request)))});
 server.get("/api/invoices",async request=>{const actor=await getActor(request);if(!can(actor,"finance.read"))throw Object.assign(new Error("Forbidden"),{statusCode:403});return{items:await prisma.invoice.findMany({where:{clinicId:actor.clinicId},include:{lines:true,allocations:true,fiscalRecord:{include:{submissions:true}}},orderBy:{createdAt:"desc"}})}});
 server.post("/api/invoices",async(request,reply)=>{const actor=await getActor(request);finance(actor);return reply.code(201).send(await createInvoiceDraft(actor,createInvoiceDraftSchema.parse(request.body),getCorrelationId(request)))});
 server.post<{Params:{id:string}}>("/api/invoices/:id/issue",async request=>{const actor=await getActor(request);finance(actor,true);return issueInvoice(actor,request.params.id,getCorrelationId(request))});
 server.post<{Params:{id:string}}>("/api/invoices/:id/rectify",async request=>{const actor=await getActor(request);finance(actor,true);return rectifyInvoice(actor,request.params.id,request.body as any,getCorrelationId(request))});
 server.get<{Params:{id:string}}>("/api/invoices/:id/pdf",async(request,reply)=>{const actor=await getActor(request);if(!can(actor,"finance.read"))throw Object.assign(new Error("Forbidden"),{statusCode:403});const invoice=await prisma.invoice.findFirstOrThrow({where:{id:request.params.id,clinicId:actor.clinicId},include:{clinic:true,lines:true,fiscalRecord:true}});if(!["ISSUED","RECTIFIED"].includes(invoice.status))throw Object.assign(new Error("La factura debe estar emitida antes de generar el PDF fiscal."),{statusCode:409,code:"INVOICE_NOT_ISSUED"});if(!invoice.fullNumber||!invoice.issuedAt||!invoice.fiscalRecord?.qrPayload)throw Object.assign(new Error("La factura no tiene registro fiscal/QR disponible."),{statusCode:409,code:"FISCAL_QR_MISSING"});const pdf=renderInvoicePdf({...invoice,fullNumber:invoice.fullNumber,issuedAt:invoice.issuedAt,fiscalRecord:invoice.fiscalRecord});reply.type("application/pdf");reply.header("Cache-Control","private, no-store");reply.header("Content-Disposition",`inline; filename="${invoice.fullNumber.replace(/[^a-zA-Z0-9._-]+/g,"_")}.pdf"`);return reply.send(pdf)});
 server.post<{Params:{id:string}}>("/api/invoices/:id/verifactu/submit",async request=>{const actor=await getActor(request);finance(actor,true);return submitInvoiceToVerifactu(actor,request.params.id,getCorrelationId(request))});
 server.get("/api/payments",async request=>{const actor=await getActor(request);if(!can(actor,"finance.read"))throw Object.assign(new Error("Forbidden"),{statusCode:403});return{items:await prisma.payment.findMany({where:{clinicId:actor.clinicId},include:{allocations:{include:{invoice:true}}},orderBy:{receivedAt:"desc"},take:250})}});
 server.post("/api/payments",async(request,reply)=>{const actor=await getActor(request);finance(actor);return reply.code(201).send(await recordPayment(actor,recordPaymentSchema.parse(request.body),getCorrelationId(request)))});
 server.post<{Params:{id:string}}>("/api/payments/:id/allocate",async request=>{const actor=await getActor(request);finance(actor);return allocatePayment(actor,request.params.id,allocatePaymentSchema.parse(request.body),getCorrelationId(request))});
 server.get<{Querystring:{start?:string;end?:string}}>("/api/accounting/export.csv",async(request,reply)=>{const actor=await getActor(request);if(!can(actor,"finance.read"))throw Object.assign(new Error("Forbidden"),{statusCode:403});const start=request.query.start?new Date(request.query.start):new Date(Date.UTC(new Date().getUTCFullYear(),0,1)),end=request.query.end?new Date(request.query.end):new Date();const [invoices,payments]=await Promise.all([prisma.invoice.findMany({where:{clinicId:actor.clinicId,issuedAt:{gte:start,lte:end},status:{in:["ISSUED","RECTIFIED"]}},include:{allocations:true},orderBy:{issuedAt:"asc"}}),prisma.payment.findMany({where:{clinicId:actor.clinicId,receivedAt:{gte:start,lte:end}},orderBy:{receivedAt:"asc"}})]);const esc=(v:any)=>`"${String(v??"").replace(/"/g,'""')}"`,rows=[["tipo","fecha","referencia","cliente_paciente","base_cents","iva_cents","total_cents","metodo","cobrado_cents"],...invoices.map(i=>["FACTURA",i.issuedAt?.toISOString()??"",i.fullNumber??"",i.customerName,i.subtotalCents,i.taxCents,i.totalCents,"",i.allocations.reduce((n,a)=>n+a.amountCents,0)]),...payments.map(p=>["COBRO",p.receivedAt.toISOString(),p.reference??p.id,p.patientId??"",0,0,p.amountCents,p.method,p.amountCents])];reply.type("text/csv; charset=utf-8");reply.header("Content-Disposition",`attachment; filename=contabilidad-${start.toISOString().slice(0,10)}-${end.toISOString().slice(0,10)}.csv`);return '\ufeff'+rows.map(r=>r.map(esc).join(",")).join("\n")});
 server.post("/api/invoice-series",async request=>{const actor=await getActor(request);finance(actor,true);const b=request.body as any;return prisma.invoiceSeries.create({data:{clinicId:actor.clinicId,code:String(b.code),name:String(b.name)}})});
}
