-- Applied after explicit user approval as 20261001100659_consolidate_permissive_rls_policies.sql.
-- Historical proposal: use the guarded migration rather than running this file directly.
-- Split ALL policies and combine permissive alternatives by operation.
-- USING and WITH CHECK preserve the original OR semantics for authenticated.
drop policy "staff_members_admin_manage" on public."staff_members";
drop policy "staff_members_staff_select" on public."staff_members";
create policy "staff_members_select_access" on public."staff_members" for SELECT to authenticated using ((( SELECT private.is_clinic_admin(staff_members.clinic_id) AS is_clinic_admin)) OR (( SELECT private.is_clinic_staff(staff_members.clinic_id) AS is_clinic_staff)));
create policy "staff_members_insert_access" on public."staff_members" for INSERT to authenticated with check ((( SELECT private.is_clinic_admin(staff_members.clinic_id) AS is_clinic_admin)));
create policy "staff_members_update_access" on public."staff_members" for UPDATE to authenticated using ((( SELECT private.is_clinic_admin(staff_members.clinic_id) AS is_clinic_admin))) with check ((( SELECT private.is_clinic_admin(staff_members.clinic_id) AS is_clinic_admin)));
create policy "staff_members_delete_access" on public."staff_members" for DELETE to authenticated using ((( SELECT private.is_clinic_admin(staff_members.clinic_id) AS is_clinic_admin)));
drop policy "clinical_plan_dependencies_access" on public."clinical_plan_dependencies";
drop policy "clinical_plan_dependencies_staff_manage" on public."clinical_plan_dependencies";
create policy "clinical_plan_dependencies_select_access" on public."clinical_plan_dependencies" for SELECT to authenticated using (((( SELECT private.is_clinic_staff(clinical_plan_dependencies.clinic_id) AS is_clinic_staff) OR (EXISTS ( SELECT 1
   FROM (clinical_plan_items i
     JOIN clinical_plans p ON ((p.id = i.plan_id)))
  WHERE ((i.id = clinical_plan_dependencies.item_id) AND ( SELECT private.is_patient_owner(p.patient_id) AS is_patient_owner)))))) OR (( SELECT private.is_clinic_staff(clinical_plan_dependencies.clinic_id) AS is_clinic_staff)));
create policy "clinical_plan_dependencies_insert_access" on public."clinical_plan_dependencies" for INSERT to authenticated with check ((( SELECT private.is_clinic_staff(clinical_plan_dependencies.clinic_id) AS is_clinic_staff)));
create policy "clinical_plan_dependencies_update_access" on public."clinical_plan_dependencies" for UPDATE to authenticated using ((( SELECT private.is_clinic_staff(clinical_plan_dependencies.clinic_id) AS is_clinic_staff))) with check ((( SELECT private.is_clinic_staff(clinical_plan_dependencies.clinic_id) AS is_clinic_staff)));
create policy "clinical_plan_dependencies_delete_access" on public."clinical_plan_dependencies" for DELETE to authenticated using ((( SELECT private.is_clinic_staff(clinical_plan_dependencies.clinic_id) AS is_clinic_staff)));
drop policy "document_templates_admin_manage" on public."document_templates";
drop policy "document_templates_staff_select" on public."document_templates";
create policy "document_templates_select_access" on public."document_templates" for SELECT to authenticated using ((( SELECT private.is_clinic_admin(document_templates.clinic_id) AS is_clinic_admin)) OR (( SELECT private.is_clinic_staff(document_templates.clinic_id) AS is_clinic_staff)));
create policy "document_templates_insert_access" on public."document_templates" for INSERT to authenticated with check ((( SELECT private.is_clinic_admin(document_templates.clinic_id) AS is_clinic_admin)));
create policy "document_templates_update_access" on public."document_templates" for UPDATE to authenticated using ((( SELECT private.is_clinic_admin(document_templates.clinic_id) AS is_clinic_admin))) with check ((( SELECT private.is_clinic_admin(document_templates.clinic_id) AS is_clinic_admin)));
create policy "document_templates_delete_access" on public."document_templates" for DELETE to authenticated using ((( SELECT private.is_clinic_admin(document_templates.clinic_id) AS is_clinic_admin)));
drop policy "budget_items_access" on public."budget_items";
drop policy "budget_items_staff_manage" on public."budget_items";
create policy "budget_items_select_access" on public."budget_items" for SELECT to authenticated using (((( SELECT private.is_clinic_staff(budget_items.clinic_id) AS is_clinic_staff) OR (EXISTS ( SELECT 1
   FROM budgets b
  WHERE ((b.id = budget_items.budget_id) AND ( SELECT private.is_patient_owner(b.patient_id) AS is_patient_owner)))))) OR (( SELECT private.is_clinic_staff(budget_items.clinic_id) AS is_clinic_staff)));
create policy "budget_items_insert_access" on public."budget_items" for INSERT to authenticated with check ((( SELECT private.is_clinic_staff(budget_items.clinic_id) AS is_clinic_staff)));
create policy "budget_items_update_access" on public."budget_items" for UPDATE to authenticated using ((( SELECT private.is_clinic_staff(budget_items.clinic_id) AS is_clinic_staff))) with check ((( SELECT private.is_clinic_staff(budget_items.clinic_id) AS is_clinic_staff)));
create policy "budget_items_delete_access" on public."budget_items" for DELETE to authenticated using ((( SELECT private.is_clinic_staff(budget_items.clinic_id) AS is_clinic_staff)));
drop policy "sites_admin_manage" on public."sites";
drop policy "sites_staff_select" on public."sites";
create policy "sites_select_access" on public."sites" for SELECT to authenticated using ((( SELECT private.is_clinic_admin(sites.clinic_id) AS is_clinic_admin)) OR (( SELECT private.is_clinic_staff(sites.clinic_id) AS is_clinic_staff)));
create policy "sites_insert_access" on public."sites" for INSERT to authenticated with check ((( SELECT private.is_clinic_admin(sites.clinic_id) AS is_clinic_admin)));
create policy "sites_update_access" on public."sites" for UPDATE to authenticated using ((( SELECT private.is_clinic_admin(sites.clinic_id) AS is_clinic_admin))) with check ((( SELECT private.is_clinic_admin(sites.clinic_id) AS is_clinic_admin)));
create policy "sites_delete_access" on public."sites" for DELETE to authenticated using ((( SELECT private.is_clinic_admin(sites.clinic_id) AS is_clinic_admin)));
drop policy "clinic_settings_admin_manage" on public."clinic_settings";
drop policy "clinic_settings_staff_select" on public."clinic_settings";
create policy "clinic_settings_select_access" on public."clinic_settings" for SELECT to authenticated using ((( SELECT private.is_clinic_admin(clinic_settings.clinic_id) AS is_clinic_admin)) OR (( SELECT private.is_clinic_staff(clinic_settings.clinic_id) AS is_clinic_staff)));
create policy "clinic_settings_insert_access" on public."clinic_settings" for INSERT to authenticated with check ((( SELECT private.is_clinic_admin(clinic_settings.clinic_id) AS is_clinic_admin)));
create policy "clinic_settings_update_access" on public."clinic_settings" for UPDATE to authenticated using ((( SELECT private.is_clinic_admin(clinic_settings.clinic_id) AS is_clinic_admin))) with check ((( SELECT private.is_clinic_admin(clinic_settings.clinic_id) AS is_clinic_admin)));
create policy "clinic_settings_delete_access" on public."clinic_settings" for DELETE to authenticated using ((( SELECT private.is_clinic_admin(clinic_settings.clinic_id) AS is_clinic_admin)));
drop policy "staff_settings_admin_manage" on public."staff_settings";
drop policy "staff_settings_staff_select" on public."staff_settings";
create policy "staff_settings_select_access" on public."staff_settings" for SELECT to authenticated using ((( SELECT private.is_clinic_admin(staff_settings.clinic_id) AS is_clinic_admin)) OR (( SELECT private.is_clinic_staff(staff_settings.clinic_id) AS is_clinic_staff)));
create policy "staff_settings_insert_access" on public."staff_settings" for INSERT to authenticated with check ((( SELECT private.is_clinic_admin(staff_settings.clinic_id) AS is_clinic_admin)));
create policy "staff_settings_update_access" on public."staff_settings" for UPDATE to authenticated using ((( SELECT private.is_clinic_admin(staff_settings.clinic_id) AS is_clinic_admin))) with check ((( SELECT private.is_clinic_admin(staff_settings.clinic_id) AS is_clinic_admin)));
create policy "staff_settings_delete_access" on public."staff_settings" for DELETE to authenticated using ((( SELECT private.is_clinic_admin(staff_settings.clinic_id) AS is_clinic_admin)));
drop policy "clinic_payment_methods_admin_manage" on public."clinic_payment_methods";
drop policy "clinic_payment_methods_staff_select" on public."clinic_payment_methods";
create policy "clinic_payment_methods_select_access" on public."clinic_payment_methods" for SELECT to authenticated using ((( SELECT private.is_clinic_admin(clinic_payment_methods.clinic_id) AS is_clinic_admin)) OR (( SELECT private.is_clinic_staff(clinic_payment_methods.clinic_id) AS is_clinic_staff)));
create policy "clinic_payment_methods_insert_access" on public."clinic_payment_methods" for INSERT to authenticated with check ((( SELECT private.is_clinic_admin(clinic_payment_methods.clinic_id) AS is_clinic_admin)));
create policy "clinic_payment_methods_update_access" on public."clinic_payment_methods" for UPDATE to authenticated using ((( SELECT private.is_clinic_admin(clinic_payment_methods.clinic_id) AS is_clinic_admin))) with check ((( SELECT private.is_clinic_admin(clinic_payment_methods.clinic_id) AS is_clinic_admin)));
create policy "clinic_payment_methods_delete_access" on public."clinic_payment_methods" for DELETE to authenticated using ((( SELECT private.is_clinic_admin(clinic_payment_methods.clinic_id) AS is_clinic_admin)));
drop policy "payment_terminals_admin_manage" on public."payment_terminals";
drop policy "payment_terminals_staff_select" on public."payment_terminals";
create policy "payment_terminals_select_access" on public."payment_terminals" for SELECT to authenticated using ((( SELECT private.is_clinic_admin(payment_terminals.clinic_id) AS is_clinic_admin)) OR (( SELECT private.is_clinic_staff(payment_terminals.clinic_id) AS is_clinic_staff)));
create policy "payment_terminals_insert_access" on public."payment_terminals" for INSERT to authenticated with check ((( SELECT private.is_clinic_admin(payment_terminals.clinic_id) AS is_clinic_admin)));
create policy "payment_terminals_update_access" on public."payment_terminals" for UPDATE to authenticated using ((( SELECT private.is_clinic_admin(payment_terminals.clinic_id) AS is_clinic_admin))) with check ((( SELECT private.is_clinic_admin(payment_terminals.clinic_id) AS is_clinic_admin)));
create policy "payment_terminals_delete_access" on public."payment_terminals" for DELETE to authenticated using ((( SELECT private.is_clinic_admin(payment_terminals.clinic_id) AS is_clinic_admin)));
drop policy "appointment_blocks_staff_manage" on public."appointment_blocks";
drop policy "appointment_blocks_staff_select" on public."appointment_blocks";
create policy "appointment_blocks_select_access" on public."appointment_blocks" for SELECT to authenticated using ((( SELECT private.is_clinic_staff(appointment_blocks.clinic_id) AS is_clinic_staff)));
create policy "appointment_blocks_insert_access" on public."appointment_blocks" for INSERT to authenticated with check ((( SELECT private.is_clinic_staff(appointment_blocks.clinic_id) AS is_clinic_staff)));
create policy "appointment_blocks_update_access" on public."appointment_blocks" for UPDATE to authenticated using ((( SELECT private.is_clinic_staff(appointment_blocks.clinic_id) AS is_clinic_staff))) with check ((( SELECT private.is_clinic_staff(appointment_blocks.clinic_id) AS is_clinic_staff)));
create policy "appointment_blocks_delete_access" on public."appointment_blocks" for DELETE to authenticated using ((( SELECT private.is_clinic_staff(appointment_blocks.clinic_id) AS is_clinic_staff)));
drop policy "patient_recalls_access" on public."patient_recalls";
drop policy "patient_recalls_staff_manage" on public."patient_recalls";
create policy "patient_recalls_select_access" on public."patient_recalls" for SELECT to authenticated using ((( SELECT private.can_access_patient(patient_recalls.clinic_id, patient_recalls.patient_id) AS can_access_patient)) OR (( SELECT private.is_clinic_staff(patient_recalls.clinic_id) AS is_clinic_staff)));
create policy "patient_recalls_insert_access" on public."patient_recalls" for INSERT to authenticated with check ((( SELECT private.is_clinic_staff(patient_recalls.clinic_id) AS is_clinic_staff)));
create policy "patient_recalls_update_access" on public."patient_recalls" for UPDATE to authenticated using ((( SELECT private.is_clinic_staff(patient_recalls.clinic_id) AS is_clinic_staff))) with check ((( SELECT private.is_clinic_staff(patient_recalls.clinic_id) AS is_clinic_staff)));
create policy "patient_recalls_delete_access" on public."patient_recalls" for DELETE to authenticated using ((( SELECT private.is_clinic_staff(patient_recalls.clinic_id) AS is_clinic_staff)));
drop policy "budgets_access" on public."budgets";
drop policy "budgets_staff_manage" on public."budgets";
create policy "budgets_select_access" on public."budgets" for SELECT to authenticated using ((( SELECT private.can_access_patient(budgets.clinic_id, budgets.patient_id) AS can_access_patient)) OR (( SELECT private.is_clinic_staff(budgets.clinic_id) AS is_clinic_staff)));
create policy "budgets_insert_access" on public."budgets" for INSERT to authenticated with check ((( SELECT private.is_clinic_staff(budgets.clinic_id) AS is_clinic_staff)));
create policy "budgets_update_access" on public."budgets" for UPDATE to authenticated using ((( SELECT private.is_clinic_staff(budgets.clinic_id) AS is_clinic_staff))) with check ((( SELECT private.is_clinic_staff(budgets.clinic_id) AS is_clinic_staff)));
create policy "budgets_delete_access" on public."budgets" for DELETE to authenticated using ((( SELECT private.is_clinic_staff(budgets.clinic_id) AS is_clinic_staff)));
drop policy "clinic_payment_settings_admin_manage" on public."clinic_payment_settings";
drop policy "clinic_payment_settings_staff_select" on public."clinic_payment_settings";
create policy "clinic_payment_settings_select_access" on public."clinic_payment_settings" for SELECT to authenticated using ((( SELECT private.is_clinic_admin(clinic_payment_settings.clinic_id) AS is_clinic_admin)) OR (( SELECT private.is_clinic_staff(clinic_payment_settings.clinic_id) AS is_clinic_staff)));
create policy "clinic_payment_settings_insert_access" on public."clinic_payment_settings" for INSERT to authenticated with check ((( SELECT private.is_clinic_admin(clinic_payment_settings.clinic_id) AS is_clinic_admin)));
create policy "clinic_payment_settings_update_access" on public."clinic_payment_settings" for UPDATE to authenticated using ((( SELECT private.is_clinic_admin(clinic_payment_settings.clinic_id) AS is_clinic_admin))) with check ((( SELECT private.is_clinic_admin(clinic_payment_settings.clinic_id) AS is_clinic_admin)));
create policy "clinic_payment_settings_delete_access" on public."clinic_payment_settings" for DELETE to authenticated using ((( SELECT private.is_clinic_admin(clinic_payment_settings.clinic_id) AS is_clinic_admin)));
drop policy "cabinets_admin_manage" on public."cabinets";
drop policy "cabinets_staff_select" on public."cabinets";
create policy "cabinets_select_access" on public."cabinets" for SELECT to authenticated using ((( SELECT private.is_clinic_admin(cabinets.clinic_id) AS is_clinic_admin)) OR (( SELECT private.is_clinic_staff(cabinets.clinic_id) AS is_clinic_staff)));
create policy "cabinets_insert_access" on public."cabinets" for INSERT to authenticated with check ((( SELECT private.is_clinic_admin(cabinets.clinic_id) AS is_clinic_admin)));
create policy "cabinets_update_access" on public."cabinets" for UPDATE to authenticated using ((( SELECT private.is_clinic_admin(cabinets.clinic_id) AS is_clinic_admin))) with check ((( SELECT private.is_clinic_admin(cabinets.clinic_id) AS is_clinic_admin)));
create policy "cabinets_delete_access" on public."cabinets" for DELETE to authenticated using ((( SELECT private.is_clinic_admin(cabinets.clinic_id) AS is_clinic_admin)));
drop policy "clinical_plans_access" on public."clinical_plans";
drop policy "clinical_plans_staff_manage" on public."clinical_plans";
create policy "clinical_plans_select_access" on public."clinical_plans" for SELECT to authenticated using ((( SELECT private.can_access_patient(clinical_plans.clinic_id, clinical_plans.patient_id) AS can_access_patient)) OR (( SELECT private.is_clinic_staff(clinical_plans.clinic_id) AS is_clinic_staff)));
create policy "clinical_plans_insert_access" on public."clinical_plans" for INSERT to authenticated with check ((( SELECT private.is_clinic_staff(clinical_plans.clinic_id) AS is_clinic_staff)));
create policy "clinical_plans_update_access" on public."clinical_plans" for UPDATE to authenticated using ((( SELECT private.is_clinic_staff(clinical_plans.clinic_id) AS is_clinic_staff))) with check ((( SELECT private.is_clinic_staff(clinical_plans.clinic_id) AS is_clinic_staff)));
create policy "clinical_plans_delete_access" on public."clinical_plans" for DELETE to authenticated using ((( SELECT private.is_clinic_staff(clinical_plans.clinic_id) AS is_clinic_staff)));
drop policy "clinical_plan_items_access" on public."clinical_plan_items";
drop policy "clinical_plan_items_staff_manage" on public."clinical_plan_items";
create policy "clinical_plan_items_select_access" on public."clinical_plan_items" for SELECT to authenticated using (((( SELECT private.is_clinic_staff(clinical_plan_items.clinic_id) AS is_clinic_staff) OR (EXISTS ( SELECT 1
   FROM clinical_plans p
  WHERE ((p.id = clinical_plan_items.plan_id) AND ( SELECT private.is_patient_owner(p.patient_id) AS is_patient_owner)))))) OR (( SELECT private.is_clinic_staff(clinical_plan_items.clinic_id) AS is_clinic_staff)));
create policy "clinical_plan_items_insert_access" on public."clinical_plan_items" for INSERT to authenticated with check ((( SELECT private.is_clinic_staff(clinical_plan_items.clinic_id) AS is_clinic_staff)));
create policy "clinical_plan_items_update_access" on public."clinical_plan_items" for UPDATE to authenticated using ((( SELECT private.is_clinic_staff(clinical_plan_items.clinic_id) AS is_clinic_staff))) with check ((( SELECT private.is_clinic_staff(clinical_plan_items.clinic_id) AS is_clinic_staff)));
create policy "clinical_plan_items_delete_access" on public."clinical_plan_items" for DELETE to authenticated using ((( SELECT private.is_clinic_staff(clinical_plan_items.clinic_id) AS is_clinic_staff)));
drop policy "periodontal_access" on public."periodontal_measurements";
drop policy "periodontal_staff_manage" on public."periodontal_measurements";
create policy "periodontal_measurements_select_access" on public."periodontal_measurements" for SELECT to authenticated using ((( SELECT private.can_access_patient(periodontal_measurements.clinic_id, periodontal_measurements.patient_id) AS can_access_patient)) OR (( SELECT private.is_clinic_staff(periodontal_measurements.clinic_id) AS is_clinic_staff)));
create policy "periodontal_measurements_insert_access" on public."periodontal_measurements" for INSERT to authenticated with check ((( SELECT private.is_clinic_staff(periodontal_measurements.clinic_id) AS is_clinic_staff)));
create policy "periodontal_measurements_update_access" on public."periodontal_measurements" for UPDATE to authenticated using ((( SELECT private.is_clinic_staff(periodontal_measurements.clinic_id) AS is_clinic_staff))) with check ((( SELECT private.is_clinic_staff(periodontal_measurements.clinic_id) AS is_clinic_staff)));
create policy "periodontal_measurements_delete_access" on public."periodontal_measurements" for DELETE to authenticated using ((( SELECT private.is_clinic_staff(periodontal_measurements.clinic_id) AS is_clinic_staff)));
drop policy "consent_requirements_access" on public."consent_requirements";
drop policy "consent_requirements_staff_manage" on public."consent_requirements";
create policy "consent_requirements_select_access" on public."consent_requirements" for SELECT to authenticated using ((( SELECT private.can_access_patient(consent_requirements.clinic_id, consent_requirements.patient_id) AS can_access_patient)) OR (( SELECT private.is_clinic_staff(consent_requirements.clinic_id) AS is_clinic_staff)));
create policy "consent_requirements_insert_access" on public."consent_requirements" for INSERT to authenticated with check ((( SELECT private.is_clinic_staff(consent_requirements.clinic_id) AS is_clinic_staff)));
create policy "consent_requirements_update_access" on public."consent_requirements" for UPDATE to authenticated using ((( SELECT private.is_clinic_staff(consent_requirements.clinic_id) AS is_clinic_staff))) with check ((( SELECT private.is_clinic_staff(consent_requirements.clinic_id) AS is_clinic_staff)));
create policy "consent_requirements_delete_access" on public."consent_requirements" for DELETE to authenticated using ((( SELECT private.is_clinic_staff(consent_requirements.clinic_id) AS is_clinic_staff)));
drop policy "ai_clinical_reviews_staff_manage" on public."ai_clinical_reviews";
drop policy "ai_clinical_reviews_staff_select" on public."ai_clinical_reviews";
create policy "ai_clinical_reviews_select_access" on public."ai_clinical_reviews" for SELECT to authenticated using ((( SELECT private.is_clinic_staff(ai_clinical_reviews.clinic_id) AS is_clinic_staff)));
create policy "ai_clinical_reviews_insert_access" on public."ai_clinical_reviews" for INSERT to authenticated with check ((( SELECT private.is_clinic_staff(ai_clinical_reviews.clinic_id) AS is_clinic_staff)));
create policy "ai_clinical_reviews_update_access" on public."ai_clinical_reviews" for UPDATE to authenticated using ((( SELECT private.is_clinic_staff(ai_clinical_reviews.clinic_id) AS is_clinic_staff))) with check ((( SELECT private.is_clinic_staff(ai_clinical_reviews.clinic_id) AS is_clinic_staff)));
create policy "ai_clinical_reviews_delete_access" on public."ai_clinical_reviews" for DELETE to authenticated using ((( SELECT private.is_clinic_staff(ai_clinical_reviews.clinic_id) AS is_clinic_staff)));
drop policy "staff_schedules_admin_manage" on public."staff_schedules";
drop policy "staff_schedules_staff_select" on public."staff_schedules";
create policy "staff_schedules_select_access" on public."staff_schedules" for SELECT to authenticated using ((( SELECT private.is_clinic_admin(staff_schedules.clinic_id) AS is_clinic_admin)) OR (( SELECT private.is_clinic_staff(staff_schedules.clinic_id) AS is_clinic_staff)));
create policy "staff_schedules_insert_access" on public."staff_schedules" for INSERT to authenticated with check ((( SELECT private.is_clinic_admin(staff_schedules.clinic_id) AS is_clinic_admin)));
create policy "staff_schedules_update_access" on public."staff_schedules" for UPDATE to authenticated using ((( SELECT private.is_clinic_admin(staff_schedules.clinic_id) AS is_clinic_admin))) with check ((( SELECT private.is_clinic_admin(staff_schedules.clinic_id) AS is_clinic_admin)));
create policy "staff_schedules_delete_access" on public."staff_schedules" for DELETE to authenticated using ((( SELECT private.is_clinic_admin(staff_schedules.clinic_id) AS is_clinic_admin)));
drop policy "patient_waitlist_access" on public."patient_waitlist_requests";
drop policy "patient_waitlist_patient_insert" on public."patient_waitlist_requests";
drop policy "patient_waitlist_staff_manage" on public."patient_waitlist_requests";
create policy "patient_waitlist_requests_select_access" on public."patient_waitlist_requests" for SELECT to authenticated using ((( SELECT private.can_access_patient(patient_waitlist_requests.clinic_id, patient_waitlist_requests.patient_id) AS can_access_patient)) OR (( SELECT private.is_clinic_staff(patient_waitlist_requests.clinic_id) AS is_clinic_staff)));
create policy "patient_waitlist_requests_insert_access" on public."patient_waitlist_requests" for INSERT to authenticated with check (((( SELECT private.is_patient_owner(patient_waitlist_requests.patient_id) AS is_patient_owner) AND (priority = 0) AND (status = 'ACTIVE'::text) AND (fulfilled_at IS NULL) AND (appointment_id IS NULL))) OR (( SELECT private.is_clinic_staff(patient_waitlist_requests.clinic_id) AS is_clinic_staff)));
create policy "patient_waitlist_requests_update_access" on public."patient_waitlist_requests" for UPDATE to authenticated using ((( SELECT private.is_clinic_staff(patient_waitlist_requests.clinic_id) AS is_clinic_staff))) with check ((( SELECT private.is_clinic_staff(patient_waitlist_requests.clinic_id) AS is_clinic_staff)));
create policy "patient_waitlist_requests_delete_access" on public."patient_waitlist_requests" for DELETE to authenticated using ((( SELECT private.is_clinic_staff(patient_waitlist_requests.clinic_id) AS is_clinic_staff)));
drop policy "appointment_requests_access" on public."appointment_requests";
drop policy "appointment_requests_patient_insert" on public."appointment_requests";
drop policy "appointment_requests_patient_update" on public."appointment_requests";
drop policy "appointment_requests_staff_manage" on public."appointment_requests";
create policy "appointment_requests_select_access" on public."appointment_requests" for SELECT to authenticated using ((( SELECT private.can_access_patient(appointment_requests.clinic_id, appointment_requests.patient_id) AS can_access_patient)) OR (( SELECT private.is_clinic_staff(appointment_requests.clinic_id) AS is_clinic_staff)));
create policy "appointment_requests_insert_access" on public."appointment_requests" for INSERT to authenticated with check ((( SELECT private.is_patient_owner(appointment_requests.patient_id) AS is_patient_owner)) OR (( SELECT private.is_clinic_staff(appointment_requests.clinic_id) AS is_clinic_staff)));
create policy "appointment_requests_update_access" on public."appointment_requests" for UPDATE to authenticated using ((( SELECT private.is_patient_owner(appointment_requests.patient_id) AS is_patient_owner)) OR (( SELECT private.is_clinic_staff(appointment_requests.clinic_id) AS is_clinic_staff))) with check ((( SELECT private.is_patient_owner(appointment_requests.patient_id) AS is_patient_owner)) OR (( SELECT private.is_clinic_staff(appointment_requests.clinic_id) AS is_clinic_staff)));
create policy "appointment_requests_delete_access" on public."appointment_requests" for DELETE to authenticated using ((( SELECT private.is_clinic_staff(appointment_requests.clinic_id) AS is_clinic_staff)));
drop policy "staff_absences_admin_manage" on public."staff_absences";
drop policy "staff_absences_staff_select" on public."staff_absences";
create policy "staff_absences_select_access" on public."staff_absences" for SELECT to authenticated using ((( SELECT private.is_clinic_admin(staff_absences.clinic_id) AS is_clinic_admin)) OR (( SELECT private.is_clinic_staff(staff_absences.clinic_id) AS is_clinic_staff)));
create policy "staff_absences_insert_access" on public."staff_absences" for INSERT to authenticated with check ((( SELECT private.is_clinic_admin(staff_absences.clinic_id) AS is_clinic_admin)));
create policy "staff_absences_update_access" on public."staff_absences" for UPDATE to authenticated using ((( SELECT private.is_clinic_admin(staff_absences.clinic_id) AS is_clinic_admin))) with check ((( SELECT private.is_clinic_admin(staff_absences.clinic_id) AS is_clinic_admin)));
create policy "staff_absences_delete_access" on public."staff_absences" for DELETE to authenticated using ((( SELECT private.is_clinic_admin(staff_absences.clinic_id) AS is_clinic_admin)));
