"use client";
import {ChangeEvent,useState} from "react";
import {api,money} from "../../../lib/api";
import {useApiData,useRealtime} from "../../../lib/use-api-data";

function toBase64(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result??"").split(",")[1]??"");r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}
export default function Laboratory(){
  const{data,refresh}=useApiData<any>("/api/lab-works",{items:[]});useRealtime(refresh);const[busy,setBusy]=useState(""),[error,setError]=useState("");
  async function op(id:string,fn:()=>Promise<unknown>){setBusy(id);setError("");try{await fn();await refresh()}catch(e:any){setError(e?.payload?.error?.message??e?.message??"No se pudo completar la acción")}finally{setBusy("")}}
  async function transition(x:any,status:string){await op(x.id,()=>api(`/api/lab-works/${x.id}/transition`,{method:"POST",body:JSON.stringify({status,expectedVersion:x.version})}))}
  async function upload(x:any,e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value="";if(!file)return;const base64=await toBase64(file);await op(x.id,()=>api(`/api/lab-works/${x.id}/attachments`,{method:"POST",body:JSON.stringify({fileName:file.name,mimeType:file.type||"application/octet-stream",base64})}))}
  async function rework(x:any){const reason=window.prompt("Motivo de repetición / retratamiento")?.trim();if(!reason)return;const amount=window.prompt("Coste adicional del laboratorio (€)","0")??"0",costCents=Math.max(0,Math.round(Number(amount.replace(",","."))*100)||0);await op(x.id,()=>api(`/api/lab-works/${x.id}/rework`,{method:"POST",body:JSON.stringify({reason,costCents})}))}
  return <><header className="native-topbar"><div><h1>Laboratorio</h1><p>Impresión/escaneado → enviado → prueba → recibido → colocado, con archivos y repeticiones trazables.</p></div></header>{error&&<div className="native-error">{error}</div>}<div className="native-card"><table className="native-table"><thead><tr><th>Paciente</th><th>Trabajo</th><th>Laboratorio</th><th>ETA</th><th>Coste</th><th>Estado</th><th>Archivos</th><th>Acciones</th></tr></thead><tbody>{data.items.map((x:any)=><tr key={x.id}><td>{x.patient?.firstName} {x.patient?.lastName}</td><td><b>{x.title}</b><br/><small>{x.toothOrZone??""}</small>{x.reworkOfId&&<><br/><small>Repetición</small></>}</td><td>{x.lab?.name??"—"}</td><td>{x.etaAt?new Date(x.etaAt).toLocaleDateString("es-ES"):"—"}</td><td>{money(x.costCents)}</td><td><span className="native-badge">{x.status}</span></td><td>{(x.attachments??[]).length? (x.attachments??[]).map((a:any)=><div key={a.id}><a href={`/api/lab-works/${x.id}/attachments/${a.id}`}>{a.fileName}</a></div>):"—"}</td><td><div className="native-toolbar"><select className="native-select" value="" disabled={busy===x.id} onChange={e=>{if(e.target.value)void transition(x,e.target.value)}}><option value="">Cambiar…</option>{["IMPRESSION_TAKEN","SCANNED","SENT","IN_PRODUCTION","TRIAL","RECEIVED","PLACED","INCIDENT","CANCELLED"].map(s=><option key={s}>{s}</option>)}</select><label className="native-button" style={{cursor:"pointer"}}>Adjuntar<input type="file" hidden onChange={e=>void upload(x,e)}/></label><button className="native-button" disabled={busy===x.id} onClick={()=>void rework(x)}>Repetición</button></div></td></tr>)}</tbody></table>{!data.items.length&&<div className="native-empty">Sin trabajos de laboratorio.</div>}</div></>}
