"use client";
import {FormEvent,useMemo,useState} from "react";
import {api,money} from "../../../lib/api";
import {useApiData} from "../../../lib/use-api-data";

function period(year:number,currentYear:number){const start=new Date(Date.UTC(year,0,1));const end=year===currentYear?new Date():new Date(Date.UTC(year,11,31,23,59,59,999));return{start,end}}
function previousPeriod(p:{start:Date;end:Date}){return{start:new Date(Date.UTC(p.start.getUTCFullYear()-1,p.start.getUTCMonth(),p.start.getUTCDate(),p.start.getUTCHours(),p.start.getUTCMinutes(),p.start.getUTCSeconds(),p.start.getUTCMilliseconds())),end:new Date(Date.UTC(p.end.getUTCFullYear()-1,p.end.getUTCMonth(),p.end.getUTCDate(),p.end.getUTCHours(),p.end.getUTCMinutes(),p.end.getUTCSeconds(),p.end.getUTCMilliseconds()))}}
function query(p:{start:Date;end:Date},staffId:string,siteId:string,specialty:string){const q=new URLSearchParams({start:p.start.toISOString(),end:p.end.toISOString()});if(staffId)q.set("staffId",staffId);if(siteId)q.set("siteId",siteId);if(specialty)q.set("specialty",specialty);return q.toString()}
function Bars({items,valueKey,labelKey="name"}:{items:any[];valueKey:string;labelKey?:string}){const max=Math.max(1,...items.map(x=>Math.abs(Number(x[valueKey]??0))));return <div className="chart-bars">{items.slice(0,12).map((x,i)=><div className="chart-row" key={`${x[labelKey]}-${i}`}><span>{x[labelKey]}</span><div className="chart-track"><div className="chart-fill" style={{width:`${Math.max(2,Math.abs(Number(x[valueKey]??0))/max*100)}%`}}/></div><b>{money(Number(x[valueKey]??0))}</b></div>)}</div>}
function Lines({current,previous}:{current:any[];previous:any[]}){const all=[...current,...previous],max=Math.max(1,...all.map(x=>Number(x.invoicedCents??0))),w=700,h=190,p=24;const points=(arr:any[])=>arr.map((x,i)=>`${p+(i*(w-2*p)/Math.max(1,arr.length-1))},${h-p-(Number(x.invoicedCents??0)/max)*(h-2*p)}`).join(" ");return <svg viewBox={`0 0 ${w} ${h}`} style={{width:"100%",height:220}} role="img" aria-label="Facturación mensual comparada"><line x1={p} x2={p} y1={p} y2={h-p} stroke="#dfe7ef"/><line x1={p} x2={w-p} y1={h-p} y2={h-p} stroke="#dfe7ef"/><polyline points={points(previous)} fill="none" stroke="#8ea0b6" strokeWidth="3" strokeDasharray="7 6"/><polyline points={points(current)} fill="none" stroke="#2764d8" strokeWidth="4"/>{current.map((x,i)=><circle key={x.month} cx={p+i*(w-2*p)/Math.max(1,current.length-1)} cy={h-p-(Number(x.invoicedCents??0)/max)*(h-2*p)} r="4" fill="#2764d8"/>)}</svg>}
function MarginBridge({summary}:{summary:any}){
 const produced=Number(summary.marginEligibleProducedCents??summary.producedCents??0),direct=Number(summary.marginEligibleDirectCostCents??summary.directCostCents??summary.costCents??0),losses=Number(summary.lossCents??0),margin=Number(summary.marginCents??(produced-direct-losses)),afterCost=produced-direct;
 const values=[0,produced,afterCost,margin],min=Math.min(...values),max=Math.max(1,...values),w=700,h=235,top=28,bottom=48,left=24,right=24,plot=h-top-bottom,scale=(v:number)=>top+(max-v)/(max-min||1)*plot;
 const bars=[{label:summary.marginIsComplete===false?"Producción con coste conocido":"Producción",from:0,to:produced,value:produced,kind:"positive"},{label:"Costes directos",from:produced,to:afterCost,value:-direct,kind:"cost"},{label:"Pérdidas",from:afterCost,to:margin,value:-losses,kind:"loss"},{label:"Margen clínico",from:0,to:margin,value:margin,kind:"result"}],barW=104,gap=(w-left-right-bars.length*barW)/(bars.length-1);
 return <svg className="margin-bridge" viewBox={`0 0 ${w} ${h}`} role="img" aria-label={`Puente de margen: producción ${money(produced)}, costes directos ${money(direct)}, pérdidas ${money(losses)}, margen ${money(margin)}`}>
  <line x1={left} x2={w-right} y1={scale(0)} y2={scale(0)} className="margin-zero"/>
  {bars.map((b,i)=>{const x=left+i*(barW+gap),y1=scale(b.from),y2=scale(b.to),y=Math.min(y1,y2),height=Math.max(3,Math.abs(y2-y1));return <g key={b.label}><rect x={x} y={y} width={barW} height={height} rx="8" className={`margin-bar ${b.kind}`}/><text x={x+barW/2} y={h-26} textAnchor="middle" className="margin-label">{b.label}</text><text x={x+barW/2} y={Math.max(16,y-7)} textAnchor="middle" className="margin-value">{money(b.value)}</text>{i<bars.length-1&&i<2?<line x1={x+barW} x2={x+barW+gap} y1={scale(b.to)} y2={scale(b.to)} className="margin-connector"/>:null}</g>})}
 </svg>
}
const specialtyOptions=["Implantología","Ortodoncia","Endodoncia","Periodoncia e higiene","Cirugía","Prótesis y rehabilitación","Conservadora","Estética","Odontopediatría","Otros"];
function lossLabel(type:string){return ({"appointment.no_show":"Citas perdidas / NPA","treatment.rework":"Retratamientos","discount.applied":"Descuentos","refund.recorded":"Devoluciones","writeoff.recorded":"Impagos / incobrables"} as Record<string,string>)[type]??type}

export default function Analysis(){
 const currentYear=new Date().getFullYear(),[year,setYear]=useState(currentYear),[staffId,setStaffId]=useState(""),[siteId,setSiteId]=useState(""),[specialty,setSpecialty]=useState(""),[showPurchase,setShowPurchase]=useState(false),[showRecipe,setShowRecipe]=useState(false),[error,setError]=useState(""),[drilldown,setDrilldown]=useState<any>(null),[drillBusy,setDrillBusy]=useState(false);
 const current=period(year,currentYear),previous=previousPeriod(current),q=query(current,staffId,siteId,specialty),pq=query(previous,staffId,siteId,specialty),prev=year-1;
 const{data:context}=useApiData<any>("/api/agenda/context",{staff:[],sites:[]}),{data:summary,refresh:refreshSummary}=useApiData<any>(`/api/analytics/summary?${q}`,{}),{data:comparison}=useApiData<any>(`/api/analytics/comparison?${q}`,{}),{data:monthly}=useApiData<any>(`/api/analytics/monthly?${q}`,{items:[]}),{data:prevMonthly}=useApiData<any>(`/api/analytics/monthly?${pq}`,{items:[]}),{data:specialties}=useApiData<any>(`/api/analytics/specialties?${q}`,{items:[]}),{data:prevSpecialties}=useApiData<any>(`/api/analytics/specialties?${pq}`,{items:[]}),{data:treatments}=useApiData<any>(`/api/analytics/treatments?${q}`,{items:[]}),{data:doctors}=useApiData<any>(`/api/analytics/doctors?${q}`,{items:[]}),{data:losses}=useApiData<any>(`/api/analytics/losses?${q}`,{items:[]}),{data:purchases,refresh:refreshPurchases}=useApiData<any>(`/api/analytics/purchases?${q}`,{totalCents:0,bySupplier:[],byCategory:[]}),{data:recipes,refresh:refreshRecipes}=useApiData<any>("/api/analytics/cost-recipes",{items:[]}),{data:trace}=useApiData<any>(`/api/analytics/events?${q}&limit=30`,{items:[]});
 const delta=comparison.delta??{},kpis=useMemo(()=>[["Producido",summary.producedCents,delta.produced],["Facturado",summary.invoicedCents,delta.invoiced],["Cobrado",summary.collectedCents,delta.collected],["Margen clínico",summary.marginCents,delta.margin],["Costes directos",summary.directCostCents??summary.costCents,null],["Gasto proveedores",summary.purchaseSpendCents,null],["Pérdidas e ineficiencias",summary.inefficiencyCostCents??summary.lossCents,delta.losses]],[summary,delta]);
 async function createPurchase(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),amount=Math.max(0,Math.round(Number(String(f.get("amount")??"0").replace(",","."))*100)),body={supplierName:f.get("supplierName"),invoiceNumber:f.get("invoiceNumber"),issuedAt:new Date(String(f.get("issuedAt"))).toISOString(),totalCents:amount,siteId:f.get("siteId")||undefined,items:[{category:f.get("category")||"materials",description:f.get("description")||"Compra de material",quantity:1,unitCostCents:amount,totalCents:amount}]};setError("");try{await api("/api/supplier-invoices",{method:"POST",body:JSON.stringify(body)});setShowPurchase(false);await Promise.all([refreshPurchases(),refreshSummary()])}catch(e:any){setError(e?.payload?.error?.message??e?.message??"No se pudo registrar la compra")}}
 async function createRecipe(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),unitCostCents=Math.max(0,Math.round(Number(String(f.get("cost")??"0").replace(",","."))*100));setError("");try{await api("/api/analytics/cost-recipes",{method:"POST",body:JSON.stringify({treatmentCode:f.get("treatmentCode"),name:f.get("name")||f.get("treatmentCode"),items:[{category:f.get("category")||"material",description:f.get("description"),quantity:Number(f.get("quantity")||1),unitCostCents}]})});setShowRecipe(false);await refreshRecipes()}catch(e:any){setError(e?.payload?.error?.message??e?.message??"No se pudo crear la receta de coste")}}
 async function openTreatment(category:string){setDrillBusy(true);setError("");try{const join=q?`${q}&`:"";setDrilldown(await api(`/api/analytics/treatments/drilldown?${join}category=${encodeURIComponent(category)}`))}catch(e:any){setError(e?.payload?.error?.message??e?.message??"No se pudo abrir la trazabilidad del tratamiento")}finally{setDrillBusy(false)}}
 return <><header className="native-topbar"><div><h1>Análisis</h1><p>Tu clínica, en números. Cada cifra se puede reconstruir desde eventos y costes trazables.</p></div><div className="native-toolbar"><button className="native-button" onClick={()=>setShowPurchase(v=>!v)}>+ Compra</button><button className="native-button" onClick={()=>setShowRecipe(v=>!v)}>+ Receta de coste</button></div></header>
 {error&&<div className="native-error">{error}</div>}
 <div className="native-toolbar"><select className="native-select" value={year} onChange={e=>setYear(Number(e.target.value))}>{Array.from({length:6},(_,i)=>currentYear-i).map(y=><option key={y}>{y}</option>)}</select><select className="native-select" value={siteId} onChange={e=>setSiteId(e.target.value)}><option value="">Todas las sedes</option>{context.sites?.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="native-select" value={staffId} onChange={e=>setStaffId(e.target.value)}><option value="">Todos los doctores</option>{context.staff?.filter((x:any)=>x.role==="DENTIST").map((x:any)=><option key={x.id} value={x.id}>{x.displayName}</option>)}</select><select className="native-select" value={specialty} onChange={e=>setSpecialty(e.target.value)}><option value="">Todas las especialidades</option>{specialtyOptions.map(x=><option key={x} value={x}>{x}</option>)}</select><span className="native-badge">{year===currentYear?`YTD hasta ${current.end.toLocaleDateString("es-ES")}`:"Año completo"} · comparando con {prev}</span></div>
 {summary.marginIsComplete===false&&<div className="native-warning"><b>Costes históricos incompletos.</b> El margen solo usa tratamientos cuyo coste está documentado. Cobertura actual: <b>{Number(summary.marginCoveragePercent??0).toFixed(1)} %</b> de la producción. La producción y los cobros sí se muestran completos cuando existen datos.</div>}
 {showPurchase&&<form className="native-card native-toolbar" onSubmit={createPurchase} style={{marginBottom:14}}><input className="native-input" name="supplierName" placeholder="Proveedor" required/><input className="native-input" name="invoiceNumber" placeholder="Nº factura" required/><input className="native-input" name="issuedAt" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/><select className="native-select" name="siteId"><option value="">Sin sede</option>{context.sites?.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input className="native-input" name="category" placeholder="Categoría" defaultValue="materials"/><input className="native-input" name="description" placeholder="Descripción" required/><input className="native-input" name="amount" inputMode="decimal" placeholder="Total €" required/><button className="native-button primary">Registrar compra</button></form>}
 {showRecipe&&<form className="native-card native-toolbar" onSubmit={createRecipe} style={{marginBottom:14}}><input className="native-input" name="treatmentCode" placeholder="Código tratamiento, ej. implant" required/><input className="native-input" name="name" placeholder="Nombre"/><input className="native-input" name="category" placeholder="Categoría" defaultValue="material"/><input className="native-input" name="description" placeholder="Material / coste" required/><input className="native-input" name="quantity" type="number" min="1" defaultValue="1"/><input className="native-input" name="cost" inputMode="decimal" placeholder="Coste unitario €" required/><button className="native-button primary">Crear receta</button></form>}
 <section className="native-grid kpis">{kpis.map(([label,value,d]:any[])=>{const pct=d?.percent;return <div className="native-card native-kpi" key={String(label)}><small>{label}</small><strong>{money(Number(value??0))}</strong><span style={{color:pct!=null&&pct>=0?"var(--denty-green)":"var(--denty-muted)",fontSize:12}}>{d?.incomplete?"costes históricos incompletos":pct==null?"sin base comparable":`${pct>=0?"+":""}${pct.toFixed(1)} % vs ${prev}`}</span></div>})}</section>
 <section className="native-card" style={{marginTop:14}}><h2>Puente de margen</h2><p><small>Cómo la producción clínica se convierte en margen después de costes directos y pérdidas operativas. Las compras a proveedores se muestran aparte para no duplicar costes ya incluidos en las recetas.</small></p><MarginBridge summary={summary}/></section>
 <section className="native-card" style={{marginTop:14}}><h2>Rentabilidad por especialidad</h2><table className="native-table"><thead><tr><th>Especialidad</th><th>Producido {year}</th><th>Producido {prev}</th><th>Δ</th><th>Coste directo</th><th>Margen</th><th>Margen %</th><th>Cobertura</th></tr></thead><tbody>{(specialties.items??[]).map((x:any)=>{const py=(prevSpecialties.items??[]).find((p:any)=>p.name===x.name),previousProduced=Number(py?.producedCents??0),change=previousProduced?((x.producedCents-previousProduced)/Math.abs(previousProduced))*100:null;return <tr key={x.name}><td><b>{x.name}</b></td><td>{money(x.producedCents)}</td><td>{money(previousProduced)}</td><td>{change==null?"—":`${change>=0?"+":""}${change.toFixed(1)}%`}</td><td>{money(x.directCostCents)}</td><td>{money(x.marginCents)}</td><td>{x.marginPercent==null?"—":`${x.marginPercent}%`}</td><td>{Number(x.marginCoveragePercent??100).toFixed(1)}%{x.marginIsComplete===false?" ⚠":""}</td></tr>})}</tbody></table>{!(specialties.items??[]).length&&<div className="native-empty">Sin producción clínica en este periodo.</div>}</section>
 <section className="native-grid two" style={{marginTop:14}}><div className="native-card"><h2>Facturación mes a mes</h2><Lines current={monthly.items??[]} previous={prevMonthly.items??[]}/><small>Azul {year} · discontinuo mismo período de {prev}</small></div><div className="native-card"><h2>Producción por tratamiento</h2><Bars items={treatments.items??[]} valueKey="producedCents"/></div></section>
 <section className="native-card" style={{marginTop:14}}><h2>Doctores</h2><table className="native-table"><thead><tr><th>Doctor</th><th>Producido</th><th>Facturado</th><th>Cobrado</th><th>Sillón</th><th>Prod./h</th><th>Margen/h</th><th>NPA</th><th>Retrat.</th></tr></thead><tbody>{(doctors.items??[]).map((x:any)=><tr key={x.id}><td><b>{x.name}</b></td><td>{money(x.producedCents)}</td><td>{money(x.billedCents)}</td><td>{money(x.collectedCents)}</td><td>{(Number(x.chairMinutes??0)/60).toFixed(1)} h</td><td>{money(x.producedPerHourCents)}</td><td>{money(x.marginPerHourCents)}</td><td>{x.noShowRatePercent}% ({x.noShowCount})</td><td>{x.reworkCount}</td></tr>)}</tbody></table></section>
 <section className="native-grid two" style={{marginTop:14}}><div className="native-card"><h2>Pérdidas e ineficiencias</h2><div className="native-kpi"><small>Total</small><strong>{money(losses.totalImpactCents??losses.totalLossCents??0)}</strong></div><Bars items={(losses.items??[]).map((x:any)=>({...x,name:lossLabel(x.name)}))} valueKey="impactCents"/></div><div className="native-card"><h2>Compras y materiales</h2><div className="native-kpi"><small>Gasto proveedores</small><strong>{money(purchases.totalCents??0)}</strong></div><Bars items={purchases.bySupplier??[]} valueKey="costCents"/><h3>Por categoría</h3><Bars items={purchases.byCategory??[]} valueKey="costCents"/></div></section>
 <section className="native-grid two" style={{marginTop:14}}><div className="native-card"><h2>Rentabilidad por tratamiento</h2><p><small>El coste directo usa la receta histórica del tratamiento y sustituye el laboratorio estándar por el coste real cuando existe. Las compras generales no se descuentan otra vez.</small></p><table className="native-table"><thead><tr><th>Área</th><th>Producido</th><th>Coste directo</th><th>Margen</th><th>%</th><th>Cobertura</th><th></th></tr></thead><tbody>{(treatments.items??[]).slice(0,15).map((x:any)=><tr key={x.name}><td>{x.name}</td><td>{money(x.producedCents)}</td><td>{money(x.directCostCents??x.costCents)}</td><td><b>{money(x.marginCents)}</b></td><td>{x.marginPercent==null?"—":`${x.marginPercent}%`}</td><td>{Number(x.marginCoveragePercent??100).toFixed(1)}%{x.marginIsComplete===false?" ⚠":""}</td><td><button className="native-button" disabled={drillBusy} onClick={()=>void openTreatment(x.name)}>Ver origen</button></td></tr>)}</tbody></table></div><div className="native-card"><h2>Recetas de coste vigentes e históricas</h2><table className="native-table"><thead><tr><th>Tratamiento</th><th>Desde</th><th>Hasta</th><th>Coste</th></tr></thead><tbody>{(recipes.items??[]).slice(0,20).map((r:any)=><tr key={r.id}><td><b>{r.name}</b><br/><small>{r.treatmentCode}</small></td><td>{new Date(r.activeFrom).toLocaleDateString("es-ES")}</td><td>{r.activeUntil?new Date(r.activeUntil).toLocaleDateString("es-ES"):"vigente"}</td><td>{money((r.items??[]).reduce((n:number,i:any)=>n+Number(i.quantity??1)*Number(i.unitCostCents??0),0))}</td></tr>)}</tbody></table></div></section>
 <section className="native-card" style={{marginTop:14}}><h2>Trazabilidad</h2><p><small>Cada cifra puede seguirse hasta el evento que la originó.</small></p><table className="native-table"><thead><tr><th>Fecha</th><th>Evento</th><th>Paciente</th><th>Doctor</th><th>Tratamiento</th><th>Ingreso</th><th>Coste</th><th>Pérdida</th></tr></thead><tbody>{(trace.items??[]).map((e:any)=><tr key={e.id}><td>{new Date(e.occurredAt).toLocaleDateString("es-ES")}</td><td>{e.type}</td><td>{e.patient?`${e.patient.firstName} ${e.patient.lastName}`:"—"}</td><td>{e.staff?.displayName??"—"}</td><td>{e.clinicalPlanItem?.label??e.category??"—"}</td><td>{e.revenueCents?money(e.revenueCents):"—"}</td><td>{e.costCents?money(e.costCents):"—"}</td><td>{e.lossCents?money(e.lossCents):"—"}</td></tr>)}</tbody></table>{!(trace.items??[]).length&&<div className="native-empty">Todavía no hay eventos analíticos en este periodo.</div>}</section>
 {drilldown&&<aside className="native-card" style={{position:"fixed",right:20,bottom:20,width:"min(720px,calc(100vw - 40px))",maxHeight:"75vh",overflow:"auto",zIndex:60}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><h2 style={{marginTop:0}}>Origen · {drilldown.category}</h2><small>{drilldown.summary?.quantity??0} tratamientos · margen {money(drilldown.summary?.marginCents??0)}</small></div><button className="native-button" onClick={()=>setDrilldown(null)}>×</button></div><table className="native-table"><thead><tr><th>Fecha</th><th>Paciente</th><th>Doctor</th><th>Evento</th><th>Tratamiento</th><th>Ingreso</th><th>Coste</th></tr></thead><tbody>{(drilldown.items??[]).map((e:any)=><tr key={e.id}><td>{new Date(e.occurredAt).toLocaleDateString("es-ES")}</td><td>{e.patient?`${e.patient.firstName} ${e.patient.lastName}`:"—"}</td><td>{e.staff?.displayName??"—"}</td><td>{e.type}</td><td>{e.clinicalPlanItem?.label??e.category??"—"}</td><td>{e.revenueCents?money(e.revenueCents):"—"}</td><td>{e.costCents?money(e.costCents):"—"}</td></tr>)}</tbody></table></aside>}
 </>}
