import type { ToothState } from "@/domain";

export const TOOTH_STATE_LABELS: Readonly<Record<ToothState, string>> = {
  healthy: "Sano",
  filling: "Obturación realizada",
  filling_bad: "Obturación insatisfactoria",
  filling_pending: "Obturación pendiente",
  crown: "Corona realizada",
  crown_bad: "Corona insatisfactoria",
  crown_pending: "Corona pendiente",
  endo: "Endodoncia realizada",
  endo_bad: "Endodoncia insatisfactoria",
  endo_indicated: "Endodoncia indicada",
  post: "Perno realizado",
  post_bad: "Perno insatisfactorio",
  post_pending: "Perno pendiente",
  implant: "Implante realizado",
  implant_review: "Implante a revisar",
  implant_indicated: "Implante indicado",
  prosthesis: "Prótesis fija realizada",
  prosthesis_bad: "Prótesis fija insatisfactoria",
  prosthesis_pending: "Prótesis fija pendiente",
  removable: "Removible realizada",
  removable_bad: "Removible insatisfactoria",
  removable_pending: "Removible pendiente",
  caries: "Caries",
  extraction: "Exodoncia indicada",
  missing: "Ausente",
};
