import type { FastifyInstance } from "fastify";
import { createPlanItemSchema, recordPreferenceSchema } from "@denty/contracts";
import { can } from "@denty/domain";
import { getActor } from "../../plugins/actor";
import { getCorrelationId } from "../../plugins/correlation";
import { addDependency, addPlanItem, approveAlternative, createAlternativeSet, createClinicalRework, createMissingToothAlternativeSet, getPlan, recordPreference, removeDependency, setItemStatus, syncBudgetFromPlan, updateAlternativeContext, updatePlanItemPriority, confirmAlternativeClassification } from "./service";
function clinical(actor:any,approve=false){if(!can(actor,approve?"clinical.approve_plan":"clinical.write"))throw Object.assign(new Error("Forbidden"),{statusCode:403});}
export async function registerClinicalRoutes(server:FastifyInstance){
 server.get<{Params:{patientId:string}}>("/api/patients/:patientId/clinical-plan",async request=>getPlan(await getActor(request),request.params.patientId));
 server.post<{Params:{patientId:string}}>("/api/patients/:patientId/clinical-plan/items",async(request,reply)=>{const actor=await getActor(request);clinical(actor);return reply.code(201).send(await addPlanItem(actor,request.params.patientId,createPlanItemSchema.parse(request.body),getCorrelationId(request)))});
 server.post<{Params:{id:string}}>("/api/clinical-plan/items/:id/status",async request=>{const actor=await getActor(request);clinical(actor);return setItemStatus(actor,request.params.id,String((request.body as any)?.status),getCorrelationId(request))});
 server.post<{Params:{id:string}}>("/api/clinical-plan/items/:id/priority-override",async request=>{const actor=await getActor(request);clinical(actor,true);const b=request.body as any;return updatePlanItemPriority(actor,request.params.id,{priority:Number(b.priority),phase:b.phase==null?undefined:Number(b.phase),reason:String(b.reason??"")},getCorrelationId(request))});
 server.post<{Params:{id:string}}>("/api/clinical-plan/items/:id/rework",async(request,reply)=>{const actor=await getActor(request);clinical(actor);return reply.code(201).send(await createClinicalRework(actor,request.params.id,request.body as any,getCorrelationId(request)))});
 server.post<{Params:{patientId:string}}>("/api/patients/:patientId/clinical-plan/alternatives/missing-tooth",async(request,reply)=>{const actor=await getActor(request);clinical(actor);const b=request.body as any;return reply.code(201).send(await createMissingToothAlternativeSet(actor,request.params.patientId,{toothOrZone:String(b.toothOrZone),availableData:Array.isArray(b.availableData)?b.availableData:[]},getCorrelationId(request)))});
 server.post<{Params:{patientId:string}}>("/api/patients/:patientId/clinical-plan/alternatives",async(request,reply)=>{const actor=await getActor(request);clinical(actor);const b=request.body as any;return reply.code(201).send(await createAlternativeSet(actor,request.params.patientId,{kind:b.kind,toothOrZone:String(b.toothOrZone),availableData:Array.isArray(b.availableData)?b.availableData:[],missingTeeth:Array.isArray(b.missingTeeth)?b.missingTeeth:[]},getCorrelationId(request)))});
 server.post<{Params:{patientId:string}}>("/api/patients/:patientId/clinical-plan/preferences",async(request,reply)=>{const actor=await getActor(request),b=recordPreferenceSchema.parse(request.body);return reply.code(201).send(await recordPreference(actor,request.params.patientId,b.optionId,b.preference,b.note,getCorrelationId(request)))});
 server.post<{Params:{optionId:string}}>("/api/clinical-plan/alternatives/:optionId/approve",async request=>{const actor=await getActor(request);clinical(actor,true);return approveAlternative(actor,request.params.optionId,getCorrelationId(request))});
 server.post<{Params:{planId:string}}>("/api/clinical-plans/:planId/dependencies",async(request,reply)=>{const actor=await getActor(request);clinical(actor,true);return reply.code(201).send(await addDependency(actor,request.params.planId,request.body as any,getCorrelationId(request)))});
 server.delete<{Params:{planId:string}}>("/api/clinical-plans/:planId/dependencies",async request=>{const actor=await getActor(request);clinical(actor,true);const q=request.query as any;return removeDependency(actor,request.params.planId,String(q.itemId),String(q.dependsOnId),String(q.reason??""),getCorrelationId(request))});
 server.patch<{Params:{setId:string}}>("/api/clinical-plan/alternative-sets/:setId/context",async request=>{const actor=await getActor(request);clinical(actor,true);return updateAlternativeContext(actor,request.params.setId,Array.isArray((request.body as any)?.availableData)?(request.body as any).availableData:[],getCorrelationId(request))});
 server.post<{Params:{setId:string}}>("/api/clinical-plan/alternative-sets/:setId/classification",async request=>{const actor=await getActor(request);clinical(actor,true);return confirmAlternativeClassification(actor,request.params.setId,String((request.body as any)?.classification??""),getCorrelationId(request))});
 server.post<{Params:{patientId:string}}>("/api/patients/:patientId/clinical-plan/budget",async request=>{const actor=await getActor(request);clinical(actor);return syncBudgetFromPlan(actor,request.params.patientId,getCorrelationId(request))});
}
