"use client";
import {useParams} from "next/navigation";
import {useState} from "react";
import {api,money} from "../../../lib/api";
import {useApiData,useRealtime} from "../../../lib/use-api-data";
function upcoming(appts:any[]){return appts.filter(a=>new Date(a.startsAt)>=new Date()&&!['CANCELLED','COMPLETED'].includes(a.status)).sort((a,b)=>a.startsAt.localeCompare(b.startsAt))[0]}
export default function PatientPortal(){
 const{patientId}=useParams<{patientId:string}>(),{data,refresh}=useApiData<any>(`/api/patient/${patientId}/projection`,{patient:{},appointments:[],plan:null,budgets:[],documents:[]});useRealtime(refresh);const next=upcoming(data.appointments??[]),[message,setMessage]=useState("");
 async function checkin(){if(!next)return;await api(`/api/patient/check-in/${next.id}`,{method:"POST",body:"{}"});await refresh()}
 async function prefer(optionId:string,preference:string){await api(`/api/patients/${patientId}/clinical-plan/preferences`,{method:"POST",body:JSON.stringify({optionId,preference})});await refresh()}
 async function acceptBudget(id:string){await api(`/api/patient/budgets/${id}/respond`,{method:"POST",body:JSON.stringify({})});await refresh()}
 async function signDocument(id:string){setMessage("");await api(`/api/documents/${id}/sign`,{method:"POST",body:JSON.stringify({signerName:`${data.patient?.firstName??""} ${data.patient?.lastName??""}`.trim()||"Paciente"})});setMessage("Documento firmado correctamente.");await refresh()}
 async function pay(b:any){setMessage("");const intent=await api<any>(`/api/patient/${patientId}/payment-intents`,{method:"POST",body:JSON.stringify({budgetId:b.id,amountCents:b.totalCents,currency:"EUR"})});if(intent.checkoutUrl){window.location.href=intent.checkoutUrl;return}setMessage("La clínica ha recibido tu solicitud de pago. El proveedor online no está configurado para esta cuenta.")}
 return <main className="native-denty" style={{maxWidth:980,margin:"0 auto",padding:"24px 14px 70px"}}><header className="native-topbar"><div><h1>Hola, {data.patient?.firstName}</h1><p>Tu tratamiento, explicado paso a paso.</p></div></header>{message&&<div className="native-card" style={{marginBottom:14}}>{message}</div>}
 {next&&<section className="native-card" style={{marginBottom:14}}><small>Próxima cita</small><h2>{new Date(next.startsAt).toLocaleString("es-ES")}</h2><p>{next.title}</p>{["PLANNED","CONFIRMED"].includes(next.status)&&<button className="native-button primary" onClick={checkin}>He llegado</button>}{next.status==="ARRIVED"&&<span className="native-badge">Ya estás en espera</span>}{next.status==="IN_CHAIR"&&<span className="native-badge">Estás en gabinete</span>}</section>}
 <section className="native-card"><h2>Tratamiento</h2><details open><summary><b>Ruta hasta terminar</b></summary><div style={{paddingTop:10}}>{data.plan?.route?.map((x:any,i:number)=><div key={x.id} className="appointment-card" style={{marginBottom:8}}><small>Paso {i+1}</small><b style={{display:"block"}}>{x.label}</b><span>{x.status==="COMPLETED"?"Completado":"Pendiente"}</span>{x.reason&&<p>{x.reason}</p>}</div>)}{!data.plan?.route?.length&&<p>No hay una ruta clínica secuenciada todavía.</p>}</div></details>
 <details><summary><b>Opciones de tratamiento</b></summary>{data.plan?.alternativeSets?.map((set:any)=><div key={set.id}><h3>{set.title}</h3>{set.options.map((o:any)=><div key={o.id} className="appointment-card" style={{marginBottom:9}}><b>{o.title}</b><p><b>Ventajas:</b> {(o.prosJson??[]).join(" · ")}</p><p><b>Inconvenientes:</b> {(o.consJson??[]).join(" · ")}</p><p>Tiempo relativo: {o.relativeTime??"—"} · Coste relativo: {o.relativeCost??"—"}</p>{Array.isArray(o.missingDataJson)&&o.missingDataJson.length>0&&<p><b>Antes de decidir falta valorar:</b> {o.missingDataJson.join(", ")}</p>}<div className="native-toolbar"><button className="native-button" onClick={()=>prefer(o.id,"INTERESTED")}>Me interesa</button><button className="native-button" onClick={()=>prefer(o.id,"DISCUSS")}>Quiero hablar de esta opción</button></div></div>)}</div>)}</details>
 <details><summary><b>Por qué este orden</b></summary><p>Denty muestra las dependencias que ha definido o validado la clínica. Un paso que necesita otro aparece después de él.</p></details>
 <details><summary><b>Documentos</b></summary><div style={{paddingTop:8}}><p><small>Al firmar aquí utilizas una firma electrónica simple con registro de evidencia e integridad del PDF.</small></p>{data.documents?.map((d:any)=><div key={d.id} className="appointment-card" style={{marginBottom:8}}><b>{d.title}</b><small style={{display:"block"}}>{d.status}{d.signedAt?` · firmado ${new Date(d.signedAt).toLocaleDateString("es-ES")}`:""}</small><div className="native-toolbar" style={{marginTop:7}}><a className="native-button" href={`/api/documents/${d.id}/file`} target="_blank" rel="noreferrer">Descargar PDF</a>{d.status==="FINAL"&&<button className="native-button primary" onClick={()=>void signDocument(d.id)}>Firmar</button>}</div></div>)}{!data.documents?.length&&<p>No tienes documentos disponibles todavía.</p>}</div></details></section>
 <section className="native-card" style={{marginTop:14}}><h2>Presupuestos</h2>{data.budgets?.map((b:any)=><div key={b.id} className="appointment-card" style={{marginBottom:8}}><b>{b.code}</b><span style={{float:"right"}}>{money(b.totalCents)}</span><p>{b.status}</p><div className="native-toolbar">{b.status==="PRESENTED"&&<button className="native-button primary" onClick={()=>acceptBudget(b.id)}>Aceptar presupuesto</button>}{["ACCEPTED","PARTIALLY_ACCEPTED"].includes(b.status)&&<button className="native-button primary" onClick={()=>void pay(b)}>Pagar</button>}</div></div>)}</section></main>}
