"use client";
import Link from "next/link";
import {useParams} from "next/navigation";
import {useEffect,useState} from "react";
import {api,money} from "../../../lib/api";
import {useApiData,useRealtime} from "../../../lib/use-api-data";
function upcoming(appts:any[]){return appts.filter(a=>new Date(a.startsAt)>=new Date()&&!['CANCELLED','COMPLETED'].includes(a.status)).sort((a,b)=>a.startsAt.localeCompare(b.startsAt))[0]}
function GamesIcon(){return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="M8.2 7.5h7.6a4.9 4.9 0 0 1 4.6 6.6l-.8 2.2a2.25 2.25 0 0 1-3.8.7l-1.1-1.4H9.3L8.2 17a2.25 2.25 0 0 1-3.8-.7l-.8-2.2a4.9 4.9 0 0 1 4.6-6.6Z"/><path d="M7.4 11.5h3M8.9 10v3M15.8 10.9h.01M17.6 12.7h.01"/></svg>}
function futureDateISO(offset=1){const d=new Date();d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)}
function slotLabel(value:string){return new Date(value).toLocaleTimeString("es-ES",{hour:"2-digit",minute:"2-digit"})}
export default function PatientPortal(){
 const{patientId}=useParams<{patientId:string}>(),{data,refresh}=useApiData<any>(`/api/patient/${patientId}/projection`,{patient:{},appointments:[],plan:null,budgets:[],documents:[]});useRealtime(refresh);const next=upcoming(data.appointments??[]),[message,setMessage]=useState("");
 const[bookingOpen,setBookingOpen]=useState(false),[bookingDate,setBookingDate]=useState(futureDateISO()),[availability,setAvailability]=useState<any>({sites:[]}),[availabilityLoading,setAvailabilityLoading]=useState(false),[requests,setRequests]=useState<any[]>([]),[appointmentNote,setAppointmentNote]=useState(""),[bookingError,setBookingError]=useState("");
 async function loadRequests(){try{const r=await api<any>(`/api/patient/${patientId}/appointment-requests`);setRequests(r.items??[])}catch{setRequests([])}}
 useEffect(()=>{void loadRequests()},[patientId]);
 async function loadAvailability(date=bookingDate){setAvailabilityLoading(true);setBookingError("");try{setAvailability(await api<any>(`/api/patient/${patientId}/appointment-availability?date=${date}&durationMin=30`))}catch(e:any){setBookingError(e?.payload?.error?.message??e?.message??"No se pudieron cargar los huecos.")}finally{setAvailabilityLoading(false)}}
 useEffect(()=>{if(bookingOpen)void loadAvailability(bookingDate)},[bookingOpen,bookingDate]);
 async function bookSlot(siteId:string,startsAt:string){setBookingError("");try{await api(`/api/patient/${patientId}/appointments/book`,{method:"POST",body:JSON.stringify({siteId,startsAt,durationMin:30,reason:appointmentNote||undefined})});setMessage("Cita confirmada. Ya aparece en tu próxima cita.");setBookingOpen(false);setAppointmentNote("");await Promise.all([refresh(),loadRequests()])}catch(e:any){setBookingError(e?.payload?.error?.message??e?.message??"Ese hueco ya no está disponible.");await loadAvailability()}}
 async function requestAppointment(){setMessage("");try{await api(`/api/patient/${patientId}/appointment-requests`,{method:"POST",body:JSON.stringify({note:appointmentNote||undefined})});setMessage("Solicitud enviada. Administración y secretaría ya la tienen disponible.");setAppointmentNote("");await loadRequests()}catch(e:any){setMessage(e?.payload?.error?.message??e?.message??"No se pudo enviar la solicitud.")}}
 async function checkin(){if(!next)return;await api(`/api/patient/check-in/${next.id}`,{method:"POST",body:"{}"});await refresh()}
 async function prefer(optionId:string,preference:string){await api(`/api/patients/${patientId}/clinical-plan/preferences`,{method:"POST",body:JSON.stringify({optionId,preference})});await refresh()}
 async function acceptBudget(id:string){await api(`/api/patient/budgets/${id}/respond`,{method:"POST",body:JSON.stringify({})});await refresh()}
 async function signDocument(id:string){setMessage("");await api(`/api/documents/${id}/sign`,{method:"POST",body:JSON.stringify({signerName:`${data.patient?.firstName??""} ${data.patient?.lastName??""}`.trim()||"Paciente"})});setMessage("Documento firmado correctamente.");await refresh()}
 async function pay(b:any){setMessage("");const intent=await api<any>(`/api/patient/${patientId}/payment-intents`,{method:"POST",body:JSON.stringify({budgetId:b.id,amountCents:b.totalCents,currency:"EUR"})});if(intent.checkoutUrl){window.location.href=intent.checkoutUrl;return}setMessage("La clínica ha recibido tu solicitud de pago. El proveedor online no está configurado para esta cuenta.")}
 return <main className="native-denty motion-page" style={{maxWidth:980,margin:"0 auto",padding:"24px 14px 70px"}}><header className="native-topbar"><div><h1>Hola, {data.patient?.firstName}</h1><p>Tu tratamiento, explicado paso a paso.</p></div></header>{message&&<div className="native-card" style={{marginBottom:14}}>{message}</div>}
 <nav className="patient-quick-access" aria-label="Accesos del paciente" data-motion-reveal><Link className="patient-games-entry" href={`/patient/${patientId}/games`}><span className="patient-games-entry-icon"><GamesIcon/></span><span className="patient-games-entry-copy"><strong>Juegos</strong><small>Partidas rápidas y tus récords</small></span><span className="patient-games-entry-arrow" aria-hidden="true">›</span></Link></nav>
 <section className="native-card patient-appointment-card" style={{marginBottom:14}} data-motion-reveal><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start",flexWrap:"wrap"}}><div><small>Citas</small><h2 style={{marginBottom:6}}>¿Cuándo quieres venir?</h2><p style={{margin:0}}>Elige uno de los huecos disponibles o pide que la clínica te dé cita.</p></div>{requests.some(r=>r.status==="PENDING")&&<span className="native-badge">Solicitud enviada</span>}</div><div className="native-toolbar" style={{marginTop:14}}><button className="native-button primary" onClick={()=>setBookingOpen(v=>!v)}>Elegir día y hora</button><button className="native-button" disabled={requests.some(r=>r.status==="PENDING")} onClick={()=>void requestAppointment()}>Solicitar cita</button></div><label style={{display:"block",marginTop:12}}>Motivo o nota opcional<textarea className="native-input" rows={2} value={appointmentNote} onChange={e=>setAppointmentNote(e.target.value)} placeholder="Ej. revisión, molestia, limpieza…" style={{display:"block",width:"100%",marginTop:6,resize:"vertical"}}/></label>{bookingOpen&&<div className="patient-booking-panel" style={{marginTop:14,paddingTop:14,borderTop:"1px solid var(--denty-line)"}}><div className="native-toolbar"><label>Día <input className="native-input" type="date" min={futureDateISO(0)} value={bookingDate} onChange={e=>setBookingDate(e.target.value)}/></label><button className="native-button" onClick={()=>void loadAvailability()}>Actualizar</button></div>{bookingError&&<p style={{color:"#b33"}}>{bookingError}</p>}{availabilityLoading?<p>Buscando huecos disponibles…</p>:<div className="native-grid" style={{marginTop:10}}>{(availability.sites??[]).map((group:any)=><div key={group.site.id} className="appointment-card"><b>{group.site.name}</b>{group.site.address&&<small style={{display:"block",marginTop:2}}>{group.site.address}</small>}<div className="patient-slot-grid" style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:10}}>{group.slots?.map((slot:any)=><button key={slot.startsAt} className="native-button soft" onClick={()=>void bookSlot(group.site.id,slot.startsAt)}>{slotLabel(slot.startsAt)}</button>)}{!group.slots?.length&&<small>No hay huecos este día.</small>}</div></div>)}{!(availability.sites??[]).length&&<p>No hay disponibilidad para ese día.</p>}</div>}</div>}</section>
 {next&&<section className="native-card" style={{marginBottom:14}} data-motion-reveal><small>Próxima cita</small><h2>{new Date(next.startsAt).toLocaleString("es-ES")}</h2><p>{next.title}</p>{["PLANNED","CONFIRMED"].includes(next.status)&&<button className="native-button primary" onClick={checkin}>He llegado</button>}{next.status==="ARRIVED"&&<span className="native-badge">Ya estás en espera</span>}{next.status==="IN_CHAIR"&&<span className="native-badge">Estás en gabinete</span>}</section>}
 <section className="native-card" data-motion-reveal><h2>Tratamiento</h2><details open><summary><b>Ruta hasta terminar</b></summary><div style={{paddingTop:10}}>{data.plan?.route?.map((x:any,i:number)=><div key={x.id} className="appointment-card" style={{marginBottom:8}}><small>Paso {i+1}</small><b style={{display:"block"}}>{x.label}</b><span>{x.status==="COMPLETED"?"Completado":"Pendiente"}</span>{x.reason&&<p>{x.reason}</p>}</div>)}{!data.plan?.route?.length&&<p>No hay una ruta clínica secuenciada todavía.</p>}</div></details>
 <details><summary><b>Opciones de tratamiento</b></summary>{data.plan?.alternativeSets?.map((set:any)=><div key={set.id}><h3>{set.title}</h3>{set.options.map((o:any)=><div key={o.id} className="appointment-card" style={{marginBottom:9}}><b>{o.title}</b><p><b>Ventajas:</b> {(o.prosJson??[]).join(" · ")}</p><p><b>Inconvenientes:</b> {(o.consJson??[]).join(" · ")}</p><p>Tiempo relativo: {o.relativeTime??"—"} · Coste relativo: {o.relativeCost??"—"}</p>{Array.isArray(o.missingDataJson)&&o.missingDataJson.length>0&&<p><b>Antes de decidir falta valorar:</b> {o.missingDataJson.join(", ")}</p>}<div className="native-toolbar"><button className="native-button" onClick={()=>prefer(o.id,"INTERESTED")}>Me interesa</button><button className="native-button" onClick={()=>prefer(o.id,"DISCUSS")}>Quiero hablar de esta opción</button></div></div>)}</div>)}</details>
 <details><summary><b>Por qué este orden</b></summary><p>Denty muestra las dependencias que ha definido o validado la clínica. Un paso que necesita otro aparece después de él.</p></details>
 <details><summary><b>Documentos</b></summary><div style={{paddingTop:8}}><p><small>Al firmar aquí utilizas una firma electrónica simple con registro de evidencia e integridad del PDF.</small></p>{data.documents?.map((d:any)=><div key={d.id} className="appointment-card" style={{marginBottom:8}}><b>{d.title}</b><small style={{display:"block"}}>{d.status}{d.signedAt?` · firmado ${new Date(d.signedAt).toLocaleDateString("es-ES")}`:""}</small><div className="native-toolbar" style={{marginTop:7}}><a className="native-button" href={`/api/documents/${d.id}/file`} target="_blank" rel="noreferrer">Descargar PDF</a>{d.status==="FINAL"&&<button className="native-button primary" onClick={()=>void signDocument(d.id)}>Firmar</button>}</div></div>)}{!data.documents?.length&&<p>No tienes documentos disponibles todavía.</p>}</div></details></section>
 <section className="native-card" style={{marginTop:14}} data-motion-reveal><h2>Presupuestos</h2>{data.budgets?.map((b:any)=><div key={b.id} className="appointment-card" style={{marginBottom:8}}><b>{b.code}</b><span style={{float:"right"}}>{money(b.totalCents)}</span><p>{b.status}</p><div className="native-toolbar">{b.status==="PRESENTED"&&<button className="native-button primary" onClick={()=>acceptBudget(b.id)}>Aceptar presupuesto</button>}{["ACCEPTED","PARTIALLY_ACCEPTED"].includes(b.status)&&<button className="native-button primary" onClick={()=>void pay(b)}>Pagar</button>}</div></div>)}</section></main>}
