import { prisma } from "@denty/db";
import { sendNotification } from "./provider";
let timer:NodeJS.Timeout|undefined;
const essential=new Set(["PASSWORD_RESET","PATIENT_INVITATION","SECURITY_ALERT","APPOINTMENT_CHANGE"]);
async function disabled(notification:any){if(essential.has(notification.type))return false;const owners=[...(notification.userId?[{userId:notification.userId}]:[]),...(notification.patientId?[{patientId:notification.patientId}]:[])];if(!owners.length)return false;const pref=await prisma.notificationPreference.findFirst({where:{clinicId:notification.clinicId,enabled:false,channel:notification.channel,OR:owners,type:{in:[notification.type,"*"]}}});return Boolean(pref)}
async function targetFor(notification:any){if(notification.userId){const u=await prisma.user.findUnique({where:{id:notification.userId}});return notification.channel==="EMAIL"?u?.email:null}if(notification.patientId){const p=await prisma.patient.findUnique({where:{id:notification.patientId}});return notification.channel==="EMAIL"?p?.email:notification.channel==="SMS"||notification.channel==="WHATSAPP"?p?.phone:null}return null}
export async function dispatchPendingNotifications(){const rows=await prisma.notification.findMany({where:{status:"PENDING",OR:[{scheduledAt:null},{scheduledAt:{lte:new Date()}}]},orderBy:{createdAt:"asc"},take:50});for(const n of rows){try{if(await disabled(n)){await prisma.notification.update({where:{id:n.id},data:{status:"SKIPPED",error:"Preferencia del usuario"}});continue}const result=await sendNotification({channel:n.channel,type:n.type,subject:n.subject,body:n.body,target:await targetFor(n),notificationId:n.id});await prisma.notification.update({where:{id:n.id},data:{status:result.status,sentAt:result.status==="SENT"?new Date():undefined,error:result.error}})}catch(e:any){await prisma.notification.update({where:{id:n.id},data:{status:"FAILED",error:String(e?.message??e).slice(0,500)}}).catch(()=>undefined)}}}
export function startNotificationDispatcher(){if(timer||process.env.DENTY_NOTIFICATION_DISPATCHER==="false")return;const ms=Math.max(10,Number(process.env.DENTY_NOTIFICATION_INTERVAL_SECONDS??30)||30)*1000;const first=setTimeout(()=>void dispatchPendingNotifications(),2_000);first.unref();timer=setInterval(()=>void dispatchPendingNotifications(),ms);timer.unref()}
export function stopNotificationDispatcher(){if(timer){clearInterval(timer);timer=undefined}}
