"use client";
import {useState} from "react";
import {api,money} from "../../../lib/api";
import {useApiData} from "../../../lib/use-api-data";
export default function Finance(){
 const{data:invoices,refresh}=useApiData<any>("/api/invoices",{items:[]}),{data:budgets}=useApiData<any>("/api/budgets",{items:[]}),{data:series,refresh:refreshSeries}=useApiData<any>("/api/invoice-series",{items:[]}),{data:payments,refresh:refreshPayments}=useApiData<any>("/api/payments",{items:[]}),[tab,setTab]=useState<"invoices"|"budgets"|"payments">("invoices"),[busy,setBusy]=useState<string>(""),[error,setError]=useState("");
 async function run(id:string,fn:()=>Promise<unknown>,alsoPayments=false){setBusy(id);setError("");try{await fn();await refresh();if(alsoPayments)await refreshPayments()}catch(e:any){setError(e?.payload?.error?.message??e?.message??"No se pudo completar la operación")}finally{setBusy("")}}
 async function ensureSeries(){const code=prompt("Código de serie","F");if(!code)return;await api("/api/invoice-series",{method:"POST",body:JSON.stringify({code,name:`Serie ${code}`})});await refreshSeries()}
 async function issue(id:string){await run(id,()=>api(`/api/invoices/${id}/issue`,{method:"POST",body:"{}"}))}
 async function submit(id:string){await run(id,()=>api(`/api/invoices/${id}/verifactu/submit`,{method:"POST",body:"{}"}))}
 async function rectify(x:any){const reason=prompt("Motivo de la rectificación");if(!reason)return;await run(x.id,()=>api(`/api/invoices/${x.id}/rectify`,{method:"POST",body:JSON.stringify({reason})}))}
 async function invoiceBudget(id:string){setError("");try{await api(`/api/budgets/${id}/invoice-draft`,{method:"POST",body:"{}"});await refresh();setTab("invoices")}catch(e:any){setError(e?.payload?.error?.message??e?.message??"No se pudo crear la factura")}}
 async function manualInvoice(){if(!series.items.length){setError("Crea una serie de facturación primero.");return}const type=(prompt("Tipo: STANDARD o SIMPLIFIED","STANDARD")??"STANDARD").toUpperCase();if(!["STANDARD","SIMPLIFIED"].includes(type)){setError("Tipo de factura no válido.");return}const customerName=prompt("Cliente / paciente",type==="SIMPLIFIED"?"Cliente":"")?.trim();if(!customerName)return;const description=prompt("Concepto","Servicios odontológicos")?.trim();if(!description)return;const euros=Number((prompt("Importe (€)","0")??"0").replace(",","."));if(!(euros>0))return;await api("/api/invoices",{method:"POST",body:JSON.stringify({seriesId:series.items[0].id,type,customerName,lines:[{description,quantity:1,unitPriceCents:Math.round(euros*100),taxRateBps:0}]})});await refresh();setTab("invoices")}
 async function recordPayment(){const patientId=prompt("patientId (opcional)")?.trim()||undefined,euros=Number((prompt("Importe cobrado (€)","0")??"0").replace(",","."));if(!(euros>0))return;const method=(prompt("Método: CASH, CARD, TRANSFER, FINANCING u OTHER","CARD")??"CARD").toUpperCase();const reference=prompt("Referencia (opcional)")?.trim()||undefined;setError("");try{await api("/api/payments",{method:"POST",body:JSON.stringify({patientId,amountCents:Math.round(euros*100),method,reference})});await refreshPayments();setTab("payments")}catch(e:any){setError(e?.payload?.error?.message??e?.message??"No se pudo registrar el cobro")}}
 async function allocate(p:any){const open=invoices.items.filter((i:any)=>["ISSUED","RECTIFIED"].includes(i.status)&&i.allocations.reduce((n:number,a:any)=>n+a.amountCents,0)<i.totalCents);if(!open.length){setError("No hay facturas emitidas con saldo pendiente.");return}const invoiceId=prompt(`Factura a asignar:\n${open.map((i:any)=>`${i.id} · ${i.fullNumber} · ${money(i.totalCents-i.allocations.reduce((n:number,a:any)=>n+a.amountCents,0))} pendiente`).join("\n")}`,open[0].id)?.trim();if(!invoiceId)return;const remaining=p.amountCents-(p.allocations??[]).reduce((n:number,a:any)=>n+a.amountCents,0),euros=Number((prompt("Importe a asignar (€)",(remaining/100).toFixed(2))??"0").replace(",","."));if(!(euros>0))return;await run(p.id,()=>api(`/api/payments/${p.id}/allocate`,{method:"POST",body:JSON.stringify({invoiceId,amountCents:Math.round(euros*100)})}),true)}
 async function exportAccounting(){const year=new Date().getFullYear(),response=await fetch(`/api/accounting/export.csv?start=${year}-01-01T00:00:00.000Z&end=${year}-12-31T23:59:59.999Z`,{credentials:"include"});if(!response.ok)throw new Error("No se pudo exportar la contabilidad");const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`contabilidad-${year}.csv`;a.click();URL.revokeObjectURL(url)}
 return <><header className="native-topbar"><div><h1>Finanzas</h1><p>Presupuesto, factura, factura rectificativa y cobro son entidades distintas.</p></div><div className="native-toolbar"><button className="native-button" onClick={exportAccounting}>Exportar CSV</button><button className="native-button" onClick={ensureSeries}>Series ({series.items.length})</button><button className="native-button" onClick={()=>void manualInvoice()}>+ Factura</button><button className="native-button primary" onClick={()=>void recordPayment()}>Registrar cobro</button></div></header>{error&&<div className="native-error">{error}</div>}<div className="native-toolbar"><button className={`native-button ${tab==="invoices"?"soft":""}`} onClick={()=>setTab("invoices")}>Facturas</button><button className={`native-button ${tab==="budgets"?"soft":""}`} onClick={()=>setTab("budgets")}>Presupuestos</button><button className={`native-button ${tab==="payments"?"soft":""}`} onClick={()=>setTab("payments")}>Cobros</button></div>
 {tab==="invoices"?<div className="native-card"><table className="native-table"><thead><tr><th>Número</th><th>Tipo</th><th>Paciente/cliente</th><th>Estado</th><th>Total</th><th>Cobrado</th><th>Fiscal</th><th></th></tr></thead><tbody>{invoices.items.map((x:any)=>{const submissions=x.fiscalRecord?.submissions??[],accepted=submissions.some((s:any)=>s.status==="ACCEPTED"),last=submissions.at(-1),paid=x.allocations?.reduce((n:number,a:any)=>n+a.amountCents,0)??0;return <tr key={x.id}><td>{x.fullNumber??"Borrador"}</td><td>{x.type}</td><td>{x.customerName}</td><td><span className="native-badge">{x.status}</span></td><td>{money(x.totalCents)}</td><td>{money(paid)}</td><td>{x.status==="DRAFT"?"—":accepted?<span className="native-badge">AEAT aceptado</span>:last?<span className="native-badge">{last.status}</span>:<span className="native-badge">Pendiente envío</span>}</td><td><div className="native-toolbar">{x.status==="DRAFT"&&<button disabled={busy===x.id} className="native-button" onClick={()=>void issue(x.id)}>Emitir</button>}{x.status==="ISSUED"&&<button disabled={busy===x.id} className="native-button" onClick={()=>void rectify(x)}>Rectificar</button>}{["ISSUED","RECTIFIED"].includes(x.status)&&<button className="native-button" onClick={()=>window.open(`/api/invoices/${x.id}/pdf`,"_blank","noopener,noreferrer")}>Ver PDF</button>}{["ISSUED","RECTIFIED"].includes(x.status)&&!accepted&&<button disabled={busy===x.id} className="native-button" onClick={()=>void submit(x.id)}>Remitir VERI*FACTU</button>}</div></td></tr>})}</tbody></table></div>:tab==="budgets"?<div className="native-card"><table className="native-table"><thead><tr><th>Presupuesto</th><th>Paciente</th><th>Estado</th><th>Total</th><th></th></tr></thead><tbody>{budgets.items.map((x:any)=><tr key={x.id}><td>{x.code}</td><td>{x.patient.firstName} {x.patient.lastName}</td><td>{x.status}</td><td>{money(x.totalCents)}</td><td><button className="native-button" onClick={()=>void invoiceBudget(x.id)}>Crear factura</button></td></tr>)}</tbody></table></div>:<div className="native-card"><table className="native-table"><thead><tr><th>Fecha</th><th>Referencia</th><th>Método</th><th>Total</th><th>Asignado</th><th></th></tr></thead><tbody>{payments.items.map((p:any)=>{const used=(p.allocations??[]).reduce((n:number,a:any)=>n+a.amountCents,0);return <tr key={p.id}><td>{new Date(p.receivedAt).toLocaleString("es-ES")}</td><td>{p.reference??p.id}</td><td>{p.method}</td><td>{money(p.amountCents)}</td><td>{money(used)}</td><td>{used<p.amountCents&&<button className="native-button" onClick={()=>void allocate(p)}>Asignar</button>}</td></tr>})}</tbody></table></div>}</>}
