import type { FastifyInstance } from "fastify";
import { createLabWorkSchema, labTransitionSchema } from "@denty/contracts";
import { can, appointmentBeforeEta } from "@denty/domain";
import { prisma } from "@denty/db";
import { getActor } from "../../plugins/actor";
import { getCorrelationId } from "../../plugins/correlation";
import { createLabWork, createRework, transitionLabWork } from "./service";
import { addLabAttachment, readLabAttachment } from "./attachments";
export async function registerLaboratoryRoutes(server:FastifyInstance){server.get("/api/lab-works",async request=>{const actor=await getActor(request);if(!can(actor,"lab.read"))throw Object.assign(new Error("Forbidden"),{statusCode:403});const items=await prisma.labWork.findMany({where:{clinicId:actor.clinicId},include:{lab:true,patient:true,events:true,attachments:true},orderBy:[{etaAt:"asc"},{createdAt:"desc"}]});return{items}});server.post("/api/lab-works",async(request,reply)=>{const actor=await getActor(request);if(!can(actor,"lab.write"))throw Object.assign(new Error("Forbidden"),{statusCode:403});return reply.code(201).send(await createLabWork(actor,createLabWorkSchema.parse(request.body),getCorrelationId(request)))});server.post<{Params:{id:string}}>("/api/lab-works/:id/transition",async request=>{const actor=await getActor(request);if(!can(actor,"lab.write"))throw Object.assign(new Error("Forbidden"),{statusCode:403});return transitionLabWork(actor,request.params.id,labTransitionSchema.parse(request.body),getCorrelationId(request))});server.post<{Params:{id:string}}>("/api/lab-works/:id/rework",async request=>{const actor=await getActor(request);if(!can(actor,"lab.write"))throw Object.assign(new Error("Forbidden"),{statusCode:403});return createRework(actor,request.params.id,request.body,getCorrelationId(request))});server.get<{Params:{id:string}}>("/api/lab-works/:id/agenda-warning",async request=>{const actor=await getActor(request),work=await prisma.labWork.findFirstOrThrow({where:{id:request.params.id,clinicId:actor.clinicId}});if(!work.etaAt)return{warning:false};const appts=work.clinicalPlanItemId?await prisma.appointment.findMany({where:{clinicalPlanItemId:work.clinicalPlanItemId,status:{notIn:["CANCELLED","COMPLETED"]}}}):[];const risky=appts.filter(a=>appointmentBeforeEta(a.startsAt,work.etaAt!));return{warning:risky.length>0,appointments:risky.map(x=>({id:x.id,startsAt:x.startsAt}))}});server.post<{Params:{id:string}}>("/api/lab-works/:id/attachments",async(request,reply)=>{const actor=await getActor(request);if(!can(actor,"lab.write"))throw Object.assign(new Error("Forbidden"),{statusCode:403});return reply.code(201).send(await addLabAttachment(actor,request.params.id,request.body as any,getCorrelationId(request)))});server.get<{Params:{id:string;attachmentId:string}}>("/api/lab-works/:id/attachments/:attachmentId",async(request,reply)=>{const actor=await getActor(request);if(!can(actor,"lab.read"))throw Object.assign(new Error("Forbidden"),{statusCode:403});const result=await readLabAttachment(actor,request.params.id,request.params.attachmentId);reply.header("Content-Disposition",`attachment; filename="${result.attachment.fileName.replace(/"/g,"_")}"`);reply.type(result.attachment.mimeType);return reply.send(result.data)});}
