import { createHash, randomBytes } from "node:crypto";
import { prisma, runBusinessTransaction, writeAnalyticsEvent, writeAudit, writeDomainEvent } from "@denty/db";
import { writePaymentAllocationAttribution } from "../analytics/financial-attribution";
import { permissionsForRole, type ActorContext } from "@denty/domain";
import { hashPassword } from "../../auth/credentials";

function sha(v:string){return createHash("sha256").update(v).digest("hex")}
export async function createPatientInvitation(actor:ActorContext,patientId:string,input:{email?:string;phone?:string;expiresHours?:number},correlationId:string){await prisma.patient.findFirstOrThrow({where:{id:patientId,clinicId:actor.clinicId}});const token=randomBytes(32).toString("base64url"),expiresAt=new Date(Date.now()+(input.expiresHours??72)*3600_000);const inv=await prisma.patientInvitation.create({data:{clinicId:actor.clinicId,patientId,tokenHash:sha(token),email:input.email,phone:input.phone,expiresAt}});await prisma.notification.create({data:{clinicId:actor.clinicId,patientId,channel:input.email?"EMAIL":"MANUAL",type:"PATIENT_INVITATION",subject:"Acceso a Denty Paciente",body:`Invitación creada. Token de un solo uso: ${token}`,status:"PENDING"}});return{id:inv.id,token,expiresAt};}
export async function claimPatientInvitation(token:string,input:{displayName:string;email?:string;username?:string;password:string}){const inv=await prisma.patientInvitation.findUnique({where:{tokenHash:sha(token)}});if(!inv||inv.revokedAt||inv.acceptedAt||inv.expiresAt<=new Date())throw Object.assign(new Error("Invitation invalid or expired"),{statusCode:400});const passwordHash=await hashPassword(input.password);return prisma.$transaction(async tx=>{let user=inv.userId?await tx.user.findUnique({where:{id:inv.userId}}):null;if(!user)user=await tx.user.create({data:{clinicId:inv.clinicId,displayName:input.displayName,email:input.email??inv.email,username:input.username,role:"PATIENT",credential:{create:{passwordHash}}}});else await tx.userCredential.upsert({where:{userId:user.id},create:{userId:user.id,passwordHash},update:{passwordHash}});await tx.patientAccessGrant.upsert({where:{userId_patientId:{userId:user.id,patientId:inv.patientId}},create:{userId:user.id,patientId:inv.patientId,relation:"self"},update:{active:true}});await tx.patientInvitation.update({where:{id:inv.id},data:{userId:user.id,acceptedAt:new Date()}});return{id:user.id,role:"PATIENT",permissions:permissionsForRole("PATIENT")};});}
export async function patientProjection(actor:ActorContext,patientId:string){if(actor.role==="PATIENT"&&!actor.patientIds?.includes(patientId))throw Object.assign(new Error("Forbidden"),{statusCode:403});const [patient,appointments,plan,budgets,documents]=await Promise.all([prisma.patient.findFirstOrThrow({where:{id:patientId,clinicId:actor.clinicId},select:{id:true,firstName:true,lastName:true,phone:true,email:true}}),prisma.appointment.findMany({where:{clinicId:actor.clinicId,patientId,status:{not:"CANCELLED"}},orderBy:{startsAt:"asc"}}),prisma.clinicalPlan.findFirst({where:{clinicId:actor.clinicId,patientId,status:"ACTIVE"},include:{items:true,alternativeSets:{include:{options:{include:{preferences:true}}}}}}),prisma.budget.findMany({where:{clinicId:actor.clinicId,patientId,status:{in:["PRESENTED","ACCEPTED","PARTIALLY_ACCEPTED"]}},include:{items:true},orderBy:{createdAt:"desc"}}),prisma.document.findMany({where:{clinicId:actor.clinicId,patientId,status:{in:["FINAL","SIGNED"]},archivedAt:null},select:{id:true,title:true,type:true,status:true,createdAt:true,signedAt:true,deliveredAt:true}})]);let route:any[]=[];if(plan){const deps=await prisma.clinicalPlanDependency.findMany({where:{planId:plan.id}});const by=new Map(plan.items.map(x=>[x.id,x])),seen=new Set<string>();const visit=(x:any)=>{if(seen.has(x.id))return;for(const d of deps.filter(d=>d.itemId===x.id)){const prev=by.get(d.dependsOnId);if(prev)visit(prev)}seen.add(x.id);route.push({id:x.id,label:x.patientLabel??x.label,status:x.status,tooth:x.tooth,reason:x.clinicalReason,dependsOn:deps.filter(d=>d.itemId===x.id).map(d=>d.dependsOnId)})};[...plan.items].sort((a,b)=>a.phase-b.phase||b.priority-a.priority).forEach(visit)}return{patient,appointments,plan:plan?{id:plan.id,title:plan.title,route,alternativeSets:plan.alternativeSets}:null,budgets,documents};}
export async function patientCheckIn(actor:ActorContext,appointmentId:string,correlationId:string){return runBusinessTransaction(prisma,async tx=>{const ap=await tx.appointment.findFirstOrThrow({where:{id:appointmentId,clinicId:actor.clinicId}});if(actor.role==="PATIENT"&&!actor.patientIds?.includes(ap.patientId))throw Object.assign(new Error("Forbidden"),{statusCode:403});if(!["PLANNED","CONFIRMED"].includes(ap.status))throw Object.assign(new Error("Appointment cannot be checked in"),{statusCode:409});const updated=await tx.appointment.update({where:{id:ap.id},data:{status:"ARRIVED",arrivedAt:new Date(),version:{increment:1}}});await writeAudit(tx,{clinicId:actor.clinicId,actorUserId:actor.userId,action:"appointment.arrived",entityType:"appointment",entityId:ap.id,correlationId,before:{status:ap.status},after:{status:updated.status,version:updated.version}});await writeDomainEvent(tx,{clinicId:actor.clinicId,actorUserId:actor.userId,type:"appointment.arrived",entityType:"appointment",entityId:ap.id,correlationId,payload:{patientId:ap.patientId,staffId:ap.staffId,arrivedAt:updated.arrivedAt,version:updated.version}});return updated;});}
export async function acceptBudget(actor:ActorContext,budgetId:string,input:{acceptedItemIds?:string[];termsVersion?:string;ipHash?:string;userAgentHash?:string},correlationId:string){return runBusinessTransaction(prisma,async tx=>{const budget=await tx.budget.findFirstOrThrow({where:{id:budgetId,clinicId:actor.clinicId},include:{items:true}});if(actor.role==="PATIENT"&&!actor.patientIds?.includes(budget.patientId))throw Object.assign(new Error("Forbidden"),{statusCode:403});const selected=new Set(input.acceptedItemIds??budget.items.map(x=>x.id));for(const item of budget.items)await tx.budgetItem.update({where:{id:item.id},data:{accepted:selected.has(item.id)}});const all=budget.items.every(x=>selected.has(x.id)),some=budget.items.some(x=>selected.has(x.id));const status=all?"ACCEPTED":some?"PARTIALLY_ACCEPTED":"REJECTED";const updated=await tx.budget.update({where:{id:budget.id},data:{status,acceptedAt:some?new Date():null,version:{increment:1}}});if(some)await tx.budgetAcceptance.create({data:{budgetId:budget.id,patientId:budget.patientId,acceptedByUserId:actor.userId,acceptedItemIdsJson:[...selected],termsVersion:String(input.termsVersion??"v1"),ipHash:input.ipHash,userAgentHash:input.userAgentHash}});const selectedItems=budget.items.filter(x=>selected.has(x.id)),selectedBase=selectedItems.reduce((n,x)=>n+Math.max(0,x.quantity*x.unitPriceCents),0),allBase=budget.items.reduce((n,x)=>n+Math.max(0,x.quantity*x.unitPriceCents),0),lineDiscount=selectedItems.reduce((n,x)=>n+Math.max(0,x.discountCents),0),globalDiscount=some&&allBase>0?Math.round(Math.max(0,budget.discountCents)*(selectedBase/allBase)):0,acceptedDiscountCents=lineDiscount+globalDiscount;await writeAnalyticsEvent(tx,{clinicId:actor.clinicId,type:"discount.applied",patientId:budget.patientId,lossCents:acceptedDiscountCents,metadata:{budgetId:budget.id,status,acceptedItemIds:[...selected],lineDiscountCents:lineDiscount,globalDiscountCents:globalDiscount},correlationId,dedupeKey:`discount.applied:${budget.id}`,replaceOnDedupe:true});await writeDomainEvent(tx,{clinicId:actor.clinicId,actorUserId:actor.userId,type:"budget.patient_response",entityType:"budget",entityId:budget.id,correlationId,payload:{patientId:budget.patientId,status,acceptedItemIds:[...selected]}});return updated;});}
function assertPositivePaymentAmount(value:unknown){const amountCents=Number(value);if(!Number.isSafeInteger(amountCents)||amountCents<=0)throw Object.assign(new Error("El importe del pago debe ser un número entero positivo de céntimos"),{statusCode:400,code:"PAYMENT_AMOUNT_INVALID"});return amountCents}
async function validatePaymentTarget(actor:ActorContext,patientId:string,input:{invoiceId?:string;budgetId?:string;amountCents:number}){await prisma.patient.findFirstOrThrow({where:{id:patientId,clinicId:actor.clinicId}});if(input.invoiceId&&input.budgetId)throw Object.assign(new Error("Selecciona factura o presupuesto, no ambos"),{statusCode:400,code:"PAYMENT_TARGET_AMBIGUOUS"});let remainingCents:number|undefined;if(input.invoiceId){const invoice=await prisma.invoice.findFirstOrThrow({where:{id:input.invoiceId,clinicId:actor.clinicId,patientId},include:{allocations:true}});const paid=invoice.allocations.reduce((sum,x)=>sum+x.amountCents,0);remainingCents=Math.max(0,invoice.totalCents-paid)}else if(input.budgetId){const budget=await prisma.budget.findFirstOrThrow({where:{id:input.budgetId,clinicId:actor.clinicId,patientId}});remainingCents=Math.max(0,budget.totalCents)}if(remainingCents!=null&&input.amountCents>remainingCents)throw Object.assign(new Error("El importe supera el saldo del documento seleccionado"),{statusCode:409,code:"PAYMENT_EXCEEDS_BALANCE",current:{remainingCents}});return{remainingCents}}
export async function createPaymentIntent(actor:ActorContext,patientId:string,input:any){if(actor.role==="PATIENT"&&!actor.patientIds?.includes(patientId))throw Object.assign(new Error("Forbidden"),{statusCode:403});const amountCents=assertPositivePaymentAmount(input.amountCents);await validatePaymentTarget(actor,patientId,{invoiceId:input.invoiceId,budgetId:input.budgetId,amountCents});const provider=process.env.DENTY_PAYMENT_PROVIDER??"manual";let checkoutUrl:string|undefined,providerRef:string|undefined;if(provider!=="manual"&&process.env.DENTY_PAYMENT_CHECKOUT_ENDPOINT){const response=await fetch(process.env.DENTY_PAYMENT_CHECKOUT_ENDPOINT,{method:"POST",headers:{"content-type":"application/json","authorization":process.env.DENTY_PAYMENT_API_KEY?`Bearer ${process.env.DENTY_PAYMENT_API_KEY}`:""},body:JSON.stringify({amountCents,currency:input.currency??"EUR",patientId,reference:input.invoiceId??input.budgetId})});if(!response.ok)throw new Error("Payment provider rejected checkout creation");const payload=await response.json() as any;checkoutUrl=String(payload.checkoutUrl??"")||undefined;providerRef=String(payload.id??payload.providerRef??"")||undefined;if(!providerRef)throw Object.assign(new Error("El proveedor no devolvió referencia de pago"),{statusCode:502,code:"PAYMENT_PROVIDER_REFERENCE_MISSING"});}return prisma.paymentIntent.create({data:{clinicId:actor.clinicId,userId:actor.userId,patientId,budgetId:input.budgetId,invoiceId:input.invoiceId,amountCents,currency:input.currency??"EUR",provider,providerRef,status:checkoutUrl?"PENDING":"MANUAL",checkoutUrl,expiresAt:input.expiresAt?new Date(input.expiresAt):undefined}})}


export async function listFamilyGrants(actor:ActorContext,patientId:string){
  const patient=await prisma.patient.findFirstOrThrow({where:{id:patientId,clinicId:actor.clinicId}});
  if(actor.role==="PATIENT"&&!actor.patientIds?.includes(patient.id))throw Object.assign(new Error("Forbidden"),{statusCode:403});
  return prisma.patientAccessGrant.findMany({where:{patientId:patient.id,active:true},include:{user:{select:{id:true,displayName:true,email:true,username:true,role:true}}},orderBy:{createdAt:"asc"}});
}

export async function createFamilyGrant(actor:ActorContext,patientId:string,input:{userId:string;relation?:string},correlationId:string){return runBusinessTransaction(prisma,async tx=>{
  const [patient,user]=await Promise.all([tx.patient.findFirstOrThrow({where:{id:patientId,clinicId:actor.clinicId}}),tx.user.findFirstOrThrow({where:{id:input.userId,clinicId:actor.clinicId,active:true}})]);
  if(user.role!=="PATIENT")throw Object.assign(new Error("Solo una cuenta de paciente puede recibir acceso familiar."),{statusCode:409});
  const relation=String(input.relation??"family").trim().toLowerCase().slice(0,40)||"family";
  const grant=await tx.patientAccessGrant.upsert({where:{userId_patientId:{userId:user.id,patientId:patient.id}},create:{userId:user.id,patientId:patient.id,relation,active:true},update:{relation,active:true}});
  await writeAudit(tx,{clinicId:actor.clinicId,actorUserId:actor.userId,action:"patient.family_grant_created",entityType:"patient",entityId:patient.id,correlationId,after:{grantId:grant.id,userId:user.id,relation}});
  await writeDomainEvent(tx,{clinicId:actor.clinicId,actorUserId:actor.userId,type:"patient.family_grant_created",entityType:"patient",entityId:patient.id,correlationId,payload:{grantId:grant.id,userId:user.id,relation}});
  return grant;
});}

export async function revokeFamilyGrant(actor:ActorContext,patientId:string,grantId:string,correlationId:string){return runBusinessTransaction(prisma,async tx=>{
  const grant=await tx.patientAccessGrant.findFirstOrThrow({where:{id:grantId,patientId,patient:{clinicId:actor.clinicId}}});
  if(grant.relation==="self")throw Object.assign(new Error("El acceso propio del paciente no se revoca desde acceso familiar."),{statusCode:409});
  const updated=await tx.patientAccessGrant.update({where:{id:grant.id},data:{active:false}});
  await writeAudit(tx,{clinicId:actor.clinicId,actorUserId:actor.userId,action:"patient.family_grant_revoked",entityType:"patient",entityId:patientId,correlationId,before:{grantId:grant.id,userId:grant.userId,active:true},after:{active:false}});
  await writeDomainEvent(tx,{clinicId:actor.clinicId,actorUserId:actor.userId,type:"patient.family_grant_revoked",entityType:"patient",entityId:patientId,correlationId,payload:{grantId:grant.id,userId:grant.userId}});
  return updated;
});}


export async function settlePaymentIntentFromProvider(input:{provider:string;providerRef:string;status:string;amountCents?:number;method?:string},correlationId:string){
  const providerName=String(input.provider??process.env.DENTY_PAYMENT_PROVIDER??"").trim(),providerRef=String(input.providerRef??"").trim();if(!providerName||!providerRef)throw Object.assign(new Error("Falta proveedor o providerRef"),{statusCode:400});
  const current=await prisma.paymentIntent.findFirst({where:{provider:providerName,providerRef}});if(!current)throw Object.assign(new Error("PaymentIntent no encontrado"),{statusCode:404});
  const normalized=String(input.status??"").toUpperCase();if(!["PAID","SUCCEEDED","COMPLETED"].includes(normalized)){return prisma.paymentIntent.update({where:{id:current.id},data:{status:normalized||"FAILED"}})}
  if(input.amountCents!=null&&Number(input.amountCents)!==current.amountCents)throw Object.assign(new Error("El importe confirmado por el proveedor no coincide con la intención de pago"),{statusCode:409});
  return runBusinessTransaction(prisma,async tx=>{
    const intent=await tx.paymentIntent.findUniqueOrThrow({where:{id:current.id}}),reference=`provider:${providerName}:${providerRef}`;
    const existing=await tx.payment.findFirst({where:{clinicId:intent.clinicId,reference}});if(intent.status==="PAID"&&existing)return{intent,payment:existing,idempotent:true};
    if(intent.invoiceId){const invoice=await tx.invoice.findFirstOrThrow({where:{id:intent.invoiceId,clinicId:intent.clinicId,patientId:intent.patientId},include:{allocations:true}});const paid=invoice.allocations.reduce((sum,x)=>sum+x.amountCents,0);if(paid+intent.amountCents>invoice.totalCents)throw Object.assign(new Error("El pago confirmado superaría el total pendiente de la factura"),{statusCode:409,code:"INVOICE_OVER_ALLOCATION",current:{remainingCents:Math.max(0,invoice.totalCents-paid)}})}
    const method=normalizeProviderPaymentMethod(input.method),payment=existing??await tx.payment.create({data:{clinicId:intent.clinicId,patientId:intent.patientId,amountCents:intent.amountCents,currency:intent.currency,method,reference}});
    if(intent.invoiceId)await tx.paymentAllocation.upsert({where:{paymentId_invoiceId:{paymentId:payment.id,invoiceId:intent.invoiceId}},create:{paymentId:payment.id,invoiceId:intent.invoiceId,amountCents:intent.amountCents},update:{amountCents:intent.amountCents}});
    const updated=await tx.paymentIntent.update({where:{id:intent.id},data:{status:"PAID"}});
    await writeAudit(tx,{clinicId:intent.clinicId,action:"payment.provider_settled",entityType:"payment_intent",entityId:intent.id,correlationId,before:{status:intent.status},after:{status:"PAID",paymentId:payment.id,amountCents:payment.amountCents}});
    await writeDomainEvent(tx,{clinicId:intent.clinicId,type:"payment.received",entityType:"payment",entityId:payment.id,correlationId,payload:{patientId:intent.patientId,paymentIntentId:intent.id,invoiceId:intent.invoiceId,amountCents:payment.amountCents,provider:intent.provider}});
    await writeAnalyticsEvent(tx,{clinicId:intent.clinicId,type:"payment.received",patientId:intent.patientId,paymentId:payment.id,revenueCents:payment.amountCents,correlationId,metadata:{provider:intent.provider,paymentIntentId:intent.id},dedupeKey:`payment.received:${payment.id}`});
    if(intent.invoiceId)await writePaymentAllocationAttribution(tx,{clinicId:intent.clinicId,patientId:intent.patientId,paymentId:payment.id,invoiceId:intent.invoiceId,amountCents:intent.amountCents,correlationId});
    return{intent:updated,payment,idempotent:Boolean(existing)};
  });
}
function normalizeProviderPaymentMethod(value?:string){const v=String(value??"CARD").toUpperCase();return (["CASH","CARD","TRANSFER","FINANCING","OTHER"] as const).includes(v as any)?v as "CASH"|"CARD"|"TRANSFER"|"FINANCING"|"OTHER":"OTHER";}
